---
title: "Time Series Plots"
author: "Vanessa Neo"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r load_packages}

library(tidyverse)
library(lubridate)
library(patchwork)
library(plotly)
library(ggstream)

```

```{r Browse_Island_BRS07}

Browse_07_CCI <- read_csv(here::here("data_raw", "CCI_BRS07.csv"))
Browse_07_CCI <- Browse_07_CCI %>% 
  mutate(sst = as.numeric(str_sub(Browse_07_CCI$`mean temperature deg C`, 3, 13))) %>%  #remove punctuation [[ and ]] from temperature data
  select(-`mean temperature deg C`) %>%  #remove column with [[ and ]]
  mutate(data_type = "CCI") %>%  #prepare data for binding with other data types
  rename(date = daily_date) %>%  #prepare data for binding with other data types
  select(data_type, date, sst) #select only useful columns

Browse_07_CCore <- read_csv(here::here("data_raw", "CCore_BRS05_BRS07_Year_Month.csv"))
Browse_07_CCore <- Browse_07_CCore %>% 
  mutate(data_type = "Coral Core") %>% #prepare data for binding with other data types
  mutate(date = str_c(year, month, sep = "-")) %>% #stringing year and month
  mutate(date = ym(date)) %>% #converting date column fr chr to date format
  select(data_type, date, `BRS07 Sr/Ca [mmol/mol]`)  #select only useful columns

Browse_07_CCore_CCI <- read_csv(here::here("data_raw", "CCore_SST_BRS07_CCI.csv")) %>% 
  mutate(data_type = "Coral Core CCI calibrated SST", .before = "date") %>% 
  select(data_type, date, sst)

Browse_07_CCore_NOAA <- read_csv(here::here("data_raw", "CCore_SST_BRS07_NOAA.csv")) %>% 
  mutate(data_type = "Coral Core NOAA calibrated SST", .before = "date") %>% 
  select(data_type, date, sst)

Browse_07_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_SCOTTSS1.csv"))
Browse_07_Logger <- Browse_07_Logger %>% 
  rename(sst = mean_SST) %>% #prepare data for binding with other data types
  mutate(data_type = "Logger") %>% #prepare data for binding with other data types
  select(subsite, data_type, date, sst)  #select only useful columns

Browse_07_NOAA <- read_csv(here::here("data_raw", "NOAA_BRS07_SST.csv"))
Browse_07_NOAA <- Browse_07_NOAA %>% 
  mutate(data_type = "NOAA") %>%  #prepare data for binding with other data types
  select(-date) %>% #remove monthly date column
  rename(date = Date) %>% #rename daily date column to prepare for binding with other data types
  select(data_type, date, sst) #select only useful columns

Browse_07_GCM <- read_csv(here::here("data_raw/GCM", "GCM_BRS07_with_mmm_and_dhw.csv")) %>% 
  select(Date, sst) %>% 
  rename(date = Date) %>% 
  mutate(data_type = "GCM", .before = date)

Browse_07_comb <- bind_rows(Browse_07_CCI, Browse_07_Logger, Browse_07_NOAA, 
                            Browse_07_GCM, Browse_07_CCore_CCI, Browse_07_CCore_NOAA)

```

```{r Cocos_Keeling_DARL}

Cocos_DARL_CCI <- read_csv(here::here("data_raw", "CCI_DARL.csv"))
Cocos_DARL_CCI <- Cocos_DARL_CCI %>% 
  mutate(sst = as.numeric(str_sub(Cocos_DARL_CCI$`mean temperature deg C`, 3, 13))) %>%  #remove punctuation [[ and ]] from temperature data
  select(-`mean temperature deg C`) %>%  #remove column with [[ and ]]
  mutate(data_type = "CCI") %>%  #prepare data for binding with other data types
  rename(date = daily_date) %>%  #prepare data for binding with other data types
  select(data_type, date, sst) #select only useful columns

Cocos_DARL_CCore <- read_csv(here::here("data_raw", "CCore_DAR_Long_Year_Month.csv"))
Cocos_DARL_CCore <- Cocos_DARL_CCore %>% 
  mutate(data_type = "Coral Core") %>% #prepare data for binding with other data types
  mutate(date = str_c(year, month, sep = "-")) %>% #stringing year and month
  mutate(date = ym(date)) %>% #converting date column fr chr to date format
  select(data_type, date, `Sr/Ca`)  #select only useful columns

Cocos_DARL_CCore_CCI <- read_csv(here::here("data_raw", "CCore_SST_DARL_CCI.csv")) %>% 
  mutate(data_type = "Coral Core CCI calibrated SST", .before = "date") %>% 
  select(data_type, date, sst)

Cocos_DARL_CCore_NOAA <- read_csv(here::here("data_raw", "CCore_SST_DARL_NOAA.csv")) %>% 
  mutate(data_type = "Coral Core NOAA calibrated SST", .before = "date") %>% 
  select(data_type, date, sst)

Cocos_DARL_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_100THSITE.csv"))
Cocos_DARL_Logger <- Cocos_DARL_Logger %>% 
  rename(sst = mean_SST) %>% #prepare data for binding with other data types
  mutate(data_type = "Logger") %>% #prepare data for binding with other data types
  select(subsite, data_type, date, sst)  #select only useful columns

Cocos_DARL_NOAA <- read_csv(here::here("data_raw", "NOAA_DAR_Long_SST.csv"))
Cocos_DARL_NOAA <- Cocos_DARL_NOAA %>% 
  mutate(data_type = "NOAA") %>%  #prepare data for binding with other data types
  select(-date) %>% #remove monthly date column
  rename(date = Date) %>% #rename daily date column to prepare for binding with other data types
  select(data_type, date, sst) #select only useful columns

Cocos_DARL_GCM <- read_csv(here::here("data_raw/GCM", "GCM_DAR_Long_with_mmm_and_dhw.csv")) %>% 
  select(Date, sst) %>% 
  rename(date = Date) %>% 
  mutate(data_type = "GCM", .before = date)

Cocos_DARL_comb <- bind_rows(Cocos_DARL_CCI, Cocos_DARL_Logger, Cocos_DARL_NOAA, 
                             Cocos_DARL_GCM, Cocos_DARL_CCore_CCI, Cocos_DARL_CCore_NOAA)

```

```{r Ningaloo_Reef_Tantabiddi_13TNT}

Ningaloo_13TNT_CCI <- read_csv(here::here("data_raw", "CCI_Tantabiddi.csv"))
Ningaloo_13TNT_CCI <- Ningaloo_13TNT_CCI %>% 
  mutate(sst = as.numeric(str_sub(Ningaloo_13TNT_CCI$`mean temperature deg C`, 3, 13))) %>%  #remove punctuation [[ and ]] from temperature data
  select(-`mean temperature deg C`) %>%  #remove column with [[ and ]]
  mutate(data_type = "CCI") %>%  #prepare data for binding with other data types
  rename(date = daily_date) %>%  #prepare data for binding with other data types
  select(data_type, date, sst) #select only useful columns

Ningaloo_13TNT_CCore <- read_csv(here::here("data_raw", "CCore_Ningaloo_13TNT_Year_Month.csv"))
Ningaloo_13TNT_CCore <- Ningaloo_13TNT_CCore %>% 
  mutate(data_type = "Coral Core") %>% #prepare data for binding with other data types
  mutate(date = str_c(year, month, sep = "-")) %>% #stringing year and month
  mutate(date = ym(date)) %>% #converting date column fr chr to date format
  select(data_type, date, `Sr/Ca`)  #select only useful columns

Ningaloo_13TNT_CCore_CCI <- read_csv(here::here("data_raw", "CCore_SST_Ningaloo_13TNT_CCI.csv")) %>% 
  mutate(data_type = "Coral Core CCI calibrated SST", .before = "date") %>% 
  select(data_type, date, sst)

Ningaloo_13TNT_CCore_NOAA <- read_csv(here::here("data_raw", "CCore_SST_Ningaloo_13TNT_NOAA.csv")) %>% 
  mutate(data_type = "Coral Core NOAA calibrated SST", .before = "date") %>% 
  select(data_type, date, sst)

Ningaloo_13TNT_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_TANDFL1.csv"))
Ningaloo_13TNT_Logger <- Ningaloo_13TNT_Logger %>% 
  rename(sst = mean_SST) %>% #prepare data for binding with other data types
  mutate(data_type = "Logger") %>% #prepare data for binding with other data types
  select(subsite, data_type, date, sst)  #select only useful columns

Ningaloo_13TNT_NOAA <- read_csv(here::here("data_raw", "NOAA_Tantabiddi_13TNT_SST.csv"))
Ningaloo_13TNT_NOAA <- Ningaloo_13TNT_NOAA %>% 
  mutate(data_type = "NOAA") %>%  #prepare data for binding with other data types
  select(-date) %>% #remove monthly date column
  rename(date = Date) %>% #rename daily date column to prepare for binding with other data types
  select(data_type, date, sst) #select only useful columns

Ningaloo_13TNT_GCM <- read_csv(here::here("data_raw/GCM", "GCM_Tantabiddi_with_mmm_and_dhw.csv")) %>% 
  select(Date, sst) %>% 
  rename(date = Date) %>% 
  mutate(data_type = "GCM", .before = date)

Ningaloo_13TNT_comb <- bind_rows(Ningaloo_13TNT_CCI, Ningaloo_13TNT_Logger, Ningaloo_13TNT_NOAA,
                                 Ningaloo_13TNT_GCM, Ningaloo_13TNT_CCore_CCI, Ningaloo_13TNT_CCore_NOAA)

```

```{r Ningaloo_Reef_Tantabiddi_08TNT}

Ningaloo_08TNT_CCI <- read_csv(here::here("data_raw", "CCI_Tantabiddi.csv"))
Ningaloo_08TNT_CCI <- Ningaloo_08TNT_CCI %>% 
  mutate(sst = as.numeric(str_sub(Ningaloo_08TNT_CCI$`mean temperature deg C`, 3, 13))) %>%  #remove punctuation [[ and ]] from temperature data
  select(-`mean temperature deg C`) %>%  #remove column with [[ and ]]
  mutate(data_type = "CCI") %>%  #prepare data for binding with other data types
  rename(date = daily_date) %>%  #prepare data for binding with other data types
  select(data_type, date, sst) #select only useful columns

Ningaloo_08TNT_CCore <- read_csv(here::here("data_raw", "CCore_Ningaloo_08TNT_Year_Month.csv"))
Ningaloo_08TNT_CCore <- Ningaloo_08TNT_CCore %>% 
  mutate(data_type = "Coral Core") %>% #prepare data for binding with other data types
  mutate(date = str_c(year, month, sep = "-")) %>% #stringing year and month
  mutate(date = ym(date)) %>% #converting date column fr chr to date format
  select(data_type, date, `Sr/Ca`)  #select only useful columns

Ningaloo_08TNT_CCore_CCI <- read_csv(here::here("data_raw", "CCore_SST_Ningaloo_08TNT_CCI.csv")) %>% 
  mutate(data_type = "Coral Core CCI calibrated SST", .before = "date") %>% 
  select(data_type, date, sst)

Ningaloo_08TNT_CCore_NOAA <- read_csv(here::here("data_raw", "CCore_SST_Ningaloo_08TNT_NOAA.csv")) %>% 
  mutate(data_type = "Coral Core NOAA calibrated SST", .before = "date") %>% 
  select(data_type, date, sst)

Ningaloo_08TNT_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_TANDFL1.csv"))
Ningaloo_08TNT_Logger <- Ningaloo_08TNT_Logger %>% 
  rename(sst = mean_SST) %>% #prepare data for binding with other data types
  mutate(data_type = "Logger") %>% #prepare data for binding with other data types
  select(subsite, data_type, date, sst)  #select only useful columns

Ningaloo_08TNT_NOAA <- read_csv(here::here("data_raw", "NOAA_Tantabiddi_08TNT_SST.csv"))
Ningaloo_08TNT_NOAA <- Ningaloo_08TNT_NOAA %>% 
  mutate(data_type = "NOAA") %>%  #prepare data for binding with other data types
  select(-date) %>% #remove monthly date column
  rename(date = Date) %>% #rename daily date column to prepare for binding with other data types
  select(data_type, date, sst) #select only useful columns

Ningaloo_08TNT_GCM <- read_csv(here::here("data_raw/GCM", "GCM_Tantabiddi_with_mmm_and_dhw.csv")) %>% 
  select(Date, sst) %>% 
  rename(date = Date) %>% 
  mutate(data_type = "GCM", .before = date)

Ningaloo_08TNT_comb <- bind_rows(Ningaloo_08TNT_CCI, Ningaloo_08TNT_Logger, Ningaloo_08TNT_NOAA,
                                 Ningaloo_08TNT_GCM, Ningaloo_08TNT_CCore_CCI, Ningaloo_08TNT_CCore_NOAA)

```

```{r Ningaloo_Reef_Bundegi_13BND}

Ningaloo_13BND_CCI <- read_csv(here::here("data_raw", "CCI_Bundegi.csv"))
Ningaloo_13BND_CCI <- Ningaloo_13BND_CCI %>% 
  mutate(sst = as.numeric(str_sub(Ningaloo_13BND_CCI$`mean temperature deg C`, 3, 13))) %>%  #remove punctuation [[ and ]] from temperature data
  select(-`mean temperature deg C`) %>%  #remove column with [[ and ]]
  mutate(data_type = "CCI") %>%  #prepare data for binding with other data types
  rename(date = daily_date) %>%  #prepare data for binding with other data types
  select(data_type, date, sst) #select only useful columns

Ningaloo_13BND_CCore <- read_csv(here::here("data_raw", "CCore_Ningaloo_13BND_Year_Month.csv"))
Ningaloo_13BND_CCore <- Ningaloo_13BND_CCore %>% 
  mutate(data_type = "Coral Core") %>% #prepare data for binding with other data types
  mutate(date = str_c(year, month, sep = "-")) %>% #stringing year and month
  mutate(date = ym(date)) %>% #converting date column fr chr to date format
  select(data_type, date, `Sr/Ca`)  #select only useful columns

Ningaloo_13BND_CCore_CCI <- read_csv(here::here("data_raw", "CCore_SST_Ningaloo_13BND_CCI.csv")) %>% 
  mutate(data_type = "Coral Core CCI calibrated SST", .before = "date") %>% 
  select(data_type, date, sst)

Ningaloo_13BND_CCore_NOAA <- read_csv(here::here("data_raw", "CCore_SST_Ningaloo_13BND_NOAA.csv")) %>% 
  mutate(data_type = "Coral Core NOAA calibrated SST", .before = "date") %>% 
  select(data_type, date, sst)

Ningaloo_13BND_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_BUNDFL1.csv"))
Ningaloo_13BND_Logger <- Ningaloo_13BND_Logger %>% 
  rename(sst = mean_SST) %>% #prepare data for binding with other data types
  mutate(data_type = "Logger") %>% #prepare data for binding with other data types
  select(subsite, data_type, date, sst)  #select only useful columns

Ningaloo_13BND_NOAA <- read_csv(here::here("data_raw", "NOAA_Bundegi_13BND_SST.csv"))
Ningaloo_13BND_NOAA <- Ningaloo_13BND_NOAA %>% 
  mutate(data_type = "NOAA") %>%  #prepare data for binding with other data types
  select(-date) %>% #remove monthly date column
  rename(date = Date) %>% #rename daily date column to prepare for binding with other data types
  select(data_type, date, sst) #select only useful columns

Ningaloo_13BND_GCM <- read_csv(here::here("data_raw/GCM", "GCM_Bundegi_with_mmm_and_dhw.csv")) %>% 
  select(Date, sst) %>% 
  rename(date = Date) %>% 
  mutate(data_type = "GCM", .before = date)

Ningaloo_13BND_comb <- bind_rows(Ningaloo_13BND_CCI, Ningaloo_13BND_Logger, Ningaloo_13BND_NOAA,
                                 Ningaloo_13BND_GCM, Ningaloo_13BND_CCore_CCI, Ningaloo_13BND_CCore_NOAA)

```

```{r Ningaloo_Reef_Bundegi_08BND}

Ningaloo_08BND_CCI <- read_csv(here::here("data_raw", "CCI_Bundegi.csv"))
Ningaloo_08BND_CCI <- Ningaloo_08BND_CCI %>% 
  mutate(sst = as.numeric(str_sub(Ningaloo_08BND_CCI$`mean temperature deg C`, 3, 13))) %>%  #remove punctuation [[ and ]] from temperature data
  select(-`mean temperature deg C`) %>%  #remove column with [[ and ]]
  mutate(data_type = "CCI") %>%  #prepare data for binding with other data types
  rename(date = daily_date) %>%  #prepare data for binding with other data types
  select(data_type, date, sst) #select only useful columns

Ningaloo_08BND_CCore <- read_csv(here::here("data_raw", "CCore_Ningaloo_08BND_Year_Month.csv"))
Ningaloo_08BND_CCore <- Ningaloo_08BND_CCore %>% 
  mutate(data_type = "Coral Core") %>% #prepare data for binding with other data types
  mutate(date = str_c(year, month, sep = "-")) %>% #stringing year and month
  mutate(date = ym(date)) %>% #converting date column fr chr to date format
  select(data_type, date, `Sr/Ca`)  #select only useful columns

Ningaloo_08BND_CCore_CCI <- read_csv(here::here("data_raw", "CCore_SST_Ningaloo_08BND_CCI.csv")) %>% 
  mutate(data_type = "Coral Core CCI calibrated SST", .before = "date") %>% 
  select(data_type, date, sst)

Ningaloo_08BND_CCore_NOAA <- read_csv(here::here("data_raw", "CCore_SST_Ningaloo_08BND_NOAA.csv")) %>% 
  mutate(data_type = "Coral Core NOAA calibrated SST", .before = "date") %>% 
  select(data_type, date, sst)

Ningaloo_08BND_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_BUNDFL1.csv"))
Ningaloo_08BND_Logger <- Ningaloo_08BND_Logger %>% 
  rename(sst = mean_SST) %>% #prepare data for binding with other data types
  mutate(data_type = "Logger") %>% #prepare data for binding with other data types
  select(subsite, data_type, date, sst)  #select only useful columns

Ningaloo_08BND_NOAA <- read_csv(here::here("data_raw", "NOAA_Bundegi_08BND_SST.csv"))
Ningaloo_08BND_NOAA <- Ningaloo_08BND_NOAA %>% 
  mutate(data_type = "NOAA") %>%  #prepare data for binding with other data types
  select(-date) %>% #remove monthly date column
  rename(date = Date) %>% #rename daily date column to prepare for binding with other data types
  select(data_type, date, sst) #select only useful columns

Ningaloo_08BND_GCM <- read_csv(here::here("data_raw/GCM", "GCM_Bundegi_with_mmm_and_dhw.csv")) %>% 
  select(Date, sst) %>% 
  rename(date = Date) %>% 
  mutate(data_type = "GCM", .before = date)

Ningaloo_08BND_comb <- bind_rows(Ningaloo_08BND_CCI, Ningaloo_08BND_Logger, Ningaloo_08BND_NOAA,
                                 Ningaloo_08BND_GCM, Ningaloo_08BND_CCore_CCI, Ningaloo_08BND_CCore_NOAA)

```

```{r Houtman_Abrolhos_HAB10A}

HAbrol_HAB10A_SrCa_CCI <- read_csv(here::here("data_raw", "CCI_HAB10A.csv"))
HAbrol_HAB10A_SrCa_CCI <- HAbrol_HAB10A_SrCa_CCI %>% 
  mutate(sst = as.numeric(str_sub(HAbrol_HAB10A_SrCa_CCI$`mean temperature deg C`, 3, 13))) %>%  #remove punctuation [[ and ]] from temperature data
  select(-`mean temperature deg C`) %>%  #remove column with [[ and ]]
  mutate(data_type = "CCI") %>%  #prepare data for binding with other data types
  rename(date = daily_date) %>%  #prepare data for binding with other data types
  select(data_type, date, sst) #select only useful columns

HAbrol_HAB10A_SrCa_CCore <- read_csv(here::here("data_raw", "CCore_H_Abrol_HAB_year.csv"))
HAbrol_HAB10A_SrCa_CCore <- HAbrol_HAB10A_SrCa_CCore %>% 
  mutate(data_type = "Coral Core") %>% #prepare data for binding with other data types
  mutate(month = "01") %>% #add month column
  mutate(date = str_c(year, month, sep = "-")) %>% #join year-month columns
  mutate(date = ym(date)) %>%  #convert chr to date format
  select(data_type, date, `HAB10A Sr/Ca`)  #select only useful columns

HAbrol_HAB10A_SrCa_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_NTHFISHFL1.csv"))
HAbrol_HAB10A_SrCa_Logger <- HAbrol_HAB10A_SrCa_Logger %>% 
  rename(sst = mean_SST) %>% #prepare data for binding with other data types
  mutate(data_type = "Logger") %>% #prepare data for binding with other data types
  select(subsite, data_type, date, sst)  #select only useful columns

HAbrol_HAB10A_SrCa_NOAA <- read_csv(here::here("data_raw", "NOAA_HAB10A_SrCa_Proxy_SST.csv"))
HAbrol_HAB10A_SrCa_NOAA <- HAbrol_HAB10A_SrCa_NOAA %>% 
  mutate(data_type = "NOAA") %>%  #prepare data for binding with other data types
  select(-date) %>% #remove monthly date column
  rename(date = Date) %>% #rename daily date column to prepare for binding with other data types
  select(data_type, date, sst) #select only useful columns

HAbrol_HAB10A_GCM <- read_csv(here::here("data_raw/GCM", "GCM_HAB10A_with_mmm_and_dhw.csv")) %>% 
  select(Date, sst) %>% 
  rename(date = Date) %>% 
  mutate(data_type = "GCM", .before = date)

HAbrol_HAB10A_SrCa_comb <- bind_rows(HAbrol_HAB10A_SrCa_CCI, HAbrol_HAB10A_SrCa_Logger, HAbrol_HAB10A_SrCa_NOAA, HAbrol_HAB10A_GCM)

```

```{r Houtman_Abrolhos_HAB05B}

HAbrol_HAB05B_SrCa_CCI <- read_csv(here::here("data_raw", "CCI_HAB05B.csv"))
HAbrol_HAB05B_SrCa_CCI <- HAbrol_HAB05B_SrCa_CCI %>% 
  mutate(sst = as.numeric(str_sub(HAbrol_HAB05B_SrCa_CCI$`mean temperature deg C`, 3, 13))) %>%  #remove punctuation [[ and ]] from temperature data
  select(-`mean temperature deg C`) %>%  #remove column with [[ and ]]
  mutate(data_type = "CCI") %>%  #prepare data for binding with other data types
  rename(date = daily_date) %>%  #prepare data for binding with other data types
  select(data_type, date, sst) #select only useful columns

HAbrol_HAB05B_SrCa_CCore <- read_csv(here::here("data_raw", "CCore_H_Abrol_HAB_year.csv"))
HAbrol_HAB05B_SrCa_CCore <- HAbrol_HAB05B_SrCa_CCore %>% 
  mutate(data_type = "Coral Core") %>% #prepare data for binding with other data types
  mutate(month = "01") %>% #add month column
  mutate(date = str_c(year, month, sep = "-")) %>% #join year-month columns
  mutate(date = ym(date)) %>%  #convert chr to date format
  select(data_type, date, `HAB05B Sr/Ca`)  #select only useful columns

HAbrol_HAB05B_CCore_CCI <- read_csv(here::here("data_raw", "CCore_SST_HAB05B_SrCa_CCI.csv")) %>% 
  mutate(data_type = "Coral Core CCI calibrated SST", .before = "date") %>% 
  select(data_type, date, sst)

HAbrol_HAB05B_SrCa_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_NTHFISHFL1.csv"))
HAbrol_HAB05B_SrCa_Logger <- HAbrol_HAB05B_SrCa_Logger %>% 
  rename(sst = mean_SST) %>% #prepare data for binding with other data types
  mutate(data_type = "Logger") %>% #prepare data for binding with other data types
  select(subsite, data_type, date, sst)  #select only useful columns

HAbrol_HAB05B_SrCa_NOAA <- read_csv(here::here("data_raw", "NOAA_HAB05B_SrCa_Proxy_SST.csv"))
HAbrol_HAB05B_SrCa_NOAA <- HAbrol_HAB05B_SrCa_NOAA %>% 
  mutate(data_type = "NOAA") %>%  #prepare data for binding with other data types
  select(-date) %>% #remove monthly date column
  rename(date = Date) %>% #rename daily date column to prepare for binding with other data types
  select(data_type, date, sst) #select only useful columns

HAbrol_HAB05B_GCM <- read_csv(here::here("data_raw/GCM", "GCM_HAB05B_with_mmm_and_dhw.csv")) %>% 
  select(Date, sst) %>% 
  rename(date = Date) %>% 
  mutate(data_type = "GCM", .before = date)

HAbrol_HAB05B_SrCa_comb <- bind_rows(HAbrol_HAB05B_SrCa_CCI, HAbrol_HAB05B_SrCa_Logger, HAbrol_HAB05B_SrCa_NOAA, HAbrol_HAB05B_GCM, HAbrol_HAB05B_CCore_CCI)

```

```{r Scott_Reef_Loggers}

SCOTT_RPO_1_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_SCOTT_RPO_1.csv"))
SCOTT_RPO_1_Logger <- SCOTT_RPO_1_Logger %>% 
  rename(sst = mean_SST) %>% 
  mutate(data_type = "Logger") %>% 
  select(subsite, data_type, date, sst)  

SCOTT_SL4_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_SCOTT_SL4.csv"))
SCOTT_SL4_Logger <- SCOTT_SL4_Logger %>% 
  rename(sst = mean_SST) %>% 
  mutate(data_type = "Logger") %>%
  select(subsite, data_type, date, sst)  

SCOTT_SS3_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_SCOTT_SS3.csv"))
SCOTT_SS3_Logger <- SCOTT_SS3_Logger %>% 
  rename(sst = mean_SST) %>% 
  mutate(data_type = "Logger") %>%
  select(subsite, data_type, date, sst)  

SCOTTNR1_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_SCOTTNR1.csv"))
SCOTTNR1_Logger <- SCOTTNR1_Logger %>% 
  rename(sst = mean_SST) %>% 
  mutate(data_type = "Logger") %>%
  select(subsite, data_type, date, sst) 

SCOTTSL1_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_SCOTTSL1.csv"))
SCOTTSL1_Logger <- SCOTTSL1_Logger %>% 
  rename(sst = mean_SST) %>% 
  mutate(data_type = "Logger") %>%
  select(subsite, data_type, date, sst) 

SCOTTSL2_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_SCOTTSL2.csv"))
SCOTTSL2_Logger <- SCOTTSL2_Logger %>% 
  rename(sst = mean_SST) %>% 
  mutate(data_type = "Logger") %>%
  select(subsite, data_type, date, sst) 

SCOTTSL3_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_SCOTTSL3.csv"))
SCOTTSL3_Logger <- SCOTTSL3_Logger %>% 
  rename(sst = mean_SST) %>% 
  mutate(data_type = "Logger") %>%
  select(subsite, data_type, date, sst) 

SCOTTSS1_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_SCOTTSS1.csv"))
SCOTTSS1_Logger <- SCOTTSS1_Logger %>% 
  rename(sst = mean_SST) %>% 
  mutate(data_type = "Logger") %>%
  select(subsite, data_type, date, sst) 

SCOTTSS2_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_SCOTTSS2.csv"))
SCOTTSS2_Logger <- SCOTTSS2_Logger %>% 
  rename(sst = mean_SST) %>% 
  mutate(data_type = "Logger") %>%
  select(subsite, data_type, date, sst) 

```

```{r Other_Loggers}

`100THSITE_Logger` <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_100THSITE.csv"))
`100THSITE_Logger` <- `100THSITE_Logger` %>% 
  rename(sst = mean_SST) %>% 
  mutate(data_type = "Logger") %>%
  select(subsite, data_type, date, sst) 

BUNDEGI_BR_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_BUNDEGI_BR.csv"))
BUNDEGI_BR_Logger <- BUNDEGI_BR_Logger %>% 
  rename(sst = mean_SST) %>% 
  mutate(data_type = "Logger") %>%
  select(subsite, data_type, date, sst) 

BUNDFL1_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_BUNDFL1.csv"))
BUNDFL1_Logger <- BUNDFL1_Logger %>% 
  rename(sst = mean_SST) %>% 
  mutate(data_type = "Logger") %>%
  select(subsite, data_type, date, sst) 

NTHFISHFL1_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_NTHFISHFL1.csv"))
NTHFISHFL1_Logger <- NTHFISHFL1_Logger %>% 
  rename(sst = mean_SST) %>% 
  mutate(data_type = "Logger") %>%
  select(subsite, data_type, date, sst) 

TANDFL1_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_TANDFL1.csv"))
TANDFL1_Logger <- TANDFL1_Logger %>% 
  rename(sst = mean_SST) %>% 
  mutate(data_type = "Logger") %>%
  select(subsite, data_type, date, sst) 

TANTABIDDI_SL1_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_TANTABIDDI_SL1.csv"))
TANTABIDDI_SL1_Logger <- TANTABIDDI_SL1_Logger %>% 
  rename(sst = mean_SST) %>% 
  mutate(data_type = "Logger") %>%
  select(subsite, data_type, date, sst) 

```

```{r Combine_Loggers}

Logger_COMBINED <- rbind(SCOTT_RPO_1_Logger, SCOTT_SL4_Logger, SCOTT_SS3_Logger, 
                         SCOTTNR1_Logger, SCOTTSL1_Logger, SCOTTSL2_Logger, SCOTTSL3_Logger, 
                         SCOTTSS1_Logger, SCOTTSS2_Logger, SCOTT_SS3_Logger, `100THSITE_Logger`, 
                         BUNDEGI_BR_Logger, BUNDFL1_Logger, NTHFISHFL1_Logger, TANDFL1_Logger, TANTABIDDI_SL1_Logger)

cols = c("SCOTT_RPO_1" = "black", "SCOTT_SL4" = "black", "SCOTT_SS3" = "black", 
         "SCOTTNR1" = "black", "SCOTTSL1" = "black", "SCOTTSL2" = "black", 
         "SCOTTSL3" = "black", "SCOTTSS1" = "black", "SCOTTSS2" = "black", "SCOTT_SS3" = "black", 
         "100THSITE" = "dark blue", "BUNDEGI_BR" = "sky blue", "BUNDFL1" = "brown",
         "NTHFISHFL1" = "dark green", "TANDFL1" = "light green", "TANTABIDDI_SL1" = "red")

ggplot(Logger_COMBINED) +
  geom_line(aes(x = date, y = sst, color = subsite), position = "jitter") +
  scale_color_manual(values = cols) +
  facet_wrap(~subsite)

ggsave("graphics/TS/logger.jpeg", dpi = 300)

```

```{r SCOTT_Reef_SCOTT_RPO_1}

SCOTT_RPO_1_GCM <- read_csv(here::here("data_raw/GCM", "GCM_SCOTT_RPO_1_with_mmm_and_dhw.csv")) %>% 
  select(Date, sst) %>% 
  rename(date = Date) %>% 
  mutate(data_type = "GCM", .before = date)

SCOTT_RPO_1_CCI <- read_csv(here::here("data_raw", "CCI_SCOTT_RPO_1_with_mmm_and_dhw.csv")) %>% 
  select(Date, sst) %>% 
  rename(date = Date) %>% 
  mutate(data_type = "CCI", .before = date)

SCOTT_RPO_1_NOAA <- read_csv(here::here("data_raw", "NOAA_SCOTT_RPO_1_with_mmm_and_dhw.csv")) %>% 
  select(Date, sst) %>% 
  rename(date = Date) %>% 
  mutate(data_type = "NOAA", .before = date)

SCOTT_RPO_1_Logger <- SCOTT_RPO_1_Logger %>% 
  select(data_type, date, sst)

SCOTT_RPO_1_comb <- rbind(SCOTT_RPO_1_CCI, SCOTT_RPO_1_Logger, SCOTT_RPO_1_NOAA, SCOTT_RPO_1_GCM)

```

```{r SCOTT_Reef_SCOTTSL1}

SCOTTSL1_GCM <- read_csv(here::here("data_raw/GCM", "GCM_SCOTTSL1_with_mmm_and_dhw.csv")) %>% 
  select(Date, sst) %>% 
  rename(date = Date) %>% 
  mutate(data_type = "GCM", .before = date)

SCOTTSL1_CCI <- read_csv(here::here("data_raw", "CCI_SCOTTSL1_with_mmm_and_dhw.csv")) %>% 
  select(Date, sst) %>% 
  rename(date = Date) %>% 
  mutate(data_type = "CCI", .before = date)

SCOTTSL1_NOAA <- read_csv(here::here("data_raw", "NOAA_SCOTTSL1_with_mmm_and_dhw.csv")) %>% 
  select(Date, sst) %>% 
  rename(date = Date) %>% 
  mutate(data_type = "NOAA", .before = date)

SCOTTSL1_Logger <- SCOTTSL1_Logger %>% 
  select(data_type, date, sst)

SCOTTSL1_comb <- rbind(SCOTTSL1_CCI, SCOTTSL1_Logger, SCOTTSL1_NOAA, SCOTTSL1_GCM)

```

```{r Combined_TS, fig.height=8, fig.width=10}

#Combined time series satellites (CCI and NOAA), loggers, coral cores, GCM

setcols <- c("CCI" = "coral", "NOAA" = "purple", "Logger" = "blue", "GCM" = "black", "Coral Core NOAA calibrated SST" = "green", "Coral Core CCI calibrated SST" = "brown")

#BRS07 Plotly
TS_BRS07 <- Browse_07_comb %>% 
  rename(type = data_type) %>% 
  ggplot(aes(x = date, y = sst)) +
  geom_line(aes(color = type)) +
  scale_color_manual(values = setcols) +
  #xlim(as.Date(c("1980-01-01", "2021-01-01"))) +
  scale_x_date(limits = (as.Date(c("1978-01-01", "2021-01-01"))), date_breaks = "5 years", date_labels = "%Y") +
  theme(legend.title = element_blank(), panel.background = element_blank(), axis.line = element_line("black"), axis.title = element_text(size = 12)) +
  labs(title = "Browse Island BRS07 (-14.12, 123.55)", y = ("Temperature°C"), x = "Time")

ggplotly(TS_BRS07) %>% 
 layout(legend = list(orientation = "h", y = -0.2, x = 0.2))

ggsave("graphics/TS/BRS07.jpeg", dpi = 300)

#BRS07 streamgraph
ggstream_Browse_07_comb <- Browse_07_comb %>% 
  select(-subsite) %>% 
  pivot_wider(names_from = data_type, values_from = sst) %>% 
  mutate(across(where(anyNA), ~replace_na(., 0))) %>% 
  pivot_longer(cols = c(2:7), names_to = "data_type", values_to = "sst") %>% 
  filter(date < as.Date("2021-01-01")) %>% 
  ggplot(aes(x = date, y = sst, fill = data_type)) +
  geom_stream(n_grid = 100000) +
  scale_fill_manual(values = setcols) +
  #xlim(as.Date(c("1980-01-01", "2021-01-01"))) +
  scale_x_date(limits = (as.Date(c("1978-01-01", "2021-01-01"))), date_breaks = "5 years", date_labels = "%Y") +
  theme(legend.title = element_blank(), panel.background = element_blank(), axis.line = element_line("black"), axis.title = element_text(size = 12)) +
  labs(title = "Browse Island BRS07 (-14.12, 123.55)", y = "", x = "Time")

#ggstream_Browse_07_comb

#DARL Plotly
TS_DARL <- Cocos_DARL_comb %>% 
  rename(type = data_type) %>% 
  ggplot(aes(x = date, y = sst)) +
  geom_line(aes(color = type)) +
  scale_color_manual(values = setcols) +
  #xlim(as.Date(c("1980-01-01", "2021-01-01"))) +
  scale_x_date(limits = (as.Date(c("1978-01-01", "2021-01-01"))), date_breaks = "5 years", date_labels = "%Y") +
  theme(legend.title = element_blank(), panel.background = element_blank(), axis.line = element_line("black"), axis.title = element_text(size = 12)) +
  labs(title = "Cocos Keeling Island DARL (-12.09, 96.88)", y = ("Temperature°C"), x = "Time")

ggplotly(TS_DARL) %>% 
 layout(legend = list(orientation = "h", y = -0.2, x = 0.2))

ggsave("graphics/TS/DARL.jpeg", dpi = 300)

#DARL streamgraph

ggstream_Cocos_DARL_comb <- Cocos_DARL_comb %>% 
  select(-subsite) %>% 
  pivot_wider(names_from = data_type, values_from = sst) %>% 
  mutate(across(where(anyNA), ~replace_na(., 0))) %>% 
  pivot_longer(cols = c(2:7), names_to = "data_type", values_to = "sst") %>% 
  filter(date < as.Date("2021-01-01")) %>% 
  ggplot(aes(x = date, y = sst, fill = data_type)) +
  geom_stream(n_grid = 100000) +
  scale_fill_manual(values = setcols) +
  #xlim(as.Date(c("1980-01-01", "2021-01-01"))) +
  scale_x_date(limits = (as.Date(c("1978-01-01", "2021-01-01"))), date_breaks = "5 years", date_labels = "%Y") +
  theme(legend.title = element_blank(), panel.background = element_blank(), axis.line = element_line("black"), axis.title = element_text(size = 12)) +
  labs(title = "Cocos Keeling Island DARL (-12.09, 96.88)", y = "", x = "Time")

#ggstream_Cocos_DARL_comb

#SCOTT_RPO_1 Plotly
TS_SCOTT_RPO_1 <- SCOTT_RPO_1_comb %>% 
  rename(type = data_type) %>% 
  ggplot(aes(x = date, y = sst)) +
  geom_line(aes(color = type)) +
  scale_color_manual(values = setcols) +
  #xlim(as.Date(c("1980-01-01", "2021-01-01"))) +
  scale_x_date(limits = (as.Date(c("1978-01-01", "2021-01-01"))), date_breaks = "5 years", date_labels = "%Y") +
  theme(legend.title = element_blank(), panel.background = element_blank(), axis.line = element_line("black"), axis.title = element_text(size = 12)) +
  labs(title = "Scott Reef SCOTT_RPO_1 (-14.06, 121.78)", y = ("Temperature°C"), x = "Time")

ggplotly(TS_SCOTT_RPO_1) %>% 
 layout(legend = list(orientation = "h", y = -0.2, x = 0.2))

ggsave("graphics/TS/SCOTT_RPO_1.jpeg", dpi = 300)

#SCOTT_RPO_1 streamgraph
ggstream_SCOTT_RPO_1_comb <- SCOTT_RPO_1_comb %>% 
  pivot_wider(names_from = data_type, values_from = sst) %>% 
  mutate(across(where(anyNA), ~replace_na(., 0))) %>% 
  pivot_longer(cols = c(2:5), names_to = "data_type", values_to = "sst") %>% 
  filter(date < as.Date("2021-01-01")) %>% 
  ggplot(aes(x = date, y = sst, fill = data_type)) +
  geom_stream(n_grid = 100000) +
  scale_fill_manual(values = setcols) +
  #xlim(as.Date(c("1980-01-01", "2021-01-01"))) +
  scale_x_date(limits = (as.Date(c("1978-01-01", "2021-01-01"))), date_breaks = "5 years", date_labels = "%Y") +
  theme(legend.title = element_blank(), panel.background = element_blank(), axis.line = element_line("black"), axis.title = element_text(size = 12)) +
  labs(title = "Scott Reef SCOTT_RPO_1 (-14.06, 121.78)", y = "", x = "Time")

#ggstream_SCOTT_RPO_1_comb

#SCOTTSL1 Plotly
TS_SCOTTSL1 <- SCOTTSL1_comb %>% 
  rename(type = data_type) %>% 
  ggplot(aes(x = date, y = sst)) +
  geom_line(aes(color = type)) +
  scale_color_manual(values = setcols) +
  #xlim(as.Date(c("1980-01-01", "2021-01-01"))) +
  scale_x_date(limits = (as.Date(c("1978-01-01", "2021-01-01"))), date_breaks = "5 years", date_labels = "%Y") +
  theme(legend.title = element_blank(), panel.background = element_blank(), axis.line = element_line("black"), axis.title = element_text(size = 12)) +
  labs(title = "Scott Reef SCOTTSL1 (-14.08, 121.95)", y = ("Temperature°C"), x = "Time")

ggplotly(TS_SCOTTSL1) %>% 
 layout(legend = list(orientation = "h", y = -0.2, x = 0.2))

ggsave("graphics/TS/SCOTTSL1.jpeg", dpi = 300)

#SCOTTSL1 streamgraph
ggstream_SCOTTSL1_comb <- SCOTTSL1_comb %>% 
  pivot_wider(names_from = data_type, values_from = sst) %>% 
  mutate(across(where(anyNA), ~replace_na(., 0))) %>% 
  pivot_longer(cols = c(2:5), names_to = "data_type", values_to = "sst") %>% 
  filter(date < as.Date("2021-01-01")) %>% 
  ggplot(aes(x = date, y = sst, fill = data_type)) +
  geom_stream(n_grid = 100000) +
  scale_fill_manual(values = setcols) +
  #xlim(as.Date(c("1980-01-01", "2021-01-01"))) +
  scale_x_date(limits = (as.Date(c("1978-01-01", "2021-01-01"))), date_breaks = "5 years", date_labels = "%Y") +
  theme(legend.title = element_blank(), panel.background = element_blank(), axis.line = element_line("black"), axis.title = element_text(size = 12)) +
  labs(title = "Scott Reef SCOTTSL1 (-14.08, 121.95)", y = "", x = "Time")

#ggstream_SCOTTSL1_comb

#08BND Plotly 
TS_Ningaloo_08BND <- Ningaloo_08BND_comb %>% 
  rename(type = data_type) %>% 
  ggplot(aes(x = date, y = sst)) +
  geom_line(aes(color = type)) +
  scale_color_manual(values = setcols) +
  #xlim(as.Date(c("1980-01-01", "2021-01-01"))) +
  scale_x_date(limits = (as.Date(c("1978-01-01", "2021-01-01"))), date_breaks = "5 years", date_labels = "%Y") +
  theme(legend.title = element_blank(), panel.background = element_blank(), axis.line = element_line("black"), axis.title = element_text(size = 12)) +
  labs(title = "Ningaloo Reef 08BND (-21.87, 114.16)", y = ("Temperature°C"), x = "Time")

ggplotly(TS_Ningaloo_08BND) %>% 
 layout(legend = list(orientation = "h", y = -0.2, x = 0.2))

ggsave("graphics/TS/Ningaloo_08BND.jpeg", dpi = 300)

#08BND streamgraph
ggstream_Ningaloo_08BND_comb <- Ningaloo_08BND_comb %>% 
  select(-subsite) %>% 
  pivot_wider(names_from = data_type, values_from = sst) %>% 
  mutate(across(where(anyNA), ~replace_na(., 0))) %>% 
  pivot_longer(cols = c(2:7), names_to = "data_type", values_to = "sst") %>% 
  filter(date < as.Date("2021-01-01")) %>% 
  ggplot(aes(x = date, y = sst, fill = data_type)) +
  geom_stream(n_grid = 100000) +
  scale_fill_manual(values = setcols) +
  #xlim(as.Date(c("1980-01-01", "2021-01-01"))) +
  scale_x_date(limits = (as.Date(c("1978-01-01", "2021-01-01"))), date_breaks = "5 years", date_labels = "%Y") +
  theme(legend.title = element_blank(), panel.background = element_blank(), axis.line = element_line("black"), axis.title = element_text(size = 12)) +
  labs(title = "Ningaloo Reef 08BND (-21.87, 114.16)", y = "", x = "Time")

#ggstream_Ningaloo_08BND_comb

#13BND Plotly
TS_Ningaloo_13BND <- Ningaloo_13BND_comb %>% 
  rename(type = data_type) %>% 
  ggplot(aes(x = date, y = sst)) +
  geom_line(aes(color = type)) +
  scale_color_manual(values = setcols) +
  #xlim(as.Date(c("1980-01-01", "2021-01-01"))) +
  scale_x_date(limits = (as.Date(c("1978-01-01", "2021-01-01"))), date_breaks = "5 years", date_labels = "%Y") +
  theme(legend.title = element_blank(), panel.background = element_blank(), axis.line = element_line("black"), axis.title = element_text(size = 12)) +
  labs(title = "Ningaloo Reef 13BND (-21.87, 114.16)", y = ("Temperature°C"), x = "Time")

ggplotly(TS_Ningaloo_13BND) %>% 
 layout(legend = list(orientation = "h", y = -0.2, x = 0.2))

ggsave("graphics/TS/Ningaloo_13BND.jpeg", dpi = 300)

#13BND streamgraph
ggstream_Ningaloo_13BND_comb <- Ningaloo_13BND_comb %>% 
  select(-subsite) %>% 
  pivot_wider(names_from = data_type, values_from = sst) %>% 
  mutate(across(where(anyNA), ~replace_na(., 0))) %>% 
  pivot_longer(cols = c(2:7), names_to = "data_type", values_to = "sst") %>% 
  filter(date < as.Date("2021-01-01")) %>% 
  ggplot(aes(x = date, y = sst, fill = data_type)) +
  geom_stream(n_grid = 100000) +
  scale_fill_manual(values = setcols) +
  #xlim(as.Date(c("1980-01-01", "2021-01-01"))) +
  scale_x_date(limits = (as.Date(c("1978-01-01", "2021-01-01"))), date_breaks = "5 years", date_labels = "%Y") +
  theme(legend.title = element_blank(), panel.background = element_blank(), axis.line = element_line("black"), axis.title = element_text(size = 12)) +
  labs(title = "Ningaloo Reef 13BND (-21.87, 114.16)", y = "", x = "Time")

#ggstream_Ningaloo_13BND_comb

#08TNT Plotly
TS_Ningaloo_08TNT <- Ningaloo_08TNT_comb %>% 
  rename(type = data_type) %>% 
  ggplot(aes(x = date, y = sst)) +
  geom_line(aes(color = type)) +
  scale_color_manual(values = setcols) +
  #xlim(as.Date(c("1980-01-01", "2021-01-01"))) +
  scale_x_date(limits = (as.Date(c("1978-01-01", "2021-01-01"))), date_breaks = "5 years", date_labels = "%Y") +
  theme(legend.title = element_blank(), panel.background = element_blank(), axis.line = element_line("black"), axis.title = element_text(size = 12)) +
  labs(title = "Ningaloo Reef 08TNT (-21.91, 113.97)", y = ("Temperature°C"), x = "Time")

ggplotly(TS_Ningaloo_08TNT) %>% 
 layout(legend = list(orientation = "h", y = -0.2, x = 0.2))

ggsave("graphics/TS/Ningaloo_08TNT.jpeg", dpi = 300)

#08TNT streamgraph
ggstream_Ningaloo_08TNT_comb <- Ningaloo_08TNT_comb %>% 
  select(-subsite) %>% 
  pivot_wider(names_from = data_type, values_from = sst) %>% 
  mutate(across(where(anyNA), ~replace_na(., 0))) %>% 
  pivot_longer(cols = c(2:7), names_to = "data_type", values_to = "sst") %>% 
  filter(date < as.Date("2021-01-01")) %>% 
  ggplot(aes(x = date, y = sst, fill = data_type)) +
  geom_stream(n_grid = 100000) +
  scale_fill_manual(values = setcols) +
  #xlim(as.Date(c("1980-01-01", "2021-01-01"))) +
  scale_x_date(limits = (as.Date(c("1978-01-01", "2021-01-01"))), date_breaks = "5 years", date_labels = "%Y") +
  theme(legend.title = element_blank(), panel.background = element_blank(), axis.line = element_line("black"), axis.title = element_text(size = 12)) +
  labs(title = "Ningaloo Reef 08TNT (-21.91, 113.97)", y = "", x = "Time")

#ggstream_Ningaloo_08TNT_comb

#13TNT Plotly
TS_Ningaloo_13TNT <- Ningaloo_13TNT_comb %>% 
  rename(type = data_type) %>% 
  ggplot(aes(x = date, y = sst)) +
  geom_line(aes(color = type)) +
  scale_color_manual(values = setcols) +
  #xlim(as.Date(c("1980-01-01", "2021-01-01"))) +
  scale_x_date(limits = (as.Date(c("1978-01-01", "2021-01-01"))), date_breaks = "5 years", date_labels = "%Y") +
  theme(legend.title = element_blank(), panel.background = element_blank(), axis.line = element_line("black"), axis.title = element_text(size = 12)) +
  labs(title = "Ningaloo Reef 13TNT (-21.91, 113.97)", y = ("Temperature°C"), x = "Time")

ggplotly(TS_Ningaloo_13TNT) %>% 
 layout(legend = list(orientation = "h", y = -0.2, x = 0.2))

ggsave("graphics/TS/Ningaloo_13TNT.jpeg", dpi = 300)

#13TNT streamgraph
ggstream_Ningaloo_13TNT_comb <- Ningaloo_13TNT_comb %>% 
  select(-subsite) %>% 
  pivot_wider(names_from = data_type, values_from = sst) %>% 
  mutate(across(where(anyNA), ~replace_na(., 0))) %>% 
  pivot_longer(cols = c(2:7), names_to = "data_type", values_to = "sst") %>% 
  filter(date < as.Date("2021-01-01")) %>% 
  ggplot(aes(x = date, y = sst, fill = data_type)) +
  geom_stream(n_grid = 100000) +
  scale_fill_manual(values = setcols) +
  #xlim(as.Date(c("1980-01-01", "2021-01-01"))) +
  scale_x_date(limits = (as.Date(c("1978-01-01", "2021-01-01"))), date_breaks = "5 years", date_labels = "%Y") +
  theme(legend.title = element_blank(), panel.background = element_blank(), axis.line = element_line("black"), axis.title = element_text(size = 12)) +
  labs(title = "Ningaloo Reef 13TNT (-21.91, 113.97)", y = "", x = "Time")

#ggstream_Ningaloo_13TNT_comb

#HAB10A Plotly
TS_HAbrol_HAB10A <- HAbrol_HAB10A_SrCa_comb %>% 
  rename(type = data_type) %>% 
  ggplot(aes(x = date, y = sst)) +
  geom_line(aes(color = type)) +
  scale_color_manual(values = setcols) +
  #xlim(as.Date(c("1980-01-01", "2021-01-01"))) +
  scale_x_date(limits = (as.Date(c("1978-01-01", "2021-01-01"))), date_breaks = "5 years", date_labels = "%Y") +
  theme(legend.title = element_blank(), panel.background = element_blank(), axis.line = element_line("black"), axis.title = element_text(size = 12)) +
  labs(title = "Houtman Abrolhos HAB10A (-28.46, 113.75)", y = ("Temperature°C"), x = "Time")

ggplotly(TS_HAbrol_HAB10A) %>% 
 layout(legend = list(orientation = "h", y = -0.2, x = 0.2))

ggsave("graphics/TS/HAbrol_HAB10A.jpeg", dpi = 300)

#HAB10A streamgraph
ggstream_HAbrol_HAB10A_comb <- HAbrol_HAB10A_SrCa_comb %>% 
  select(-subsite) %>% 
  pivot_wider(names_from = data_type, values_from = sst) %>% 
  mutate(across(where(anyNA), ~replace_na(., 0))) %>% 
  pivot_longer(cols = c(2:5), names_to = "data_type", values_to = "sst") %>% 
  filter(date < as.Date("2021-01-01")) %>% 
  ggplot(aes(x = date, y = sst, fill = data_type)) +
  geom_stream(n_grid = 100000) +
  scale_fill_manual(values = setcols) +
  #xlim(as.Date(c("1980-01-01", "2021-01-01"))) +
  scale_x_date(limits = (as.Date(c("1978-01-01", "2021-01-01"))), date_breaks = "5 years", date_labels = "%Y") +
  theme(legend.title = element_blank(), panel.background = element_blank(), axis.line = element_line("black"), axis.title = element_text(size = 12)) +
  labs(title = "Houtman Abrolhos HAB10A (-28.46, 113.75)", y = "", x = "Time")

#ggstream_HAbrol_HAB10A_comb

#HAB05B Plotly
TS_HAbrol_HAB05B <- HAbrol_HAB05B_SrCa_comb %>% 
  rename(type = data_type) %>% 
  ggplot(aes(x = date, y = sst)) +
  geom_line(aes(color = type)) +
  scale_color_manual(values = setcols) +
  #xlim(as.Date(c("1980-01-01", "2021-01-01"))) +
  scale_x_date(limits = (as.Date(c("1978-01-01", "2021-01-01"))), date_breaks = "5 years", date_labels = "%Y") +
  theme(legend.title = element_blank(), panel.background = element_blank(), axis.line = element_line("black"), axis.title = element_text(size = 12)) +
  labs(title = "Houtman Abrolhos HAB05B (-28.46, 113.77)", y = ("Temperature°C"), x = "Time")

ggplotly(TS_HAbrol_HAB05B) %>% 
 layout(legend = list(orientation = "h", y = -0.2, x = 0.2))

ggsave("graphics/TS/HAbrol_HAB05B.jpeg", dpi = 300)

#HAB05B streamgraph
ggstream_HAbrol_HAB05B_comb <- HAbrol_HAB05B_SrCa_comb %>% 
  select(-subsite) %>% 
  pivot_wider(names_from = data_type, values_from = sst) %>% 
  mutate(across(where(anyNA), ~replace_na(., 0))) %>% 
  pivot_longer(cols = c(2:6), names_to = "data_type", values_to = "sst") %>% 
  filter(date < as.Date("2021-01-01")) %>% 
  ggplot(aes(x = date, y = sst, fill = data_type)) +
  geom_stream(n_grid = 100000) +
  scale_fill_manual(values = setcols) +
  #xlim(as.Date(c("1980-01-01", "2021-01-01"))) +
  scale_x_date(limits = (as.Date(c("1978-01-01", "2021-01-01"))), date_breaks = "5 years", date_labels = "%Y") +
  theme(legend.title = element_blank(), panel.background = element_blank(), axis.line = element_line("black"), axis.title = element_text(size = 12)) +
  labs(title = "Houtman Abrolhos HAB05B (-28.46, 113.77)", y = "", x = "Time")

#ggstream_HAbrol_HAB05B_comb

```

