---
title: "Degree Heating Week Analysis"
author: "Vanessa"
date: "`r lubridate::today()`"
output: pdf_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r Loading Packages, message = FALSE, include = FALSE}
library(tidyverse)
library(lubridate)
library(dplyr)
library(patchwork)
library(colorspace)
library(rmarkdown)
library(kableExtra)
```

```{r Reading CCI_NOAA_GCM Degree Heating Week Raw Data, include = FALSE}
#CCI data
CCI_BRS05 <- read_csv(here::here("data_raw", "CCI_BRS05_with_mmm_and_dhw.csv"))
CCI_BRS07 <- read_csv(here::here("data_raw", "CCI_BRS07_with_mmm_and_dhw.csv"))
CCI_BUN05A <- read_csv(here::here("data_raw", "CCI_BUN05A_with_mmm_and_dhw.csv"))
CCI_Bundegi <- read_csv(here::here("data_raw", "CCI_Bundegi_with_mmm_and_dhw.csv"))
CCI_DAR3 <- read_csv(here::here("data_raw", "CCI_DAR3_with_mmm_and_dhw.csv"))
CCI_DARL <- read_csv(here::here("data_raw", "CCI_DARL_with_mmm_and_dhw.csv"))
CCI_HAB05B <- read_csv(here::here("data_raw", "CCI_HAB05B_with_mmm_and_dhw.csv"))
CCI_HAB10A <- read_csv(here::here("data_raw", "CCI_HAB10A_with_mmm_and_dhw.csv"))
CCI_SCOTT_RPO_1 <- read_csv(here::here("data_raw", "CCI_SCOTT_RPO_1_with_mmm_and_dhw.csv"))
CCI_SCOTT_SL4 <- read_csv(here::here("data_raw", "CCI_SCOTT_SL4_with_mmm_and_dhw.csv"))
CCI_SCOTT_SS3 <- read_csv(here::here("data_raw", "CCI_SCOTT_SS3_with_mmm_and_dhw.csv"))
CCI_SCOTTNR1 <- read_csv(here::here("data_raw", "CCI_SCOTTNR1_with_mmm_and_dhw.csv"))
CCI_SCOTTSL1 <- read_csv(here::here("data_raw", "CCI_SCOTTSL1_with_mmm_and_dhw.csv"))
CCI_SCOTTSL2 <- read_csv(here::here("data_raw", "CCI_SCOTTSL2_with_mmm_and_dhw.csv"))
CCI_SCOTTSL3 <- read_csv(here::here("data_raw", "CCI_SCOTTSL3_with_mmm_and_dhw.csv"))
CCI_SCOTTSS1 <- read_csv(here::here("data_raw", "CCI_SCOTTSS1_with_mmm_and_dhw.csv"))
CCI_SCOTTSS2 <- read_csv(here::here("data_raw", "CCI_SCOTTSS2_with_mmm_and_dhw.csv"))
CCI_Tantabiddi <- read_csv(here::here("data_raw", "CCI_Tantabiddi_with_mmm_and_dhw.csv"))
CCI_TNT <- read_csv(here::here("data_raw", "CCI_TNT_with_mmm_and_dhw.csv"))
CCI_TNT07C <- read_csv(here::here("data_raw", "CCI_TNT07C_with_mmm_and_dhw.csv"))
CCI_Wallabi_Island <- read_csv(here::here("data_raw", "CCI_Wallabi_Island_with_mmm_and_dhw.csv"))

#NOAA data
NOAA_BRS05 <- read_csv(here::here("data_raw", "NOAA_BRS05_with_mmm_and_dhw.csv"))
NOAA_BRS07 <- read_csv(here::here("data_raw", "NOAA_BRS07_with_mmm_and_dhw.csv"))
NOAA_BUN05A <- read_csv(here::here("data_raw", "NOAA_BUN05A_with_mmm_and_dhw.csv"))
NOAA_Bundegi <- read_csv(here::here("data_raw", "NOAA_Bundegi_with_mmm_and_dhw.csv"))
NOAA_DAR3 <- read_csv(here::here("data_raw", "NOAA_DAR3_with_mmm_and_dhw.csv"))
NOAA_DARL <- read_csv(here::here("data_raw", "NOAA_DAR_Long_with_mmm_and_dhw.csv"))
NOAA_HAB05B <- read_csv(here::here("data_raw", "NOAA_HAB05B_with_mmm_and_dhw.csv"))
NOAA_HAB10A <- read_csv(here::here("data_raw", "NOAA_HAB10A_with_mmm_and_dhw.csv"))
NOAA_SCOTT_RPO_1 <- read_csv(here::here("data_raw", "NOAA_SCOTT_RPO_1_with_mmm_and_dhw.csv"))
NOAA_SCOTT_SL4 <- read_csv(here::here("data_raw", "NOAA_SCOTT_SL4_with_mmm_and_dhw.csv"))
NOAA_SCOTT_SS3 <- read_csv(here::here("data_raw", "NOAA_SCOTT_SS3_with_mmm_and_dhw.csv"))
NOAA_SCOTTNR1 <- read_csv(here::here("data_raw", "NOAA_SCOTTNR1_with_mmm_and_dhw.csv"))
NOAA_SCOTTSL1 <- read_csv(here::here("data_raw", "NOAA_SCOTTSL1_with_mmm_and_dhw.csv"))
NOAA_SCOTTSL2 <- read_csv(here::here("data_raw", "NOAA_SCOTTSL2_with_mmm_and_dhw.csv"))
NOAA_SCOTTSL3 <- read_csv(here::here("data_raw", "NOAA_SCOTTSL3_with_mmm_and_dhw.csv"))
NOAA_SCOTTSS1 <- read_csv(here::here("data_raw", "NOAA_SCOTTSS1_with_mmm_and_dhw.csv"))
NOAA_SCOTTSS2 <- read_csv(here::here("data_raw", "NOAA_SCOTTSS2_with_mmm_and_dhw.csv"))
NOAA_Tantabiddi <- read_csv(here::here("data_raw", "NOAA_Tantabiddi_with_mmm_and_dhw.csv"))
NOAA_TNT <- read_csv(here::here("data_raw", "NOAA_TNT_with_mmm_and_dhw.csv"))
NOAA_TNT07C <- read_csv(here::here("data_raw", "NOAA_TNT07C_with_mmm_and_dhw.csv"))
NOAA_Wallabi_Island <- read_csv(here::here("data_raw", "NOAA_Wallabi_Island_with_mmm_and_dhw.csv"))

#GCM data
GCM_BRS05 <- read_csv(here::here("data_raw/GCM", "GCM_BRS05_with_mmm_and_dhw.csv"))
GCM_BRS07 <- read_csv(here::here("data_raw/GCM", "GCM_BRS07_with_mmm_and_dhw.csv"))
GCM_BUN05A <- read_csv(here::here("data_raw/GCM", "GCM_BUN05A_with_mmm_and_dhw.csv"))
GCM_Bundegi <- read_csv(here::here("data_raw/GCM", "GCM_Bundegi_with_mmm_and_dhw.csv"))
GCM_Tantabiddi <- read_csv(here::here("data_raw/GCM", "GCM_Tantabiddi_with_mmm_and_dhw.csv"))
GCM_TNT07C <- read_csv(here::here("data_raw/GCM", "GCM_TNT07C_with_mmm_and_dhw.csv"))
GCM_DARL <- read_csv(here::here("data_raw/GCM", "GCM_DAR_Long_with_mmm_and_dhw.csv"))
GCM_DAR3 <- read_csv(here::here("data_raw/GCM", "GCM_DAR3_with_mmm_and_dhw.csv"))
GCM_HAB05B <- read_csv(here::here("data_raw/GCM", "GCM_HAB05B_with_mmm_and_dhw.csv"))
GCM_HAB10A <- read_csv(here::here("data_raw/GCM", "GCM_HAB10A_with_mmm_and_dhw.csv"))
GCM_SCOTT_RPO_1 <- read_csv(here::here("data_raw/GCM", "GCM_SCOTT_RPO_1_with_mmm_and_dhw.csv"))
GCM_SCOTT_SL4 <- read_csv(here::here("data_raw/GCM", "GCM_SCOTT_SL4_with_mmm_and_dhw.csv"))
GCM_SCOTT_SS3 <- read_csv(here::here("data_raw/GCM", "GCM_SCOTT_SS3_with_mmm_and_dhw.csv"))
GCM_SCOTTNR1 <- read_csv(here::here("data_raw/GCM", "GCM_SCOTTNR1_with_mmm_and_dhw.csv"))
GCM_SCOTTSL1 <- read_csv(here::here("data_raw/GCM", "GCM_SCOTTSL1_with_mmm_and_dhw.csv"))
GCM_SCOTTSL2 <- read_csv(here::here("data_raw/GCM", "GCM_SCOTTSL2_with_mmm_and_dhw.csv"))
GCM_SCOTTSL3 <- read_csv(here::here("data_raw/GCM", "GCM_SCOTTSL3_with_mmm_and_dhw.csv"))
GCM_SCOTTSS1 <- read_csv(here::here("data_raw/GCM", "GCM_SCOTTSS1_with_mmm_and_dhw.csv"))
GCM_SCOTTSS2 <- read_csv(here::here("data_raw/GCM", "GCM_SCOTTSS2_with_mmm_and_dhw.csv"))
```

```{r setting_colors_data_type, include = FALSE}
cols <- c("GCM" = "dark green", "CCI" = "dark red", "NOAA" = "navy blue")
```

# Degree Heating Week Time Series Plots for CCI, NOAA, and GCM data:      



```{r DHW_TS, echo = FALSE}
#CCI and NOAA data were first checked for duplicate dates using sum(duplicated(<dataset>$Date)) and no duplicates were ensured

#BRS05
CCI_BRS05 <- CCI_BRS05 %>% 
  mutate(Reef_Site = "BRS05", Data_Type = "CCI") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

NOAA_BRS05 <- NOAA_BRS05 %>% 
  mutate(Data_Type = "NOAA") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

GCM_BRS05 <- GCM_BRS05 %>% 
  mutate(Reef_Site = "BRS05", Data_Type = "GCM") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

BRS05_Sat_Combined <- rbind(CCI_BRS05, NOAA_BRS05, GCM_BRS05)

ggplot(BRS05_Sat_Combined)+
  geom_rect(aes_string(xmin = as.Date(c("2015-06-01")), xmax = as.Date(c("2017-06-01")),
                ymin = -Inf, ymax = Inf), color = "maroon", fill = "transparent", alpha = 0.5)+
  annotate("text", x = as.Date("2017-06-01"), y = Inf, label = "2016", hjust = 0, vjust = 1, size = 2)+
  geom_line(aes(x = Date, y = accum_DHW_12weeks, color = Data_Type), alpha = 0.3, size = 2) +
  labs(x = "Time", y = "DHW value", title = "BRS05 (-14.11, 123.54)") +
  scale_color_manual(values = cols) +
  scale_y_continuous(breaks = c(0, 4, 8, 12, 16, 20)) +
  theme(panel.grid.major.y = element_line(color = "grey", linetype = "dashed"),
        legend.key = element_rect(fill = "transparent"),
        plot.title = element_text( face = "bold"),
        panel.background = element_blank(),
        axis.line = element_line(color = "grey"),
        legend.direction = "horizontal",
        legend.position = "bottom",
        legend.title = element_blank()
  )


#BRS07
CCI_BRS07 <- CCI_BRS07 %>% 
  mutate(Reef_Site = "BRS07", Data_Type = "CCI") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

NOAA_BRS07 <- NOAA_BRS07 %>% 
  mutate(Data_Type = "NOAA") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

GCM_BRS07 <- GCM_BRS07 %>% 
  mutate(Reef_Site = "BRS07", Data_Type = "GCM") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

BRS07_Sat_Combined <- rbind(CCI_BRS07, NOAA_BRS07, GCM_BRS07)

BRS07 <- ggplot(BRS07_Sat_Combined)+
   geom_rect(aes_string(xmin = as.Date(c("2015-06-01")), xmax = as.Date(c("2017-06-01")),
                ymin = -Inf, ymax = Inf), color = "maroon", fill = "transparent", alpha = 0.5)+
  annotate("text", x = as.Date("2017-06-01"), y = Inf, label = "2016", hjust = 0, vjust = 1, size = 3)+
  geom_line(aes(x = Date, y = accum_DHW_12weeks, color = Data_Type), alpha = 0.3, size = 2) +
  scale_x_date(limits = as_date(c("1985-01-01","2030-01-01")))+
  labs(x = "", y = "", title = "(D) BRS07 (-14.12, 123.55)", subtitle = "Browse Island") +
  scale_color_manual(values = cols) +
  scale_y_continuous(breaks = c(0, 4, 8, 12, 16, 20)) +
  theme(panel.grid.major.y = element_line(color = "grey", linetype = "dashed"),
        legend.key = element_rect(fill = "transparent"),
        plot.title = element_text( face = "bold"),
        legend.position = "none",
        panel.background = element_blank(),
        axis.line = element_line(color = "grey"),
        legend.direction = "horizontal",
        legend.title = element_blank()
  )


#DAR3
CCI_DAR3 <- CCI_DAR3 %>% 
  mutate(Reef_Site = "DAR3", Data_Type = "CCI") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

NOAA_DAR3 <- NOAA_DAR3 %>% 
  mutate(Data_Type = "NOAA") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

GCM_DAR3 <- GCM_DAR3 %>% 
  mutate(Reef_Site = "DAR3", Data_Type = "GCM") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

DAR3_Sat_Combined <- rbind(CCI_DAR3, NOAA_DAR3, GCM_DAR3)

ggplot(DAR3_Sat_Combined)+
  geom_rect(aes_string(xmin = as.Date(c("1995-06-01")), xmax = as.Date(c("1997-06-01")),
                ymin = -Inf, ymax = Inf), color = "blue", fill = "transparent", alpha = 0.5)+
   geom_rect(aes_string(xmin = as.Date(c("1997-06-01")), xmax = as.Date(c("1999-06-01")),
                ymin = -Inf, ymax = Inf), color = "blue", fill = "transparent", alpha = 0.5)+
  geom_rect(aes_string(xmin = as.Date(c("2013-06-01")), xmax = as.Date(c("2015-06-01")),
                ymin = -Inf, ymax = Inf), color = "blue", fill = "transparent", alpha = 0.5)+
   geom_rect(aes_string(xmin = as.Date(c("2015-06-01")), xmax = as.Date(c("2017-06-01")),
                ymin = -Inf, ymax = Inf), color = "blue", fill = "transparent", alpha = 0.5)+
  annotate("text", x = as.Date("1995-06-01"), y = Inf, label = "1996", hjust = 1, vjust = 1, size = 2)+
  annotate("text", x = as.Date("1999-06-01"), y = Inf, label = "1998", hjust = 0, vjust = 1, size = 2)+
  annotate("text", x = as.Date("2013-06-01"), y = Inf, label = "2014", hjust = 1, vjust = 1, size = 2)+
  annotate("text", x = as.Date("2017-06-01"), y = Inf, label = "2016", hjust = 0, vjust = 1, size = 2)+
  geom_line(aes(x = Date, y = accum_DHW_12weeks, color = Data_Type), alpha = 0.3, size = 2) +
  labs(x = "Time", y = "DHW value", title = "DAR3 (-12.10, 96.88)") +
  scale_color_manual(values = cols) +
  scale_y_continuous(breaks = c(0, 4, 8, 12, 16, 20)) +
  theme(panel.grid.major.y = element_line(color = "grey", linetype = "dashed"),
        legend.key = element_rect(fill = "transparent"),
        plot.title = element_text( face = "bold"),
        panel.background = element_blank(),
        axis.line = element_line(color = "grey"),
        legend.direction = "horizontal",
        legend.position = "bottom",
        legend.title = element_blank()
  )


#DAR Long
CCI_DARL <- CCI_DARL %>% 
  mutate(Reef_Site = "DAR Long", Data_Type = "CCI") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

NOAA_DARL <- NOAA_DARL %>% 
  mutate(Data_Type = "NOAA") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

GCM_DARL <- GCM_DARL %>% 
  mutate(Reef_Site = "DAR Long", Data_Type = "GCM") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

DARL_Sat_Combined <- rbind(CCI_DARL, NOAA_DARL, GCM_DARL)

DARL <- ggplot(DARL_Sat_Combined)+
  geom_rect(aes_string(xmin = as.Date(c("1995-06-01")), xmax = as.Date(c("1997-06-01")),
                ymin = -Inf, ymax = Inf), color = "blue", fill = "transparent", alpha = 0.5)+
   geom_rect(aes_string(xmin = as.Date(c("1997-06-01")), xmax = as.Date(c("1999-06-01")),
                ymin = -Inf, ymax = Inf), color = "blue", fill = "transparent", alpha = 0.5)+
  geom_rect(aes_string(xmin = as.Date(c("2013-06-01")), xmax = as.Date(c("2015-06-01")),
                ymin = -Inf, ymax = Inf), color = "blue", fill = "transparent", alpha = 0.5)+
   geom_rect(aes_string(xmin = as.Date(c("2015-06-01")), xmax = as.Date(c("2017-06-01")),
                ymin = -Inf, ymax = Inf), color = "blue", fill = "transparent", alpha = 0.5)+
  annotate("text", x = as.Date("1995-06-01"), y = Inf, label = "1996", hjust = 1, vjust = 1, size = 3)+
  annotate("text", x = as.Date("1999-06-01"), y = Inf, label = "1998", hjust = 0, vjust = 1, size = 3)+
  annotate("text", x = as.Date("2013-06-01"), y = Inf, label = "2014", hjust = 1, vjust = 1, size = 3)+
  annotate("text", x = as.Date("2017-06-01"), y = Inf, label = "2016", hjust = 0, vjust = 1, size = 3)+
  geom_line(aes(x = Date, y = accum_DHW_12weeks, color = Data_Type), alpha = 0.3, size = 2) +
  labs(x = "", y = "DHW", title = "(A) DAR Long (-12.09, 96.88)", subtitle = "Cocos Keeling Island") +
  scale_x_date(limits = as_date(c("1985-01-01","2030-01-01")))+
  scale_color_manual(values = cols) +
  scale_y_continuous(breaks = c(0, 4, 8, 12, 16, 20)) +
  theme(panel.grid.major.y = element_line(color = "grey", linetype = "dashed"),
        legend.key = element_rect(fill = "transparent"),
        plot.title = element_text( face = "bold"),
        legend.position = "none",
        panel.background = element_blank(),
        axis.line = element_line(color = "grey"),
        legend.direction = "horizontal",
        legend.title = element_blank()
  )
   


#Scott_RPO_1
CCI_SCOTT_RPO_1 <- CCI_SCOTT_RPO_1 %>% 
  mutate(Reef_Site = "SCOTT_RPO_1", Data_Type = "CCI") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

NOAA_SCOTT_RPO_1 <- NOAA_SCOTT_RPO_1 %>% 
  mutate(Data_Type = "NOAA", Reef_Site = subsite) %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

GCM_SCOTT_RPO_1 <- GCM_SCOTT_RPO_1 %>% 
  mutate(Reef_Site = "SCOTT_RPO_1", Data_Type = "GCM") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

SCOTT_RPO_1_Sat_Combined <- rbind(CCI_SCOTT_RPO_1, NOAA_SCOTT_RPO_1, GCM_SCOTT_RPO_1)

SCOTT_RPO_1 <- ggplot(SCOTT_RPO_1_Sat_Combined)+
  geom_rect(aes_string(xmin = as.Date(c("1997-06-01")), xmax = as.Date(c("1999-06-01")),
                ymin = -Inf, ymax = Inf), color = "maroon", fill = "transparent", alpha = 0.5)+
   geom_rect(aes_string(xmin = as.Date(c("2010-06-01")), xmax = as.Date(c("2012-06-01")),
                ymin = -Inf, ymax = Inf), color = "blue", fill = "transparent", alpha = 0.5)+
  geom_rect(aes_string(xmin = as.Date(c("2012-06-01")), xmax = as.Date(c("2014-06-01")),
                ymin = -Inf, ymax = Inf), color = "blue", fill = "transparent", alpha = 0.5)+
   geom_rect(aes_string(xmin = as.Date(c("2015-06-01")), xmax = as.Date(c("2017-06-01")),
                ymin = -Inf, ymax = Inf), color = "maroon", fill = "transparent", alpha = 0.5)+
  annotate("text", x = as.Date("1999-06-01"), y = Inf, label = "1998", hjust = 0, vjust = 1, size = 3)+
  annotate("text", x = as.Date("2010-06-01"), y = Inf, label = "2011", hjust = 1, vjust = 1, size = 3)+
  annotate("text", x = as.Date("2014-06-01"), y = Inf, label = "2013", hjust = 0.5, vjust = 1, size = 3)+
  annotate("text", x = as.Date("2017-06-01"), y = Inf, label = "2016", hjust = 0, vjust = 1, size = 3)+
  geom_line(aes(x = Date, y = accum_DHW_12weeks, color = Data_Type), alpha = 0.3, size = 2) +
  scale_x_date(limits = as_date(c("1985-01-01","2030-01-01")))+
  labs(x = "", y = "", title = "(B) SCOTT_RPO_1 (-14.06, 121.78)", subtitle = "Scott Reef") +
  scale_color_manual(values = cols) +
  scale_y_continuous(breaks = c(0, 4, 8, 12, 16, 20)) +
  theme(panel.grid.major.y = element_line(color = "grey", linetype = "dashed"),
        legend.key = element_rect(fill = "transparent"),
        plot.title = element_text( face = "bold", size = 12),
        legend.position = "none",
        panel.background = element_blank(),
        axis.line = element_line(color = "grey"),
        legend.direction = "horizontal",
        legend.title = element_blank()
  )


#Scott_SL4
CCI_SCOTT_SL4 <- CCI_SCOTT_SL4 %>% 
  mutate(Reef_Site = "SCOTT_SL4", Data_Type = "CCI") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

NOAA_SCOTT_SL4 <- NOAA_SCOTT_SL4 %>% 
  mutate(Data_Type = "NOAA", Reef_Site = subsite) %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

GCM_SCOTT_SL4 <- GCM_SCOTT_SL4 %>% 
  mutate(Reef_Site = "SCOTT_SL4", Data_Type = "GCM") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

SCOTT_SL4_Sat_Combined <- rbind(CCI_SCOTT_SL4, NOAA_SCOTT_SL4, GCM_SCOTT_SL4)

ggplot(SCOTT_SL4_Sat_Combined)+
  geom_rect(aes_string(xmin = as.Date(c("1997-06-01")), xmax = as.Date(c("1999-06-01")),
                ymin = -Inf, ymax = Inf), color = "maroon", fill = "transparent", alpha = 0.5)+
   geom_rect(aes_string(xmin = as.Date(c("2010-06-01")), xmax = as.Date(c("2012-06-01")),
                ymin = -Inf, ymax = Inf), color = "blue", fill = "transparent", alpha = 0.5)+
  geom_rect(aes_string(xmin = as.Date(c("2012-06-01")), xmax = as.Date(c("2014-06-01")),
                ymin = -Inf, ymax = Inf), color = "blue", fill = "transparent", alpha = 0.5)+
   geom_rect(aes_string(xmin = as.Date(c("2015-06-01")), xmax = as.Date(c("2017-06-01")),
                ymin = -Inf, ymax = Inf), color = "maroon", fill = "transparent", alpha = 0.5)+
  annotate("text", x = as.Date("1999-06-01"), y = Inf, label = "1998", hjust = 0, vjust = 1, size = 2)+
  annotate("text", x = as.Date("2010-06-01"), y = Inf, label = "2011", hjust = 1, vjust = 1, size = 2)+
  annotate("text", x = as.Date("2014-06-01"), y = Inf, label = "2013", hjust = 0.5, vjust = 1, size = 2)+
  annotate("text", x = as.Date("2017-06-01"), y = Inf, label = "2016", hjust = 0, vjust = 1, size = 2)+
  geom_line(aes(x = Date, y = accum_DHW_12weeks, color = Data_Type), alpha = 0.3, size = 2) +
  labs(x = "Time", y = "DHW value", title = "SCOTT_SL4 (-14.02, 121.86)") +
  scale_color_manual(values = cols) +
  scale_y_continuous(breaks = c(0, 4, 8, 12, 16, 20)) +
  theme(panel.grid.major.y = element_line(color = "grey", linetype = "dashed"),
        legend.key = element_rect(fill = "transparent"),
        plot.title = element_text( face = "bold"),
        panel.background = element_blank(),
        axis.line = element_line(color = "grey"),
        legend.direction = "horizontal",
        legend.position = "bottom",
        legend.title = element_blank()
  )
  

#Scott_SS3
CCI_SCOTT_SS3 <- CCI_SCOTT_SS3 %>% 
  mutate(Reef_Site = "SCOTT_SS3", Data_Type = "CCI") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

NOAA_SCOTT_SS3 <- NOAA_SCOTT_SS3 %>% 
  mutate(Data_Type = "NOAA", Reef_Site = subsite) %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

GCM_SCOTT_SS3 <- GCM_SCOTT_SS3 %>% 
  mutate(Reef_Site = "SCOTT_SS3", Data_Type = "GCM") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

SCOTT_SS3_Sat_Combined <- rbind(CCI_SCOTT_SS3, NOAA_SCOTT_SS3, GCM_SCOTT_SS3)

ggplot(SCOTT_SS3_Sat_Combined)+
  geom_rect(aes_string(xmin = as.Date(c("1997-06-01")), xmax = as.Date(c("1999-06-01")),
                ymin = -Inf, ymax = Inf), color = "maroon", fill = "transparent", alpha = 0.5)+
   geom_rect(aes_string(xmin = as.Date(c("2010-06-01")), xmax = as.Date(c("2012-06-01")),
                ymin = -Inf, ymax = Inf), color = "blue", fill = "transparent", alpha = 0.5)+
  geom_rect(aes_string(xmin = as.Date(c("2012-06-01")), xmax = as.Date(c("2014-06-01")),
                ymin = -Inf, ymax = Inf), color = "blue", fill = "transparent", alpha = 0.5)+
   geom_rect(aes_string(xmin = as.Date(c("2015-06-01")), xmax = as.Date(c("2017-06-01")),
                ymin = -Inf, ymax = Inf), color = "maroon", fill = "transparent", alpha = 0.5)+
  annotate("text", x = as.Date("1999-06-01"), y = Inf, label = "1998", hjust = 0, vjust = 1, size = 2)+
  annotate("text", x = as.Date("2010-06-01"), y = Inf, label = "2011", hjust = 1, vjust = 1, size = 2)+
  annotate("text", x = as.Date("2014-06-01"), y = Inf, label = "2013", hjust = 0.5, vjust = 1, size = 2)+
  annotate("text", x = as.Date("2017-06-01"), y = Inf, label = "2016", hjust = 0, vjust = 1, size = 2)+
  geom_line(aes(x = Date, y = accum_DHW_12weeks, color = Data_Type), alpha = 0.3, size = 2) +
  labs(x = "Time", y = "DHW value", title = "SCOTT_SS3 (-13.64, 122.03)") +
  scale_color_manual(values = cols) +
  scale_y_continuous(breaks = c(0, 4, 8, 12, 16, 20)) +
  theme(panel.grid.major.y = element_line(color = "grey", linetype = "dashed"),
        legend.key = element_rect(fill = "transparent"),
        plot.title = element_text( face = "bold"),
        panel.background = element_blank(),
        axis.line = element_line(color = "grey"),
        legend.direction = "horizontal",
        legend.position = "bottom",
        legend.title = element_blank()
  )


#ScottNR1
CCI_SCOTTNR1 <- CCI_SCOTTNR1 %>% 
  mutate(Reef_Site = "SCOTTNR1", Data_Type = "CCI") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

NOAA_SCOTTNR1 <- NOAA_SCOTTNR1 %>% 
  mutate(Data_Type = "NOAA", Reef_Site = subsite) %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

GCM_SCOTTNR1 <- GCM_SCOTTNR1 %>% 
  mutate(Reef_Site = "SCOTTNR1", Data_Type = "GCM") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

SCOTTNR1_Sat_Combined <- rbind(CCI_SCOTTNR1, NOAA_SCOTTNR1, GCM_SCOTTNR1)

ggplot(SCOTTNR1_Sat_Combined)+
  geom_rect(aes_string(xmin = as.Date(c("1997-06-01")), xmax = as.Date(c("1999-06-01")),
                ymin = -Inf, ymax = Inf), color = "maroon", fill = "transparent", alpha = 0.5)+
   geom_rect(aes_string(xmin = as.Date(c("2010-06-01")), xmax = as.Date(c("2012-06-01")),
                ymin = -Inf, ymax = Inf), color = "blue", fill = "transparent", alpha = 0.5)+
  geom_rect(aes_string(xmin = as.Date(c("2012-06-01")), xmax = as.Date(c("2014-06-01")),
                ymin = -Inf, ymax = Inf), color = "blue", fill = "transparent", alpha = 0.5)+
   geom_rect(aes_string(xmin = as.Date(c("2015-06-01")), xmax = as.Date(c("2017-06-01")),
                ymin = -Inf, ymax = Inf), color = "maroon", fill = "transparent", alpha = 0.5)+
  annotate("text", x = as.Date("1999-06-01"), y = Inf, label = "1998", hjust = 0, vjust = 1, size = 2)+
  annotate("text", x = as.Date("2010-06-01"), y = Inf, label = "2011", hjust = 1, vjust = 1, size = 2)+
  annotate("text", x = as.Date("2014-06-01"), y = Inf, label = "2013", hjust = 0.5, vjust = 1, size = 2)+
  annotate("text", x = as.Date("2017-06-01"), y = Inf, label = "2016", hjust = 0, vjust = 1, size = 2)+
  geom_line(aes(x = Date, y = accum_DHW_12weeks, color = Data_Type), alpha = 0.3, size = 2) +
  labs(x = "Time", y = "DHW value", title = "SCOTTNR1 (-13.99, 121.88)") +
  scale_color_manual(values = cols) +
  scale_y_continuous(breaks = c(0, 4, 8, 12, 16, 20)) +
  theme(panel.grid.major.y = element_line(color = "grey", linetype = "dashed"),
        legend.key = element_rect(fill = "transparent"),
        plot.title = element_text( face = "bold"),
        panel.background = element_blank(),
        axis.line = element_line(color = "grey"),
        legend.direction = "horizontal",
        legend.position = "bottom",
        legend.title = element_blank()
  )


#ScottSL1
CCI_SCOTTSL1 <- CCI_SCOTTSL1 %>% 
  mutate(Reef_Site = "SCOTTSL1", Data_Type = "CCI") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

NOAA_SCOTTSL1 <- NOAA_SCOTTSL1 %>% 
  mutate(Data_Type = "NOAA", Reef_Site = subsite) %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

GCM_SCOTTSL1 <- GCM_SCOTTSL1 %>% 
  mutate(Reef_Site = "SCOTTSL1", Data_Type = "GCM") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

SCOTTSL1_Sat_Combined <- rbind(CCI_SCOTTSL1, NOAA_SCOTTSL1, GCM_SCOTTSL1)

SCOTTSL1 <- ggplot(SCOTTSL1_Sat_Combined)+
  geom_rect(aes_string(xmin = as.Date(c("1997-06-01")), xmax = as.Date(c("1999-06-01")),
                ymin = -Inf, ymax = Inf), color = "maroon", fill = "transparent", alpha = 0.5)+
   geom_rect(aes_string(xmin = as.Date(c("2010-06-01")), xmax = as.Date(c("2012-06-01")),
                ymin = -Inf, ymax = Inf), color = "blue", fill = "transparent", alpha = 0.5)+
  geom_rect(aes_string(xmin = as.Date(c("2012-06-01")), xmax = as.Date(c("2014-06-01")),
                ymin = -Inf, ymax = Inf), color = "blue", fill = "transparent", alpha = 0.5)+
   geom_rect(aes_string(xmin = as.Date(c("2015-06-01")), xmax = as.Date(c("2017-06-01")),
                ymin = -Inf, ymax = Inf), color = "maroon", fill = "transparent", alpha = 0.5)+
  annotate("text", x = as.Date("1999-06-01"), y = Inf, label = "1998", hjust = 0, vjust = 1, size = 3)+
  annotate("text", x = as.Date("2010-06-01"), y = Inf, label = "2011", hjust = 1, vjust = 1, size = 3)+
  annotate("text", x = as.Date("2014-06-01"), y = Inf, label = "2013", hjust = 0.5, vjust = 1, size = 3)+
  annotate("text", x = as.Date("2017-06-01"), y = Inf, label = "2016", hjust = 0, vjust = 1, size = 3)+
  geom_line(aes(x = Date, y = accum_DHW_12weeks, color = Data_Type), alpha = 0.3, size = 2) +
  scale_x_date(limits = as_date(c("1985-01-01","2030-01-01")))+
  labs(x = "", y = "DHW", title = "(C) SCOTTSL1 (-14.08, 121.95)", subtitle = "Scott Reef") +
  scale_color_manual(values = cols) +
  scale_y_continuous(breaks = c(0, 4, 8, 12, 16, 20)) +
  theme(panel.grid.major.y = element_line(color = "grey", linetype = "dashed"),
        legend.key = element_rect(fill = "transparent"),
        plot.title = element_text( face = "bold"),
        legend.position = "none",
        panel.background = element_blank(),
        axis.line = element_line(color = "grey"),
        legend.direction = "horizontal",
        legend.title = element_blank()
  )


#ScottSL2
CCI_SCOTTSL2 <- CCI_SCOTTSL2 %>% 
  mutate(Reef_Site = "SCOTTSL2", Data_Type = "CCI") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

NOAA_SCOTTSL2 <- NOAA_SCOTTSL2 %>% 
  mutate(Data_Type = "NOAA", Reef_Site = subsite) %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

GCM_SCOTTSL2 <- GCM_SCOTTSL2 %>% 
  mutate(Reef_Site = "SCOTTSL2", Data_Type = "GCM") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

SCOTTSL2_Sat_Combined <- rbind(CCI_SCOTTSL2, NOAA_SCOTTSL2, GCM_SCOTTSL2)

ggplot(SCOTTSL2_Sat_Combined)+
  geom_rect(aes_string(xmin = as.Date(c("1997-06-01")), xmax = as.Date(c("1999-06-01")),
                ymin = -Inf, ymax = Inf), color = "maroon", fill = "transparent", alpha = 0.5)+
   geom_rect(aes_string(xmin = as.Date(c("2010-06-01")), xmax = as.Date(c("2012-06-01")),
                ymin = -Inf, ymax = Inf), color = "blue", fill = "transparent", alpha = 0.5)+
  geom_rect(aes_string(xmin = as.Date(c("2012-06-01")), xmax = as.Date(c("2014-06-01")),
                ymin = -Inf, ymax = Inf), color = "blue", fill = "transparent", alpha = 0.5)+
   geom_rect(aes_string(xmin = as.Date(c("2015-06-01")), xmax = as.Date(c("2017-06-01")),
                ymin = -Inf, ymax = Inf), color = "maroon", fill = "transparent", alpha = 0.5)+
  annotate("text", x = as.Date("1999-06-01"), y = Inf, label = "1998", hjust = 0, vjust = 1, size = 2)+
  annotate("text", x = as.Date("2010-06-01"), y = Inf, label = "2011", hjust = 1, vjust = 1, size = 2)+
  annotate("text", x = as.Date("2014-06-01"), y = Inf, label = "2013", hjust = 0.5, vjust = 1, size = 2)+
  annotate("text", x = as.Date("2017-06-01"), y = Inf, label = "2016", hjust = 0, vjust = 1, size = 2)+
  geom_line(aes(x = Date, y = accum_DHW_12weeks, color = Data_Type), alpha = 0.3, size = 2) +
  labs(x = "Time", y = "DHW value", title = "SCOTTSL2 (-14.19, 121.80)") +
  scale_color_manual(values = cols) +
  scale_y_continuous(breaks = c(0, 4, 8, 12, 16, 20)) +
  theme(panel.grid.major.y = element_line(color = "grey", linetype = "dashed"),
        legend.key = element_rect(fill = "transparent"),
        plot.title = element_text( face = "bold"),
        panel.background = element_blank(),
        axis.line = element_line(color = "grey"),
        legend.direction = "horizontal",
        legend.position = "bottom",
        legend.title = element_blank()
  )


#ScottSL3
CCI_SCOTTSL3 <- CCI_SCOTTSL3 %>% 
  mutate(Reef_Site = "SCOTTSL3", Data_Type = "CCI") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

NOAA_SCOTTSL3 <- NOAA_SCOTTSL3 %>% 
  mutate(Data_Type = "NOAA", Reef_Site = subsite) %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

GCM_SCOTTSL3 <- GCM_SCOTTSL3 %>% 
  mutate(Reef_Site = "SCOTTSL3", Data_Type = "GCM") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

SCOTTSL3_Sat_Combined <- rbind(CCI_SCOTTSL3, NOAA_SCOTTSL3, GCM_SCOTTSL3)

ggplot(SCOTTSL3_Sat_Combined)+
  geom_rect(aes_string(xmin = as.Date(c("1997-06-01")), xmax = as.Date(c("1999-06-01")),
                ymin = -Inf, ymax = Inf), color = "maroon", fill = "transparent", alpha = 0.5)+
   geom_rect(aes_string(xmin = as.Date(c("2010-06-01")), xmax = as.Date(c("2012-06-01")),
                ymin = -Inf, ymax = Inf), color = "blue", fill = "transparent", alpha = 0.5)+
  geom_rect(aes_string(xmin = as.Date(c("2012-06-01")), xmax = as.Date(c("2014-06-01")),
                ymin = -Inf, ymax = Inf), color = "blue", fill = "transparent", alpha = 0.5)+
   geom_rect(aes_string(xmin = as.Date(c("2015-06-01")), xmax = as.Date(c("2017-06-01")),
                ymin = -Inf, ymax = Inf), color = "maroon", fill = "transparent", alpha = 0.5)+
  annotate("text", x = as.Date("1999-06-01"), y = Inf, label = "1998", hjust = 0, vjust = 1, size = 2)+
  annotate("text", x = as.Date("2010-06-01"), y = Inf, label = "2011", hjust = 1, vjust = 1, size = 2)+
  annotate("text", x = as.Date("2014-06-01"), y = Inf, label = "2013", hjust = 0.5, vjust = 1, size = 2)+
  annotate("text", x = as.Date("2017-06-01"), y = Inf, label = "2016", hjust = 0, vjust = 1, size = 2)+
  geom_line(aes(x = Date, y = accum_DHW_12weeks, color = Data_Type), alpha = 0.3, size = 2) +
  labs(x = "Time", y = "DHW value", title = "SCOTTSL3 (-14.07, 121.78)") +
  scale_color_manual(values = cols) +
  scale_y_continuous(breaks = c(0, 4, 8, 12, 16, 20)) +
  theme(panel.grid.major.y = element_line(color = "grey", linetype = "dashed"),
        legend.key = element_rect(fill = "transparent"),
        plot.title = element_text( face = "bold"),
        panel.background = element_blank(),
        axis.line = element_line(color = "grey"),
        legend.direction = "horizontal",
        legend.position = "bottom",
        legend.title = element_blank()
  )


#ScottSS1
CCI_SCOTTSS1 <- CCI_SCOTTSS1 %>% 
  mutate(Reef_Site = "SCOTTSS1", Data_Type = "CCI") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

NOAA_SCOTTSS1 <- NOAA_SCOTTSS1 %>% 
  mutate(Data_Type = "NOAA", Reef_Site = subsite) %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

GCM_SCOTTSS1 <- GCM_SCOTTSS1 %>% 
  mutate(Reef_Site = "SCOTTSS1", Data_Type = "GCM") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

SCOTTSS1_Sat_Combined <- rbind(CCI_SCOTTSS1, NOAA_SCOTTSS1, GCM_SCOTTSS1)

ggplot(SCOTTSS1_Sat_Combined)+
  geom_rect(aes_string(xmin = as.Date(c("1997-06-01")), xmax = as.Date(c("1999-06-01")),
                ymin = -Inf, ymax = Inf), color = "maroon", fill = "transparent", alpha = 0.5)+
   geom_rect(aes_string(xmin = as.Date(c("2010-06-01")), xmax = as.Date(c("2012-06-01")),
                ymin = -Inf, ymax = Inf), color = "blue", fill = "transparent", alpha = 0.5)+
  geom_rect(aes_string(xmin = as.Date(c("2012-06-01")), xmax = as.Date(c("2014-06-01")),
                ymin = -Inf, ymax = Inf), color = "blue", fill = "transparent", alpha = 0.5)+
   geom_rect(aes_string(xmin = as.Date(c("2015-06-01")), xmax = as.Date(c("2017-06-01")),
                ymin = -Inf, ymax = Inf), color = "maroon", fill = "transparent", alpha = 0.5)+
  annotate("text", x = as.Date("1999-06-01"), y = Inf, label = "1998", hjust = 0, vjust = 1, size = 2)+
  annotate("text", x = as.Date("2010-06-01"), y = Inf, label = "2011", hjust = 1, vjust = 1, size = 2)+
  annotate("text", x = as.Date("2014-06-01"), y = Inf, label = "2013", hjust = 0.5, vjust = 1, size = 2)+
  annotate("text", x = as.Date("2017-06-01"), y = Inf, label = "2016", hjust = 0, vjust = 1, size = 2)+
  geom_line(aes(x = Date, y = accum_DHW_12weeks, color = Data_Type), alpha = 0.3, size = 2) +
  labs(x = "Time", y = "DHW value", title = "SCOTTSS1 (-14.08, 121.98)") +
  scale_color_manual(values = cols) +
  scale_y_continuous(breaks = c(0, 4, 8, 12, 16, 20)) +
  theme(panel.grid.major.y = element_line(color = "grey", linetype = "dashed"),
        legend.key = element_rect(fill = "transparent"),
        plot.title = element_text( face = "bold"),
        panel.background = element_blank(),
        axis.line = element_line(color = "grey"),
        legend.direction = "horizontal",
        legend.position = "bottom",
        legend.title = element_blank()
  )


#ScottSS2
CCI_SCOTTSS2 <- CCI_SCOTTSS2 %>% 
  mutate(Reef_Site = "SCOTTSS2", Data_Type = "CCI") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

NOAA_SCOTTSS2 <- NOAA_SCOTTSS2 %>% 
  mutate(Data_Type = "NOAA", Reef_Site = subsite) %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

GCM_SCOTTSS2 <- GCM_SCOTTSS2 %>% 
  mutate(Reef_Site = "SCOTTSS2", Data_Type = "GCM") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

SCOTTSS2_Sat_Combined <- rbind(CCI_SCOTTSS2, NOAA_SCOTTSS2, GCM_SCOTTSS2)

ggplot(SCOTTSS2_Sat_Combined)+
  geom_rect(aes_string(xmin = as.Date(c("1997-06-01")), xmax = as.Date(c("1999-06-01")),
                ymin = -Inf, ymax = Inf), color = "maroon", fill = "transparent", alpha = 0.5)+
   geom_rect(aes_string(xmin = as.Date(c("2010-06-01")), xmax = as.Date(c("2012-06-01")),
                ymin = -Inf, ymax = Inf), color = "blue", fill = "transparent", alpha = 0.5)+
  geom_rect(aes_string(xmin = as.Date(c("2012-06-01")), xmax = as.Date(c("2014-06-01")),
                ymin = -Inf, ymax = Inf), color = "blue", fill = "transparent", alpha = 0.5)+
   geom_rect(aes_string(xmin = as.Date(c("2015-06-01")), xmax = as.Date(c("2017-06-01")),
                ymin = -Inf, ymax = Inf), color = "maroon", fill = "transparent", alpha = 0.5)+
  annotate("text", x = as.Date("1999-06-01"), y = Inf, label = "1998", hjust = 0, vjust = 1, size = 2)+
  annotate("text", x = as.Date("2010-06-01"), y = Inf, label = "2011", hjust = 1, vjust = 1, size = 2)+
  annotate("text", x = as.Date("2014-06-01"), y = Inf, label = "2013", hjust = 0.5, vjust = 1, size = 2)+
  annotate("text", x = as.Date("2017-06-01"), y = Inf, label = "2016", hjust = 0, vjust = 1, size = 2)+
  geom_line(aes(x = Date, y = accum_DHW_12weeks, color = Data_Type), alpha = 0.3, size = 2) +
  labs(x = "Time", y = "DHW value", title = "SCOTTSS2 (-13.92, 121.92)") +
  scale_color_manual(values = cols) +
  scale_y_continuous(breaks = c(0, 4, 8, 12, 16, 20)) +
  theme(panel.grid.major.y = element_line(color = "grey", linetype = "dashed"),
        legend.key = element_rect(fill = "transparent"),
        plot.title = element_text( face = "bold"),
        panel.background = element_blank(),
        axis.line = element_line(color = "grey"),
        legend.direction = "horizontal",
        legend.position = "bottom",
        legend.title = element_blank()
  )


#Ningaloo BUN05A
CCI_BUN05A <- CCI_BUN05A %>% 
  mutate(Reef_Site = "BUN05A", Data_Type = "CCI") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

NOAA_BUN05A <- NOAA_BUN05A %>% 
  mutate(Data_Type = "NOAA") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

GCM_BUN05A <- GCM_BUN05A %>% 
  mutate(Reef_Site = "BUN05A", Data_Type = "GCM") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

BUN05A_Sat_Combined <- rbind(CCI_BUN05A, NOAA_BUN05A, GCM_BUN05A)

ggplot(BUN05A_Sat_Combined)+
   geom_rect(aes_string(xmin = as.Date(c("2010-06-01")), xmax = as.Date(c("2012-06-01")),
                ymin = -Inf, ymax = Inf), color = "maroon", fill = "transparent", alpha = 0.5)+
    geom_rect(aes_string(xmin = as.Date(c("2015-06-01")), xmax = as.Date(c("2017-06-01")),
                ymin = -Inf, ymax = Inf), color = "blue", fill = "transparent", alpha = 0.5)+
  annotate("text", x = as.Date("2012-06-01"), y = Inf, label = "2011", hjust = 0, vjust = 1, size = 2)+
  annotate("text", x = as.Date("2017-06-01"), y = Inf, label = "2016", hjust = 0, vjust = 1, size = 2)+
  geom_line(aes(x = Date, y = accum_DHW_12weeks, color = Data_Type), alpha = 0.3, size = 2) +
  labs(x = "Time", y = "DHW value", title = "BUN05A (-21.84, 114.18)") +
  scale_color_manual(values = cols) +
  scale_y_continuous(breaks = c(0, 4, 8, 12, 16, 20)) +
  theme(panel.grid.major.y = element_line(color = "grey", linetype = "dashed"),
        legend.key = element_rect(fill = "transparent"),
        plot.title = element_text( face = "bold"),
        panel.background = element_blank(),
        axis.line = element_line(color = "grey"),
        legend.direction = "horizontal",
        legend.position = "bottom",
        legend.title = element_blank()
  )


#Ningaloo Bundegi
CCI_Bundegi <- CCI_Bundegi %>% 
  mutate(Reef_Site = "Bundegi", Data_Type = "CCI") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

NOAA_Bundegi <- NOAA_Bundegi %>% 
  mutate(Data_Type = "NOAA") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

GCM_Bundegi <- GCM_Bundegi %>% 
  mutate(Reef_Site = "Bundegi", Data_Type = "GCM") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

Bundegi_Sat_Combined <- rbind(CCI_Bundegi, NOAA_Bundegi, GCM_Bundegi)

Bundegi <- ggplot(Bundegi_Sat_Combined)+
  geom_rect(aes_string(xmin = as.Date(c("2010-06-01")), xmax = as.Date(c("2012-06-01")),
                ymin = -Inf, ymax = Inf), color = "maroon", fill = "transparent", alpha = 0.5)+
    geom_rect(aes_string(xmin = as.Date(c("2015-06-01")), xmax = as.Date(c("2017-06-01")),
                ymin = -Inf, ymax = Inf), color = "blue", fill = "transparent", alpha = 0.5)+
  annotate("text", x = as.Date("2012-06-01"), y = Inf, label = "2011", hjust = 0, vjust = 1, size = 3)+
  annotate("text", x = as.Date("2017-06-01"), y = Inf, label = "2016", hjust = 0, vjust = 1, size = 3)+
  geom_line(aes(x = Date, y = accum_DHW_12weeks, color = Data_Type), alpha = 0.3, size = 2) +
  scale_x_date(limits = as_date(c("1985-01-01","2030-01-01")))+
  labs(x = "", y = "DHW", title = "(E) 08BND, 13BND (-21.87, 114.16)", subtitle = "Ningaloo Reef") +
  scale_color_manual(values = cols) +
  scale_y_continuous(breaks = c(0, 4, 8, 12, 16, 20)) +
  theme(panel.grid.major.y = element_line(color = "grey", linetype = "dashed"),
        legend.key = element_rect(fill = "transparent"),
        plot.title = element_text( face = "bold", size = 12),
        legend.position = "none",
        panel.background = element_blank(),
        axis.line = element_line(color = "grey"),
        legend.direction = "horizontal",
        legend.title = element_blank()
  )


#Ningaloo Tantabiddi
CCI_Tantabiddi <- CCI_Tantabiddi %>% 
  mutate(Reef_Site = "Tantabiddi", Data_Type = "CCI") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

NOAA_Tantabiddi <- NOAA_Tantabiddi %>% 
  mutate(Data_Type = "NOAA") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

GCM_Tantabiddi <- GCM_Tantabiddi %>% 
  mutate(Reef_Site = "Tantabiddi", Data_Type = "GCM") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

Tantabiddi_Sat_Combined <- rbind(CCI_Tantabiddi, NOAA_Tantabiddi, GCM_Tantabiddi)

Tantabiddi <- ggplot(Tantabiddi_Sat_Combined)+
  geom_rect(aes_string(xmin = as.Date(c("2010-06-01")), xmax = as.Date(c("2012-06-01")),
                ymin = -Inf, ymax = Inf), color = "maroon", fill = "transparent", alpha = 0.5)+
    geom_rect(aes_string(xmin = as.Date(c("2015-06-01")), xmax = as.Date(c("2017-06-01")),
                ymin = -Inf, ymax = Inf), color = "blue", fill = "transparent", alpha = 0.5)+
  annotate("text", x = as.Date("2012-06-01"), y = Inf, label = "2011", hjust = 0, vjust = 1, size = 3)+
  annotate("text", x = as.Date("2017-06-01"), y = Inf, label = "2016", hjust = 0, vjust = 1, size = 3)+
  geom_line(aes(x = Date, y = accum_DHW_12weeks, color = Data_Type), alpha = 0.3, size = 2) +
  labs(x = "", y = "", title = "(F) 08TNT, 13TNT (-21.91, 113.97)", subtitle = "Ningaloo Reef") +
  scale_x_date(limits = as_date(c("1985-01-01","2030-01-01")))+
  scale_color_manual(values = cols) +
  scale_y_continuous(breaks = c(0, 4, 8, 12, 16, 20)) +
  theme(panel.grid.major.y = element_line(color = "grey", linetype = "dashed"),
        legend.key = element_rect(fill = "transparent"),
        plot.title = element_text( face = "bold", size = 12),
        legend.position = "none",
        panel.background = element_blank(),
        axis.line = element_line(color = "grey"),
        legend.direction = "horizontal",
        legend.title = element_blank()
  )


#Ningaloo TNT
#CCI_TNT <- CCI_TNT %>% 
#  mutate(Reef_Site = "TNT", Data_Type = "CCI") %>% 
#  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

#NOAA_TNT <- NOAA_TNT %>% 
#  mutate(Data_Type = "NOAA") %>% 
#  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

#TNT_Sat_Combined <- rbind(CCI_TNT, NOAA_TNT)

#ggplot(TNT_Sat_Combined)+
#  geom_rect(aes_string(xmin = as.Date(c("2010-06-01")), xmax = as.Date(c("2012-06-01")),
#                ymin = -Inf, ymax = Inf), color = "maroon", fill = "transparent", alpha = 0.5)+
#    geom_rect(aes_string(xmin = as.Date(c("2015-06-01")), xmax = as.Date(c("2017-06-01")),
#                ymin = -Inf, ymax = Inf), color = "blue", fill = "transparent", alpha = 0.5)+
#  geom_line(aes(x = Date, y = accum_DHW_12weeks, color = Data_Type), alpha = 0.3, size = 2) +
#  labs(x = "Time", y = "DHW value", title = "Time Series of TNT (-21.9, 113.97) Degree Heating Week values") +
#  scale_color_discrete_qualitative(name = "Satellite") +
#  scale_y_continuous(breaks = c(0, 4, 8, 12, 16, 20)) +
#  theme(panel.grid.major.y = element_line(color = "grey", linetype = "dashed"),
#        legend.key = element_rect(fill = "transparent"),
#        plot.title = element_text( face = "bold")
#  )


#Ningaloo TNT07C
CCI_TNT07C <- CCI_TNT07C %>% 
  mutate(Reef_Site = "TNT07C", Data_Type = "CCI") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

NOAA_TNT07C <- NOAA_TNT07C %>% 
  mutate(Data_Type = "NOAA") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

GCM_TNT07C <- GCM_TNT07C %>% 
  mutate(Reef_Site = "TNT07C", Data_Type = "GCM") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

TNT07C_Sat_Combined <- rbind(CCI_TNT07C, NOAA_TNT07C, GCM_TNT07C)

ggplot(TNT07C_Sat_Combined)+
  geom_rect(aes_string(xmin = as.Date(c("2010-06-01")), xmax = as.Date(c("2012-06-01")),
                ymin = -Inf, ymax = Inf), color = "maroon", fill = "transparent", alpha = 0.5)+
    geom_rect(aes_string(xmin = as.Date(c("2015-06-01")), xmax = as.Date(c("2017-06-01")),
                ymin = -Inf, ymax = Inf), color = "blue", fill = "transparent", alpha = 0.5)+
  annotate("text", x = as.Date("2012-06-01"), y = Inf, label = "2011", hjust = 0, vjust = 1, size = 2)+
  annotate("text", x = as.Date("2017-06-01"), y = Inf, label = "2016", hjust = 0, vjust = 1, size = 2)+
  geom_line(aes(x = Date, y = accum_DHW_12weeks, color = Data_Type), alpha = 0.3, size = 2) +
  labs(x = "Time", y = "DHW value", title = "TNT07C (-21.89, 113.96)") +
  scale_color_manual(values = cols) +
  scale_y_continuous(breaks = c(0, 4, 8, 12, 16, 20)) +
  theme(panel.grid.major.y = element_line(color = "grey", linetype = "dashed"),
        legend.key = element_rect(fill = "transparent"),
        plot.title = element_text( face = "bold"),
        panel.background = element_blank(),
        axis.line = element_line(color = "grey"),
        legend.direction = "horizontal",
        legend.position = "bottom",
        legend.title = element_blank()
  )


#Houtman Abrolhos Wallabi Island
#CCI_Wallabi_Island <- CCI_Wallabi_Island %>% 
#  mutate(Reef_Site = "Wallabi Island", Data_Type = "CCI") %>% 
#  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

#NOAA_Wallabi_Island <- NOAA_Wallabi_Island %>% 
#  mutate(Data_Type = "NOAA") %>% 
#  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

#Wallabi_Island_Sat_Combined <- rbind(CCI_Wallabi_Island, NOAA_Wallabi_Island)

#ggplot(Wallabi_Island_Sat_Combined)+
#  geom_rect(aes_string(xmin = as.Date(c("2010-06-01")), xmax = as.Date(c("2012-06-01")),
#                ymin = -Inf, ymax = Inf), color = "maroon", fill = "transparent", alpha = 0.5)+
#  geom_line(aes(x = Date, y = accum_DHW_12weeks, color = Data_Type), alpha = 0.3, size = 2) +
#  labs(x = "Time", y = "DHW value", title = "Time Series of Wallabi Island (-28.28, 113.46) Degree Heating Week values") +
#  scale_color_discrete_qualitative(name = "Satellite") +
#  scale_y_continuous(breaks = c(0, 4, 8, 12, 16, 20)) +
#  theme(panel.grid.major.y = element_line(color = "grey", linetype = "dashed"),
#        legend.key = element_rect(fill = "transparent"),
#        plot.title = element_text( face = "bold")
#  )


#Houtman Abrolhos HAB05B
CCI_HAB05B <- CCI_HAB05B %>% 
  mutate(Reef_Site = "HAB05B", Data_Type = "CCI") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

NOAA_HAB05B <- NOAA_HAB05B %>% 
  mutate(Data_Type = "NOAA") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

GCM_HAB05B <- GCM_HAB05B %>% 
  mutate(Reef_Site = "HAB05B", Data_Type = "GCM") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

HAB05B_Sat_Combined <- rbind(CCI_HAB05B, NOAA_HAB05B, GCM_HAB05B)

HAB05B <- ggplot(HAB05B_Sat_Combined)+
  geom_rect(aes_string(xmin = as.Date(c("2010-06-01")), xmax = as.Date(c("2012-06-01")),
                ymin = -Inf, ymax = Inf), color = "maroon", fill = "transparent", alpha = 0.5)+
  annotate("text", x = as.Date("2012-06-01"), y = Inf, label = "2011", hjust = 0, vjust = 1, size = 3)+
  geom_line(aes(x = Date, y = accum_DHW_12weeks, color = Data_Type), alpha = 0.3, size = 2) +
  scale_x_date(limits = as_date(c("1985-01-01","2030-01-01")))+
  labs(x = "Time", y = "", title = "(H) HAB05B (-28.46, 113.77)", subtitle = "Houtman Abrolhos") +
  scale_color_manual(values = cols) +
  scale_y_continuous(breaks = c(0, 4, 8, 12, 16, 20)) +
  theme(panel.grid.major.y = element_line(color = "grey", linetype = "dashed"),
        legend.key = element_rect(fill = "transparent"),
        plot.title = element_text( face = "bold"),
        legend.position = "none",
        panel.background = element_blank(),
        axis.line = element_line(color = "grey"),
        legend.direction = "horizontal",
        legend.title = element_blank()
  )


#Houtman Abrolhos HAB10A
CCI_HAB10A <- CCI_HAB10A %>% 
  mutate(Reef_Site = "HAB10A", Data_Type = "CCI") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

NOAA_HAB10A <- NOAA_HAB10A %>% 
  mutate(Data_Type = "NOAA") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

GCM_HAB10A <- GCM_HAB10A %>% 
  mutate(Reef_Site = "HAB10A", Data_Type = "GCM") %>% 
  select(sst, Latitude, Longitude, Date, hotspot, degree_heating_week_mmm_from_sst, accum_DHW_12weeks, Reef_Site, Data_Type)

HAB10A_Sat_Combined <- rbind(CCI_HAB10A, NOAA_HAB10A, GCM_HAB10A)

HAB10A <- ggplot(HAB10A_Sat_Combined)+
  geom_rect(aes_string(xmin = as.Date(c("2010-06-01")), xmax = as.Date(c("2012-06-01")),
                ymin = -Inf, ymax = Inf), color = "maroon", fill = "transparent", alpha = 0.5)+
  annotate("text", x = as.Date("2012-06-01"), y = Inf, label = "2011", hjust = 0, vjust = 1, size = 3)+
  geom_line(aes(x = Date, y = accum_DHW_12weeks, color = Data_Type), alpha = 0.3, size = 2) +
  labs(x = "Time", y = "DHW", title = "(G) HAB10A (-28.46, 113.75)", subtitle = "Houtman Abrolhos") +
  scale_x_date(limits = as_date(c("1985-01-01","2030-01-01")))+
  scale_color_manual(values = cols) +
  scale_y_continuous(breaks = c(0, 4, 8, 12, 16, 20)) +
  theme(panel.grid.major.y = element_line(color = "grey", linetype = "dashed"),
        legend.key = element_rect(fill = "transparent"),
        plot.title = element_text( face = "bold"),
        legend.position = "none",
        panel.background = element_blank(),
        axis.line = element_line(color = "grey"),
        legend.direction = "horizontal",
        legend.title = element_blank()
  )


```


```{r Combined_Sites, echo = FALSE}
(DARL + SCOTT_RPO_1) /
(SCOTTSL1 + BRS07) 

(Bundegi + Tantabiddi)/
(HAB10A + HAB05B)


```


```{r Frequency_Tables, echo = FALSE, message = FALSE, include = FALSE}
#DAR Long
freq_mod_DHW_DARL <- DARL_Sat_Combined %>% 
  select(Date, accum_DHW_12weeks, Data_Type) %>% 
  pivot_wider(names_from = Data_Type, values_from = accum_DHW_12weeks) %>% 
  na.omit() %>% 
  pivot_longer(cols = c(CCI, NOAA, GCM), names_to = "Data Type", values_to = "DHW") %>% 
  filter(DHW >= 4 & DHW < 8) %>% 
  group_by(`Data Type`) %>% 
  summarize(`moderate bleaching days` = n()) %>% 
  mutate(Site = "DAR Long", Reef = "Cocos Keeling Island")

freq_sev_DHW_DARL <- DARL_Sat_Combined %>% 
  select(Date, accum_DHW_12weeks, Data_Type) %>% 
  pivot_wider(names_from = Data_Type, values_from = accum_DHW_12weeks) %>% 
  na.omit() %>% 
  pivot_longer(cols = c(CCI, NOAA, GCM), names_to = "Data Type", values_to = "DHW") %>% 
  filter(DHW >= 8) %>% 
  group_by(`Data Type`) %>% 
  summarize(`severe bleaching days` = n()) %>% 
  mutate(Site = "DAR Long", Reef = "Cocos Keeling Island")

#SCOTT_RPO_1
freq_mod_DHW_SCOTT_RPO_1 <- SCOTT_RPO_1_Sat_Combined %>% 
  select(Date, accum_DHW_12weeks, Data_Type) %>% 
  pivot_wider(names_from = Data_Type, values_from = accum_DHW_12weeks) %>% 
  na.omit() %>% 
  pivot_longer(cols = c(CCI, NOAA, GCM), names_to = "Data Type", values_to = "DHW") %>% 
  filter(DHW >= 4 & DHW < 8) %>% 
  group_by(`Data Type`) %>% 
  summarize(`moderate bleaching days` = n()) %>% 
  mutate(Site = "SCOTT_RPO_1", Reef = "Scott Reef")

freq_sev_DHW_SCOTT_RPO_1 <- SCOTT_RPO_1_Sat_Combined %>% 
  select(Date, accum_DHW_12weeks, Data_Type) %>% 
  pivot_wider(names_from = Data_Type, values_from = accum_DHW_12weeks) %>% 
  na.omit() %>% 
  pivot_longer(cols = c(CCI, NOAA, GCM), names_to = "Data Type", values_to = "DHW") %>% 
  filter(DHW >= 8) %>% 
  group_by(`Data Type`) %>% 
  summarize(`severe bleaching days` = n()) %>% 
  mutate(Site = "SCOTT_RPO_1", Reef = "Scott Reef")

#SCOTTSL1
freq_mod_DHW_SCOTTSL1 <- SCOTTSL1_Sat_Combined %>% 
  select(Date, accum_DHW_12weeks, Data_Type) %>% 
  pivot_wider(names_from = Data_Type, values_from = accum_DHW_12weeks) %>% 
  na.omit() %>% 
  pivot_longer(cols = c(CCI, NOAA, GCM), names_to = "Data Type", values_to = "DHW") %>% 
  filter(DHW >= 4 & DHW < 8) %>% 
  group_by(`Data Type`) %>% 
  summarize(`moderate bleaching days` = n()) %>% 
  mutate(Site = "SCOTTSL1", Reef = "Scott Reef")

freq_sev_DHW_SCOTTSL1 <- SCOTTSL1_Sat_Combined %>% 
  select(Date, accum_DHW_12weeks, Data_Type) %>% 
  pivot_wider(names_from = Data_Type, values_from = accum_DHW_12weeks) %>% 
  na.omit() %>% 
  pivot_longer(cols = c(CCI, NOAA, GCM), names_to = "Data Type", values_to = "DHW") %>% 
  filter(DHW >= 8) %>% 
  group_by(`Data Type`) %>% 
  summarize(`severe bleaching days` = n()) %>% 
  mutate(Site = "SCOTTSL1", Reef = "Scott Reef")

#BRS07
freq_mod_DHW_BRS07 <- BRS07_Sat_Combined %>% 
  select(Date, accum_DHW_12weeks, Data_Type) %>% 
  pivot_wider(names_from = Data_Type, values_from = accum_DHW_12weeks) %>% 
  na.omit() %>% 
  pivot_longer(cols = c(CCI, NOAA, GCM), names_to = "Data Type", values_to = "DHW") %>% 
  filter(DHW >= 4 & DHW < 8) %>% 
  group_by(`Data Type`) %>% 
  summarize(`moderate bleaching days` = n()) %>% 
  mutate(Site = "BRS07", Reef = "Browse Island")

freq_sev_DHW_BRS07 <- BRS07_Sat_Combined %>% 
  select(Date, accum_DHW_12weeks, Data_Type) %>% 
  pivot_wider(names_from = Data_Type, values_from = accum_DHW_12weeks) %>% 
  na.omit() %>% 
  pivot_longer(cols = c(CCI, NOAA, GCM), names_to = "Data Type", values_to = "DHW") %>% 
  filter(DHW >= 8) %>% 
  group_by(`Data Type`) %>% 
  summarize(`severe bleaching days` = n()) %>% 
  mutate(Site = "BRS07", Reef = "Browse Island")

#08BND and 13BND
freq_mod_DHW_Bundegi <- Bundegi_Sat_Combined %>% 
  select(Date, accum_DHW_12weeks, Data_Type) %>% 
  pivot_wider(names_from = Data_Type, values_from = accum_DHW_12weeks) %>% 
  na.omit() %>% 
  pivot_longer(cols = c(CCI, NOAA, GCM), names_to = "Data Type", values_to = "DHW") %>% 
  filter(DHW >= 4 & DHW < 8) %>% 
  group_by(`Data Type`) %>% 
  summarize(`moderate bleaching days` = n()) %>% 
  mutate(Site = "08BND and 13BND", Reef = "Ningaloo Reef")

freq_sev_DHW_Bundegi <- Bundegi_Sat_Combined %>% 
  select(Date, accum_DHW_12weeks, Data_Type) %>% 
  pivot_wider(names_from = Data_Type, values_from = accum_DHW_12weeks) %>% 
  na.omit() %>% 
  pivot_longer(cols = c(CCI, NOAA, GCM), names_to = "Data Type", values_to = "DHW") %>% 
  filter(DHW >= 8) %>% 
  group_by(`Data Type`) %>% 
  summarize(`severe bleaching days` = n()) %>% 
  mutate(Site = "08BND and 13BND", Reef = "Ningaloo Reef")

#08TNT and 13TNT
freq_mod_DHW_Tantabiddi <- Tantabiddi_Sat_Combined %>% 
  select(Date, accum_DHW_12weeks, Data_Type) %>% 
  pivot_wider(names_from = Data_Type, values_from = accum_DHW_12weeks) %>% 
  na.omit() %>% 
  pivot_longer(cols = c(CCI, NOAA, GCM), names_to = "Data Type", values_to = "DHW") %>% 
  filter(DHW >= 4 & DHW < 8) %>% 
  group_by(`Data Type`) %>% 
  summarize(`moderate bleaching days` = n()) %>% 
  mutate(Site = "08TNT and 13TNT", Reef = "Ningaloo Reef")

freq_sev_DHW_Tantabiddi <- Tantabiddi_Sat_Combined %>% 
  select(Date, accum_DHW_12weeks, Data_Type) %>% 
  pivot_wider(names_from = Data_Type, values_from = accum_DHW_12weeks) %>% 
  na.omit() %>% 
  pivot_longer(cols = c(CCI, NOAA, GCM), names_to = "Data Type", values_to = "DHW") %>% 
  filter(DHW >= 8) %>% 
  group_by(`Data Type`) %>% 
  summarize(`severe bleaching days` = n()) %>% 
  mutate(Site = "08TNT and 13TNT", Reef = "Ningaloo Reef")

#HAB10A
freq_mod_DHW_HAB10A <- HAB10A_Sat_Combined %>% 
  select(Date, accum_DHW_12weeks, Data_Type) %>% 
  pivot_wider(names_from = Data_Type, values_from = accum_DHW_12weeks) %>% 
  na.omit() %>% 
  pivot_longer(cols = c(CCI, NOAA, GCM), names_to = "Data Type", values_to = "DHW") %>% 
  filter(DHW >= 4 & DHW < 8) %>% 
  group_by(`Data Type`) %>% 
  summarize(`moderate bleaching days` = n()) %>% 
  mutate(Site = "HAB10A", Reef = "Houtman Abrolhos")

freq_sev_DHW_HAB10A <- HAB10A_Sat_Combined %>% 
  select(Date, accum_DHW_12weeks, Data_Type) %>% 
  pivot_wider(names_from = Data_Type, values_from = accum_DHW_12weeks) %>% 
  na.omit() %>% 
  pivot_longer(cols = c(CCI, NOAA, GCM), names_to = "Data Type", values_to = "DHW") %>% 
  filter(DHW >= 8) %>% 
  group_by(`Data Type`) %>% 
  summarize(`severe bleaching days` = n()) %>% 
  mutate(Site = "HAB10A", Reef = "Houtman Abrolhos")

#HAB05B
freq_mod_DHW_HAB05B <- HAB05B_Sat_Combined %>% 
  select(Date, accum_DHW_12weeks, Data_Type) %>% 
  pivot_wider(names_from = Data_Type, values_from = accum_DHW_12weeks) %>% 
  na.omit() %>% 
  pivot_longer(cols = c(CCI, NOAA, GCM), names_to = "Data Type", values_to = "DHW") %>% 
  filter(DHW >= 4 & DHW < 8) %>% 
  group_by(`Data Type`) %>% 
  summarize(`moderate bleaching days` = n()) %>% 
  mutate(Site = "HAB05B", Reef = "Houtman Abrolhos")

freq_sev_DHW_HAB05B <- HAB05B_Sat_Combined %>% 
  select(Date, accum_DHW_12weeks, Data_Type) %>% 
  pivot_wider(names_from = Data_Type, values_from = accum_DHW_12weeks) %>% 
  na.omit() %>% 
  pivot_longer(cols = c(CCI, NOAA, GCM), names_to = "Data Type", values_to = "DHW") %>% 
  filter(DHW >= 8) %>% 
  group_by(`Data Type`) %>% 
  summarize(`severe bleaching days` = n()) %>% 
  mutate(Site = "HAB05B", Reef = "Houtman Abrolhos")

#summary
freq_mod_DHW_combined <- rbind(freq_mod_DHW_DARL, freq_mod_DHW_SCOTT_RPO_1, freq_mod_DHW_SCOTTSL1, freq_mod_DHW_BRS07, freq_mod_DHW_Bundegi, freq_mod_DHW_Tantabiddi, freq_mod_DHW_HAB10A, freq_mod_DHW_HAB05B) %>% 
  relocate(c(4, 3))

freq_sev_DHW_combined <- rbind(freq_sev_DHW_DARL, freq_sev_DHW_SCOTT_RPO_1, freq_sev_DHW_SCOTTSL1, freq_sev_DHW_BRS07, freq_sev_DHW_Bundegi, freq_sev_DHW_Tantabiddi, freq_sev_DHW_HAB10A, freq_sev_DHW_HAB05B) %>% 
  relocate(c(4, 3))

```


