---
title: "Coral Core Calibration and Frequency Analysis"
author: "Vanessa Hui Fen Neo"
date: "`r lubridate::today()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
```

```{r Loading_Packages, include = FALSE, message = FALSE}
library(tidyverse)
library(lubridate)
library(patchwork)
library(tsibble)
library(TSclust)
library(mgcv)
library(broom)
library(kableExtra)
library(equatiomatic)
```


```{r Browse_Island, message = FALSE, include = FALSE}

##BRS05

Browse_05_CCI <- read_csv(here::here("data_raw", "CCI_BRS05.csv")) 
Browse_05_CCI <- Browse_05_CCI %>% 
  mutate(sst = as.numeric(str_sub(Browse_05_CCI$`mean temperature deg C`, 3, 13))) %>%  #remove punctuation [[ and ]] from temperature data
  select(-`mean temperature deg C`) %>%  #remove column with [[ and ]]
  mutate(data_type = "CCI") %>%  #prepare data for binding with other data types
  rename(date = daily_date) %>%  #prepare data for binding with other data types
  select(data_type, date, sst) %>% #select only useful columns 
  as_tsibble(index = date) # convert them to tsibble

Browse_05_CCore <- read_csv(here::here("data_raw", "CCore_BRS05_BRS07_Year_Month.csv"), n_max = 740) %>% 
  mutate(data_type = "Coral Core") %>% #prepare data for binding with other data types
  mutate(date = str_c(year, month, sep = "-")) %>% #stringing year and month
  mutate(date = yearmonth(date)) %>% #converting date column fr chr to date format
  select(data_type, date, `BRS05 Sr/Ca [mmol/mol]`) %>%  #select only useful columns 
  as_tsibble(index = date) # convert them to tsibble 

Browse_05_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_SCOTTSS1.csv")) %>% 
  rename(sst = mean_SST) %>% #prepare data for binding with other data types
  mutate(data_type = "Logger") %>% #prepare data for binding with other data types
  select(data_type, date, sst)  %>% #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

Browse_05_NOAA <- read_csv(here::here("data_raw", "NOAA_BRS05_SST.csv")) %>% 
  mutate(data_type = "NOAA") %>%  #prepare data for binding with other data types
  select(-date) %>% #remove monthly date column
  rename(date = Date) %>% #rename daily date column to prepare for binding with other data types
  select(data_type, date, sst) %>%  #select only useful columns
  as_tsibble(index = date) # convert them to tsibble


dat <- as_tibble(Browse_05_CCI) %>% 
  add_row(as_tibble(Browse_05_NOAA)) %>% 
  # only few data points when logger data is included: add_row(as_tibble(Browse_05_Logger)) %>% 
  add_row(as_tibble(Browse_05_CCore) %>% 
            rename(sst = `BRS05 Sr/Ca [mmol/mol]`)) %>% 
  mutate(data_type = 
           case_when( data_type == "CCI" ~ "browse_CCI",
                      data_type == "Logger" ~ "browse_Logger", 
                      data_type == "NOAA" ~ "browse_NOAA",
                      data_type == "Coral Core" ~ "browse_coral_core",
                      TRUE ~ data_type))

BRS05_joint <- dat %>% 
  pivot_wider(names_from = data_type, values_from = sst) %>% 
  drop_na() %>% 
  mutate(Site = "BRS05")

#GGally::ggpairs(dat_joint)
## coral core is slightly more aligned with CCI than NOAA
ggplot(BRS05_joint, aes(x = browse_coral_core, y = browse_NOAA)) + 
  geom_point() + 
  geom_smooth(method = "gam") %>% 
  labs(title = "Sea Surface Temperature at BRS05", x = "Coral Core", y = "NOAA")
# decreasing trend with curvature. 
# gam1 <- gam(browse_NOAA ~ s(browse_coral_core, bs = "cs"), data = dat_joint, method = "REML")
# plot(gam1)
# summary(gam1)
# edf = 3.841 so linear + quadratic should give a good approx to the trend

# lm1 <- lm(browse_NOAA ~ 1 + browse_coral_core + I(browse_coral_core^2), 
         # data = dat_joint)
# summary(lm1)

# p-value for quadratic is 0.175
# use linear model

NOAA_BRS05 <- lm(browse_NOAA ~ 1 + browse_coral_core, 
          data = BRS05_joint)
# summary(lm1)

# repeat for CCI 
ggplot(BRS05_joint, aes(x = browse_coral_core, y = browse_CCI)) + 
  geom_point() + 
  geom_smooth(method = "gam") %>% 
  labs(title = "Sea Surface Temperature at BRS05", x = "Coral Core", y = "CCI")
# linear decreasing trend with a slight curvature. 
# gam2 <- gam(browse_CCI ~ s(browse_coral_core, bs = "cs"), data = dat_joint, method = "REML")
# plot(gam2)
# summary(gam2)
# edf = 3.727 so linear + quadratic should give a good approx to the trend

# lm2 <- lm(browse_CCI ~ 1 + browse_coral_core + I(browse_coral_core^2), 
        #  data = dat_joint)
# summary(lm2)

# p-value for quadratic is 0.204
# use linear model

CCI_BRS05 <- lm(browse_CCI ~ 1 + browse_coral_core, 
          data = BRS05_joint)
# summary(lm2)


modelsummary::modelsummary(list(NOAA_BRS05, CCI_BRS05))

##BRS07

Browse_07_CCI <- read_csv(here::here("data_raw", "CCI_BRS07.csv"))
Browse_07_CCI <- Browse_07_CCI %>% 
  mutate(sst = as.numeric(str_sub(Browse_07_CCI$`mean temperature deg C`, 3, 13))) %>%  #remove punctuation [[ and ]] from temperature data
  select(-`mean temperature deg C`) %>%  #remove column with [[ and ]]
  mutate(data_type = "CCI") %>%  #prepare data for binding with other data types
  rename(date = daily_date) %>%  #prepare data for binding with other data types
  select(data_type, date, sst) %>% #select only useful columns 
  as_tsibble(index = date) # convert them to tsibble

Browse_07_CCore <- read_csv(here::here("data_raw", "CCore_BRS05_BRS07_Year_Month.csv"), n_max = 740) %>% 
  mutate(data_type = "Coral Core") %>% #prepare data for binding with other data types
  mutate(date = str_c(year, month, sep = "-")) %>% #stringing year and month
  mutate(date = yearmonth(date)) %>% #converting date column fr chr to date format
  select(data_type, date, `BRS07 Sr/Ca [mmol/mol]`) %>%  #select only useful columns 
  as_tsibble(index = date) # convert them to tsibble 

Browse_07_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_SCOTTSS1.csv")) %>% 
  rename(sst = mean_SST) %>% #prepare data for binding with other data types
  mutate(data_type = "Logger") %>% #prepare data for binding with other data types
  select(data_type, date, sst)  %>% #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

Browse_07_NOAA <- read_csv(here::here("data_raw", "NOAA_BRS07_SST.csv")) %>% 
  mutate(data_type = "NOAA") %>%  #prepare data for binding with other data types
  select(-date) %>% #remove monthly date column
  rename(date = Date) %>% #rename daily date column to prepare for binding with other data types
  select(data_type, date, sst) %>%  #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

dat <- as_tibble(Browse_07_CCI) %>% 
  add_row(as_tibble(Browse_07_NOAA)) %>% 
  # only 9 points are available when including logger data: add_row(as_tibble(Browse_07_Logger)) %>% 
  add_row(as_tibble(Browse_07_CCore) %>% 
            rename(sst = `BRS07 Sr/Ca [mmol/mol]`)) %>% 
  mutate(data_type = 
           case_when( data_type == "CCI" ~ "browse_CCI",
                      data_type == "Logger" ~ "browse_Logger", 
                      data_type == "NOAA" ~ "browse_NOAA",
                      data_type == "Coral Core" ~ "browse_coral_core",
                      TRUE ~ data_type))

BRS07_joint <- dat %>% 
  pivot_wider(names_from = data_type, values_from = sst) %>% 
  drop_na() %>% 
  mutate(Site = "BRS07")

#GGally::ggpairs(dat_joint)
## coral core is slightly more aligned with CCI than NOAA 
ggplot(BRS07_joint, aes(x = browse_coral_core, y = browse_NOAA)) + 
  geom_point() + 
  geom_smooth(method = "gam") %>% 
  labs(title = "Sea Surface Temperature at BRS07", x = "Coral Core", y = "NOAA")
# linear decreasing trend with a slight curvature. 
# gam1 <- gam(browse_NOAA ~ s(browse_coral_core, bs = "cs"), data = dat_joint, method = "REML")
# plot(gam1)
# summary(gam1)
# edf = 3.039 so linear + quadratic should give a good approx to the trend

# lm1 <- lm(browse_NOAA ~ 1 + browse_coral_core + I(browse_coral_core^2), 
         # data = dat_joint)
# summary(lm1)

# p-value for quadratic is 0.146
# use linear model

NOAA_BRS07 <- lm(browse_NOAA ~ 1 + browse_coral_core, 
          data = BRS07_joint)
# summary(lm1)

# repeat for CCI 
ggplot(BRS07_joint, aes(x = browse_coral_core, y = browse_CCI)) + 
  geom_point() + 
  geom_smooth(method = "gam") %>% 
  labs(title = "Sea Surface Temperature at BRS07", x = "Coral Core", y = "CCI")
# linear decreasing trend with a slight curvature. 
# gam2 <- gam(browse_CCI ~ s(browse_coral_core, bs = "cs"), data = dat_joint, method = "REML")
# plot(gam2)
# summary(gam2)
# edf = 3.166 so linear + quadratic should give a good approx to the trend

CCI_BRS07 <- lm(browse_CCI ~ 1 + browse_coral_core + I(browse_coral_core^2), 
          data = BRS07_joint)
# summary(lm2)

# p-value for quadratic is significant, keep quadratic model

modelsummary::modelsummary(list(NOAA_BRS07, CCI_BRS07))
```



```{r Cocos_Keeling_Island, message = FALSE, include = FALSE}
##DAR Long
DARL_CCI <- read_csv(here::here("data_raw", "CCI_DARL.csv"))
DARL_CCI <- DARL_CCI %>% 
  mutate(sst = as.numeric(str_sub(DARL_CCI$`mean temperature deg C`, 3, 13))) %>%  #remove punctuation [[ and ]] from temperature data
  select(-`mean temperature deg C`) %>%  #remove column with [[ and ]]
  mutate(data_type = "CCI") %>%  #prepare data for binding with other data types
  rename(date = daily_date) %>%  #prepare data for binding with other data types
  select(data_type, date, sst) %>%  #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

DARL_CCore <- read_csv(here::here("data_raw", "CCore_DAR_Long_Year_Month.csv"))
DARL_CCore <- DARL_CCore %>% 
  mutate(data_type = "Coral Core") %>% #prepare data for binding with other data types
  mutate(date = str_c(year, month, sep = "-")) %>% 
  mutate(date = ym(date)) %>% 
  select(data_type, date, `Sr/Ca`) %>%     #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

DARL_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_100THSITE.csv"))
DARL_Logger <- DARL_Logger %>% 
  rename(sst = mean_SST) %>% #prepare data for binding with other data types
  mutate(data_type = "Logger") %>% #prepare data for binding with other data types
  select(data_type, date, sst) %>%   #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

DARL_NOAA <- read_csv(here::here("data_raw", "NOAA_DAR_Long_SST.csv"))
DARL_NOAA <- DARL_NOAA %>% 
  mutate(data_type = "NOAA") %>%  #prepare data for binding with other data types
  select(-date) %>% #remove monthly date column
  rename(date = Date) %>% #rename daily date column to prepare for binding with other data types
  select(data_type, date, sst) %>%  #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

dat <- as_tibble(DARL_CCI) %>% 
  add_row(as_tibble(DARL_NOAA)) %>% 
  #less than 10 points if logger data is included : add_row(as_tibble(DARL_Logger)) %>% 
  add_row(as_tibble(DARL_CCore) %>% 
            rename(sst = `Sr/Ca`)) %>% 
  mutate(data_type = 
           case_when( data_type == "CCI" ~ "Cocos_CCI",
                      data_type == "Logger" ~ "Cocos_Logger", 
                      data_type == "NOAA" ~ "Cocos_NOAA",
                      data_type == "Coral Core" ~ "Cocos_coral_core",
                      TRUE ~ data_type))

DARL_joint <- dat %>% 
  pivot_wider(names_from = data_type, values_from = sst) %>% 
  drop_na() %>% 
  mutate(Site = "DARL")

#GGally::ggpairs(dat_joint)
## coral core is slightly more aligned with CCI than NOAA 
ggplot(DARL_joint, aes(x = Cocos_coral_core, y = Cocos_NOAA)) + 
  geom_point() + 
  geom_smooth(method = "gam") %>% 
  labs(title = "Sea Surface Temperature at DAR Long", x = "Coral Core", y = "NOAA")

# linear decreasing trend

# gam1 <- gam(Cocos_NOAA ~ s(Cocos_coral_core, bs = "cs"), data = dat_joint, method = "REML")
# plot(gam1)
# summary(gam1)
# edf = 1.881 so linear + quadratic should give a good approx to the trend

# lm1 <- lm(Cocos_NOAA ~ 1 + Cocos_coral_core + I(Cocos_coral_core^2), 
         # data = dat_joint)
# summary(lm1)

# p-value for quadratic is 0.322
# use linear model

NOAA_DARL <- lm(Cocos_NOAA ~ 1 + Cocos_coral_core, 
          data = DARL_joint)
# summary(lm1)

# repeat for CCI 
ggplot(DARL_joint, aes(x = Cocos_coral_core, y = Cocos_CCI)) + 
  geom_point() + 
  geom_smooth(method = "gam") %>% 
  labs(title = "Sea Surface Temperature at DAR Long", x = "Coral Core", y = "CCI")
# linear decreasing trend 
# gam2 <- gam(Cocos_CCI ~ s(Cocos_coral_core, bs = "cs"), data = dat_joint, method = "REML")
# plot(gam2)
# summary(gam2)
# edf = 1.969 so linear + quadratic should give a good approx to the trend

# lm2 <- lm(Cocos_CCI ~ 1 + Cocos_coral_core + I(Cocos_coral_core^2), 
         # data = dat_joint)
# summary(lm2)

# p-value for quadratic is 0.506
# use linear model

CCI_DARL <- lm(Cocos_CCI ~ 1 + Cocos_coral_core, 
          data = DARL_joint)
# summary(lm2)

modelsummary::modelsummary(list(NOAA_DARL, CCI_DARL))

##DAR3
DAR3_CCI <- read_csv(here::here("data_raw", "CCI_DAR3.csv"))
DAR3_CCI <- DAR3_CCI %>% 
  mutate(sst = as.numeric(str_sub(DAR3_CCI$`mean temperature deg C`, 3, 13))) %>%  #remove punctuation [[ and ]] from temperature data
  select(-`mean temperature deg C`) %>%  #remove column with [[ and ]]
  mutate(data_type = "CCI") %>%  #prepare data for binding with other data types
  rename(date = daily_date) %>%  #prepare data for binding with other data types
  select(data_type, date, sst) %>%  #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

DAR3_CCore <- read_csv(here::here("data_raw", "CCore_DAR3_Year_Month.csv"))
DAR3_CCore <- DAR3_CCore %>% 
  mutate(data_type = "Coral Core") %>% #prepare data for binding with other data types
  mutate(date = str_c(year, month, sep = "-")) %>% 
  mutate(date = ym(date)) %>% 
  select(data_type, date, `Sr/Ca`) %>%     #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

DAR3_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_100THSITE.csv"))
DAR3_Logger <- DAR3_Logger %>% 
  rename(sst = mean_SST) %>% #prepare data for binding with other data types
  mutate(data_type = "Logger") %>% #prepare data for binding with other data types
  select(data_type, date, sst) %>%   #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

DAR3_NOAA <- read_csv(here::here("data_raw", "NOAA_DAR3_SST.csv"))
DAR3_NOAA <- DAR3_NOAA %>% 
  mutate(data_type = "NOAA") %>%  #prepare data for binding with other data types
  select(-date) %>% #remove monthly date column
  rename(date = Date) %>% #rename daily date column to prepare for binding with other data types
  select(data_type, date, sst) %>%  #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

dat <- as_tibble(DAR3_CCI) %>% 
  add_row(as_tibble(DAR3_NOAA)) %>% 
  #less than 10 points if logger data is included : add_row(as_tibble(DAR3_Logger)) %>% 
  add_row(as_tibble(DAR3_CCore) %>% 
            rename(sst = `Sr/Ca`)) %>% 
  mutate(data_type = 
           case_when( data_type == "CCI" ~ "Cocos_CCI",
                      data_type == "Logger" ~ "Cocos_Logger", 
                      data_type == "NOAA" ~ "Cocos_NOAA",
                      data_type == "Coral Core" ~ "Cocos_coral_core",
                      TRUE ~ data_type))

DAR3_joint <- dat %>% 
  pivot_wider(names_from = data_type, values_from = sst) %>% 
  drop_na() %>% 
  mutate(Site = "DAR3")

#GGally::ggpairs(dat_joint)
## coral core is slightly more align with NOAA over CCI 
ggplot(DAR3_joint, aes(x = Cocos_coral_core, y = Cocos_NOAA)) + 
  geom_point() + 
  geom_smooth(method = "gam") %>% 
  labs(title = "Sea Surface Temperature at DAR3", x = "Coral Core", y = "NOAA")
# linear decreasing trend with a slight curvature. 
# gam1 <- gam(Cocos_NOAA ~ s(Cocos_coral_core, bs = "cs"), data = dat_joint, method = "REML")
# plot(gam1)
# summary(gam1)
# edf = 1.881 so linear + quadratic should give a good approx to the trend

# lm1 <- lm(Cocos_NOAA ~ 1 + Cocos_coral_core + I(Cocos_coral_core^2), 
        #  data = dat_joint)
# summary(lm1)

# p-value for quadratic is 0.322
# use linear model

NOAA_DAR3 <- lm(Cocos_NOAA ~ 1 + Cocos_coral_core, 
          data = DAR3_joint)
# summary(lm1)

# repeat for CCI 
ggplot(DAR3_joint, aes(x = Cocos_coral_core, y = Cocos_CCI)) + 
  geom_point() + 
  geom_smooth(method = "gam") %>% 
  labs(title = "Sea Surface Temperature at DAR3", x = "Coral Core", y = "CCI")
# linear decreasing trend with a slight curvature. 
# gam2 <- gam(Cocos_CCI ~ s(Cocos_coral_core, bs = "cs"), data = dat_joint, method = "REML")
# plot(gam2)
# summary(gam2)
# edf = 1.969 so linear + quadratic should give a good approx to the trend

# lm2 <- lm(Cocos_CCI ~ 1 + Cocos_coral_core + I(Cocos_coral_core^2), 
#          data = dat_joint)
# summary(lm2)

# p-value for quadratic is 0.506
# use linear model

CCI_DAR3 <- lm(Cocos_CCI ~ 1 + Cocos_coral_core, 
          data = DAR3_joint)
# summary(lm2)

modelsummary::modelsummary(list(NOAA_DAR3, CCI_DAR3))


```



```{r Ningaloo_Reef, message = FALSE, include = FALSE}
##Tantabiddi 13TNT
Ningaloo_13TNT_CCI <- read_csv(here::here("data_raw", "CCI_Tantabiddi.csv"))
Ningaloo_13TNT_CCI <- Ningaloo_13TNT_CCI %>% 
  mutate(sst = as.numeric(str_sub(Ningaloo_13TNT_CCI$`mean temperature deg C`, 3, 13))) %>%  #remove punctuation [[ and ]] from temperature data
  select(-`mean temperature deg C`) %>%  #remove column with [[ and ]]
  mutate(data_type = "CCI") %>%  #prepare data for binding with other data types
  rename(date = daily_date) %>%  #prepare data for binding with other data types
  select(data_type, date, sst) %>%  #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

Ningaloo_13TNT_CCore <- read_csv(here::here("data_raw", "CCore_Ningaloo_13TNT_Year_Month.csv"))
Ningaloo_13TNT_CCore <- Ningaloo_13TNT_CCore %>% 
  mutate(data_type = "Coral Core") %>% #prepare data for binding with other data types
  mutate(date = as_date(date)) %>% 
  select(data_type, date, `Sr/Ca`) %>%     #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

Ningaloo_13TNT_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_TANDFL1.csv"))
Ningaloo_13TNT_Logger <- Ningaloo_13TNT_Logger %>% 
  rename(sst = mean_SST) %>% #prepare data for binding with other data types
  mutate(data_type = "Logger") %>% #prepare data for binding with other data types
  select(data_type, date, sst) %>%   #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

Ningaloo_13TNT_NOAA <- read_csv(here::here("data_raw", "NOAA_Tantabiddi_13TNT_SST.csv"))
Ningaloo_13TNT_NOAA <- Ningaloo_13TNT_NOAA %>% 
  mutate(data_type = "NOAA") %>%  #prepare data for binding with other data types
  select(-date) %>% #remove monthly date column
  rename(date = Date) %>% #rename daily date column to prepare for binding with other data types
  select(data_type, date, sst) %>%  #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

dat <- as_tibble(Ningaloo_13TNT_CCI) %>% 
  add_row(as_tibble(Ningaloo_13TNT_NOAA)) %>% 
  # only 13 data points available if logger data is included in analysis: add_row(as_tibble(Ningaloo_13TNT_Logger)) %>% 
  add_row(as_tibble(Ningaloo_13TNT_CCore) %>% 
            rename(sst = `Sr/Ca`)) %>% 
  mutate(data_type = 
           case_when( data_type == "CCI" ~ "ningaloo_CCI",
                      # only 13 data points if logger data is included: data_type == "Logger" ~ "ningaloo_Logger", 
                      data_type == "NOAA" ~ "ningaloo_NOAA",
                      data_type == "Coral Core" ~ "ningaloo_coral_core",
                      TRUE ~ data_type))

Tantabiddi_13TNT_joint <- dat %>% 
  pivot_wider(names_from = data_type, values_from = sst) %>% 
  drop_na() %>% 
  mutate(Site = "13TNT")

#GGally::ggpairs(dat_joint)
## coral core is slightly more aligned with NOAA than CCI 
ggplot(Tantabiddi_13TNT_joint, aes(x = ningaloo_coral_core, y = ningaloo_NOAA)) + 
  geom_point() + 
  geom_smooth(method = "gam") %>% 
  labs(title = "Sea Surface Temperature at 13TNT", x = "Coral Core", y = "NOAA")
# linear decreasing trend with a slight curvature. 
# gam1 <- gam(ningaloo_NOAA ~ s(ningaloo_coral_core, bs = "cs"), data = dat_joint, method = "REML")
# plot(gam1)
# summary(gam1)
# edf = 2.677 so linear + quadratic should give a good approx to the trend

NOAA_Tantabiddi_13TNT <- lm(ningaloo_NOAA ~ 1 + ningaloo_coral_core + I(ningaloo_coral_core^2), 
          data = Tantabiddi_13TNT_joint)
# summary(lm1)

# repeat for CCI 
ggplot(Tantabiddi_13TNT_joint, aes(x = ningaloo_coral_core, y = ningaloo_CCI)) + 
  geom_point() + 
  geom_smooth(method = "gam") %>% 
  labs(title = "Sea Surface Temperature at 13TNT", x = "Coral Core", y = "CCI")
# linear decreasing trend with a slight curvature. 
# gam2 <- gam(ningaloo_CCI ~ s(ningaloo_coral_core, bs = "cs"), data = dat_joint, method = "REML")
# plot(gam2)
# summary(gam2)
# edf = 2.724 so linear + quadratic should give a good approx to the trend

CCI_Tantabiddi_13TNT <- lm(ningaloo_CCI ~ 1 + ningaloo_coral_core + I(ningaloo_coral_core^2), 
          data = Tantabiddi_13TNT_joint)
# summary(lm2)

modelsummary::modelsummary(list(NOAA_Tantabiddi_13TNT, CCI_Tantabiddi_13TNT))


##Tantabiddi 08TNT
Ningaloo_08TNT_CCI <- read_csv(here::here("data_raw", "CCI_Tantabiddi.csv"))
Ningaloo_08TNT_CCI <- Ningaloo_08TNT_CCI %>% 
  mutate(sst = as.numeric(str_sub(Ningaloo_08TNT_CCI$`mean temperature deg C`, 3, 13))) %>%  #remove punctuation [[ and ]] from temperature data
  select(-`mean temperature deg C`) %>%  #remove column with [[ and ]]
  mutate(data_type = "CCI") %>%  #prepare data for binding with other data types
  rename(date = daily_date) %>%  #prepare data for binding with other data types
  select(data_type, date, sst) %>%  #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

Ningaloo_08TNT_CCore <- read_csv(here::here("data_raw", "CCore_Ningaloo_08TNT_Year_Month.csv"))
Ningaloo_08TNT_CCore <- Ningaloo_08TNT_CCore %>% 
  mutate(data_type = "Coral Core") %>% #prepare data for binding with other data types
  mutate(date = as_date(date)) %>% 
  select(data_type, date, `Sr/Ca`) %>%     #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

Ningaloo_08TNT_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_TANDFL1.csv"))
Ningaloo_08TNT_Logger <- Ningaloo_08TNT_Logger %>% 
  rename(sst = mean_SST) %>% #prepare data for binding with other data types
  mutate(data_type = "Logger") %>% #prepare data for binding with other data types
  select(data_type, date, sst) %>%   #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

Ningaloo_08TNT_NOAA <- read_csv(here::here("data_raw", "NOAA_Tantabiddi_08TNT_SST.csv"))
Ningaloo_08TNT_NOAA <- Ningaloo_08TNT_NOAA %>% 
  mutate(data_type = "NOAA") %>%  #prepare data for binding with other data types
  select(-date) %>% #remove monthly date column
  rename(date = Date) %>% #rename daily date column to prepare for binding with other data types
  select(data_type, date, sst) %>%  #select only useful columns
  as_tsibble(index = date) # convert them to tsibble


dat <- as_tibble(Ningaloo_08TNT_CCI) %>% 
  add_row(as_tibble(Ningaloo_08TNT_NOAA)) %>% 
  # no values if logger data is added here: add_row(as_tibble(Ningaloo_08TNT_Logger)) %>% 
  add_row(as_tibble(Ningaloo_08TNT_CCore) %>% 
            rename(sst = `Sr/Ca`)) %>% 
  mutate(data_type = 
           case_when( data_type == "CCI" ~ "ningaloo_CCI",
                      data_type == "Logger" ~ "ningaloo_Logger", 
                      data_type == "NOAA" ~ "ningaloo_NOAA",
                      data_type == "Coral Core" ~ "ningaloo_coral_core",
                      TRUE ~ data_type))

Tantabiddi_08TNT_joint <- dat %>% 
  pivot_wider(names_from = data_type, values_from = sst) %>% 
  drop_na() %>% 
  mutate(Site = "08TNT")

#GGally::ggpairs(dat_joint)
## coral core is slightly more aligned with NOAA over CCI 
ggplot(Tantabiddi_08TNT_joint, aes(x = ningaloo_coral_core, y = ningaloo_NOAA)) + 
  geom_point() + 
  geom_smooth(method = "gam") %>% 
  labs(title = "Sea Surface Temperature at 08TNT", x = "Coral Core", y = "NOAA")
# linear decreasing trend 
# gam1 <- gam(ningaloo_NOAA ~ s(ningaloo_coral_core, bs = "cs"), data = dat_joint, method = "REML")
# plot(gam1)
# summary(gam1)
# edf = 2.477 so linear + quadratic should give a good approx to the trend

# lm1 <- lm(ningaloo_NOAA ~ 1 + ningaloo_coral_core + I(ningaloo_coral_core^2), data = dat_joint)
# summary(lm1)

# p-value for quadratic is 0.564
# use linear model instead

NOAA_Tantabiddi_08TNT <- lm(ningaloo_NOAA ~ 1 + ningaloo_coral_core, 
          data = Tantabiddi_08TNT_joint)
# summary(lm1)

# repeat for CCI 
ggplot(Tantabiddi_08TNT_joint, aes(x = ningaloo_coral_core, y = ningaloo_CCI)) + 
  geom_point() + 
  geom_smooth(method = "gam") %>% 
  labs(title = "Sea Surface Temperature at 08TNT", x = "Coral Core", y = "CCI")
# linear decreasing trend 
# gam2 <- gam(ningaloo_CCI ~ s(ningaloo_coral_core, bs = "cs"), data = dat_joint, method = "REML")
# plot(gam2)
# summary(gam2)
# edf = 2.391 so linear + quadratic should give a good approx to the trend

# lm2 <- lm(ningaloo_CCI ~ 1 + ningaloo_coral_core + I(ningaloo_coral_core^2), data = dat_joint)
# summary(lm2)

# p-value for quadratic is 0.329
# use linear model instead

CCI_Tantabiddi_08TNT <- lm(ningaloo_CCI ~ 1 + ningaloo_coral_core, 
          data = Tantabiddi_08TNT_joint)
# summary(lm2)

modelsummary::modelsummary(list(NOAA_Tantabiddi_08TNT, CCI_Tantabiddi_08TNT))


##Bundegi 13BND
Ningaloo_13BND_CCI <- read_csv(here::here("data_raw", "CCI_Bundegi.csv"))
Ningaloo_13BND_CCI <- Ningaloo_13BND_CCI %>% 
  mutate(sst = as.numeric(str_sub(Ningaloo_13BND_CCI$`mean temperature deg C`, 3, 13))) %>%  #remove punctuation [[ and ]] from temperature data
  select(-`mean temperature deg C`) %>%  #remove column with [[ and ]]
  mutate(data_type = "CCI") %>%  #prepare data for binding with other data types
  rename(date = daily_date) %>%  #prepare data for binding with other data types
  select(data_type, date, sst) %>%  #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

Ningaloo_13BND_CCore <- read_csv(here::here("data_raw", "CCore_Ningaloo_13BND_Year_Month.csv"))
Ningaloo_13BND_CCore <- Ningaloo_13BND_CCore %>% 
  mutate(data_type = "Coral Core") %>% #prepare data for binding with other data types
  mutate(date = as_date(date)) %>% 
  select(data_type, date, `Sr/Ca`) %>%     #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

Ningaloo_13BND_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_BUNDFL1.csv"))
Ningaloo_13BND_Logger <- Ningaloo_13BND_Logger %>% 
  rename(sst = mean_SST) %>% #prepare data for binding with other data types
  mutate(data_type = "Logger") %>% #prepare data for binding with other data types
  select(data_type, date, sst) %>%   #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

Ningaloo_13BND_NOAA <- read_csv(here::here("data_raw", "NOAA_Bundegi_13BND_SST.csv"))
Ningaloo_13BND_NOAA <- Ningaloo_13BND_NOAA %>% 
  mutate(data_type = "NOAA") %>%  #prepare data for binding with other data types
  select(-date) %>% #remove monthly date column
  rename(date = Date) %>% #rename daily date column to prepare for binding with other data types
  select(data_type, date, sst) %>%  #select only useful columns
  as_tsibble(index = date) # convert them to tsibble


dat <- as_tibble(Ningaloo_13BND_CCI) %>% 
  add_row(as_tibble(Ningaloo_13BND_NOAA)) %>% 
  # only 10 observations when logger data is added : add_row(as_tibble(Ningaloo_13BND_Logger)) %>%
  add_row(as_tibble(Ningaloo_13BND_CCore) %>% 
            rename(sst = `Sr/Ca`)) %>% 
  mutate(data_type = 
           case_when( data_type == "CCI" ~ "ningaloo_CCI",
                      data_type == "Logger" ~ "ningaloo_Logger", 
                      data_type == "NOAA" ~ "ningaloo_NOAA",
                      data_type == "Coral Core" ~ "ningaloo_coral_core",
                      TRUE ~ data_type))

Bundegi_13BND_joint <- dat %>% 
  pivot_wider(names_from = data_type, values_from = sst) %>% 
  drop_na() %>% 
  mutate(Site = "13BND")

#GGally::ggpairs(dat_joint)
## coral core is much more aligned with NOAA over CCI 
ggplot(Bundegi_13BND_joint, aes(x = ningaloo_coral_core, y = ningaloo_NOAA)) + 
  geom_point() + 
  geom_smooth(method = "gam") %>% 
  labs(title = "Sea Surface Temperature at 13BND", x = "Coral Core", y = "NOAA")
# linear decreasing trend with a slight curvature for NOAA vs coral core. 
# gam1 <- gam(ningaloo_NOAA ~ s(ningaloo_coral_core, bs = "cs"), data = dat_joint, method = "REML")
# plot(gam1)
# summary(gam1)
# edf = 2.283 so linear + quadratic should give a good approx to the trend

# lm1 <- lm(ningaloo_NOAA ~ 1 + ningaloo_coral_core + I(ningaloo_coral_core^2), 
          # data = dat_joint)
# summary(lm1)

# p-value for quadratic is 0.195
# use linear model instead

NOAA_Bundegi_13BND <- lm(ningaloo_NOAA ~ 1 + ningaloo_coral_core, 
          data = Bundegi_13BND_joint)
# summary(lm1)

# repeat for CCI 
ggplot(Bundegi_13BND_joint, aes(x = ningaloo_coral_core, y = ningaloo_CCI)) + 
  geom_point() + 
  geom_smooth(method = "gam") %>% 
  labs(title = "Sea Surface Temperature at 13BND", x = "Coral Core", y = "CCI")
# linear decreasing trend 
# gam2 <- gam(ningaloo_CCI ~ s(ningaloo_coral_core, bs = "cs"), data = dat_joint, method = "REML")
# plot(gam2)
# summary(gam2)
# edf = 1.672 so linear + quadratic should give a good approx to the trend

# lm2 <- lm(ningaloo_CCI ~ 1 + ningaloo_coral_core + I(ningaloo_coral_core^2), 
         # data = dat_joint)
# summary(lm2)

# p-value for quadratic is 0.665
# use linear model instead

CCI_Bundegi_13BND <- lm(ningaloo_CCI ~ 1 + ningaloo_coral_core, 
          data = Bundegi_13BND_joint)
# summary(lm2)

modelsummary::modelsummary(list(NOAA_Bundegi_13BND, CCI_Bundegi_13BND))


##Bundegi 08BND
Ningaloo_08BND_CCI <- read_csv(here::here("data_raw", "CCI_Bundegi.csv"))
Ningaloo_08BND_CCI <- Ningaloo_08BND_CCI %>% 
  mutate(sst = as.numeric(str_sub(Ningaloo_08BND_CCI$`mean temperature deg C`, 3, 13))) %>%  #remove punctuation [[ and ]] from temperature data
  select(-`mean temperature deg C`) %>%  #remove column with [[ and ]]
  mutate(data_type = "CCI") %>%  #prepare data for binding with other data types
  rename(date = daily_date) %>%  #prepare data for binding with other data types
  select(data_type, date, sst) %>%  #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

Ningaloo_08BND_CCore <- read_csv(here::here("data_raw", "CCore_Ningaloo_08BND_Year_Month.csv"))
Ningaloo_08BND_CCore <- Ningaloo_08BND_CCore %>% 
  mutate(data_type = "Coral Core") %>% #prepare data for binding with other data types
  mutate(date = as_date(date)) %>% 
  select(data_type, date, `Sr/Ca`) %>%     #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

Ningaloo_08BND_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_BUNDFL1.csv"))
Ningaloo_08BND_Logger <- Ningaloo_08BND_Logger %>% 
  rename(sst = mean_SST) %>% #prepare data for binding with other data types
  mutate(data_type = "Logger") %>% #prepare data for binding with other data types
  select(data_type, date, sst) %>%   #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

Ningaloo_08BND_NOAA <- read_csv(here::here("data_raw", "NOAA_Bundegi_08BND_SST.csv"))
Ningaloo_08BND_NOAA <- Ningaloo_08BND_NOAA %>% 
  mutate(data_type = "NOAA") %>%  #prepare data for binding with other data types
  select(-date) %>% #remove monthly date column
  rename(date = Date) %>% #rename daily date column to prepare for binding with other data types
  select(data_type, date, sst) %>%  #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

dat <- as_tibble(Ningaloo_08BND_CCI) %>% 
  add_row(as_tibble(Ningaloo_08BND_NOAA)) %>% 
  #no values if logger data is included : add_row(as_tibble(Ningaloo_08BND_Logger)) %>% 
  add_row(as_tibble(Ningaloo_08BND_CCore) %>% 
            rename(sst = `Sr/Ca`)) %>% 
  mutate(data_type = 
           case_when( data_type == "CCI" ~ "ningaloo_CCI",
                      data_type == "Logger" ~ "ningaloo_Logger", 
                      data_type == "NOAA" ~ "ningaloo_NOAA",
                      data_type == "Coral Core" ~ "ningaloo_coral_core",
                      TRUE ~ data_type))

Bundegi_08BND_joint <- dat %>% 
  pivot_wider(names_from = data_type, values_from = sst) %>% 
  drop_na() %>% 
  mutate(Site = "08BND")

#GGally::ggpairs(dat_joint)
## coral core is more aligned with NOAA over CCI 
ggplot(Bundegi_08BND_joint, aes(x = ningaloo_coral_core, y = ningaloo_NOAA)) + 
  geom_point() + 
  geom_smooth(method = "gam") %>% 
  labs(title = "Sea Surface Temperature at 08BND", x = "Coral Core", y = "NOAA")
# linear decreasing trend with curvature. 
# gam1 <- gam(ningaloo_NOAA ~ s(ningaloo_coral_core, bs = "cs"), data = dat_joint, method = "REML")
# plot(gam1)
# summary(gam1)
# edf = 3.657 so linear + quadratic should give a good approx to the trend

NOAA_Bundegi_08BND <- lm(ningaloo_NOAA ~ 1 + ningaloo_coral_core + I(ningaloo_coral_core^2), 
          data = Bundegi_08BND_joint)
# summary(lm1)

# significant p-value for quadratic

# repeat for CCI 
ggplot(Bundegi_08BND_joint, aes(x = ningaloo_coral_core, y = ningaloo_CCI)) + 
  geom_point() + 
  geom_smooth(method = "gam") %>% 
  labs(title = "Sea Surface Temperature at 08BND", x = "Coral Core", y = "CCI")
# linear decreasing trend with curvature. 
# gam2 <- gam(ningaloo_CCI ~ s(ningaloo_coral_core, bs = "cs"), data = dat_joint, method = "REML")
# plot(gam2)
# summary(gam2)
# edf = 2.88 so linear + quadratic should give a good approx to the trend

CCI_Bundegi_08BND <- lm(ningaloo_CCI ~ 1 + ningaloo_coral_core + I(ningaloo_coral_core^2), 
          data = Bundegi_08BND_joint)
# summary(lm2)

# significant p-value for quadratic

modelsummary::modelsummary(list(NOAA_Bundegi_08BND, CCI_Bundegi_08BND))


##TNT

Ningaloo_TNT_CCI <- read_csv(here::here("data_raw", "CCI_TNT.csv"))
Ningaloo_TNT_CCI <- Ningaloo_TNT_CCI %>% 
  mutate(sst = as.numeric(str_sub(Ningaloo_TNT_CCI$`mean temperature deg C`, 3, 13))) %>%  #remove punctuation [[ and ]] from temperature data
  select(-`mean temperature deg C`) %>%  #remove column with [[ and ]]
  mutate(data_type = "CCI") %>%  #prepare data for binding with other data types
  rename(date = daily_date) %>%  #prepare data for binding with other data types
  select(data_type, date, sst) %>%  #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

Ningaloo_TNT_CCore <- read_csv(here::here("data_raw", "CCore_Ningaloo_TNT_Year_Month.csv"))
Ningaloo_TNT_CCore <- Ningaloo_TNT_CCore %>% 
  mutate(data_type = "Coral Core") %>% #prepare data for binding with other data types
  mutate(date = as_date(date)) %>% 
  select(data_type, date, `d18O`) %>%     #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

Ningaloo_TNT_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_TANDFL1.csv"))
Ningaloo_TNT_Logger <- Ningaloo_TNT_Logger %>% 
  rename(sst = mean_SST) %>% #prepare data for binding with other data types
  mutate(data_type = "Logger") %>% #prepare data for binding with other data types
  select(data_type, date, sst) %>%   #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

Ningaloo_TNT_NOAA <- read_csv(here::here("data_raw", "NOAA_TNT_SST.csv"))
Ningaloo_TNT_NOAA <- Ningaloo_TNT_NOAA %>% 
  mutate(data_type = "NOAA") %>%  #prepare data for binding with other data types
  select(-date) %>% #remove monthly date column
  rename(date = Date) %>% #rename daily date column to prepare for binding with other data types
  select(data_type, date, sst) %>%  #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

dat <- as_tibble(Ningaloo_TNT_CCI) %>% 
  add_row(as_tibble(Ningaloo_TNT_NOAA)) %>% 
  # no data is available when logger data is added: add_row(as_tibble(Ningaloo_TNT_Logger)) %>% 
  add_row(as_tibble(Ningaloo_TNT_CCore) %>% 
            rename(sst = `d18O`)) %>% 
  mutate(data_type = 
           case_when( data_type == "CCI" ~ "ningaloo_CCI",
                      data_type == "Logger" ~ "ningaloo_Logger", 
                      data_type == "NOAA" ~ "ningaloo_NOAA",
                      data_type == "Coral Core" ~ "ningaloo_coral_core",
                      TRUE ~ data_type))

TNT_joint <- dat %>% 
  pivot_wider(names_from = data_type, values_from = sst) %>% 
  drop_na() %>% 
  mutate(Site = "TNT")

#GGally::ggpairs(dat_joint)
## coral core is slightly more aligned with CCI than NOAA
ggplot(TNT_joint, aes(x = ningaloo_coral_core, y = ningaloo_NOAA)) + 
  geom_point() + 
  geom_smooth(method = "gam") %>% 
  labs(title = "Sea Surface Temperature at TNT", x = "Coral Core", y = "NOAA")
# linear decreasing trend with a slight curvature. 
# gam1 <- gam(ningaloo_NOAA ~ s(ningaloo_coral_core, bs = "cs"), data = dat_joint, method = "REML")
# plot(gam1)
# summary(gam1)
# edf = 3.138 so linear + quadratic should give a good approx to the trend

# lm1 <- lm(ningaloo_NOAA ~ 1 + ningaloo_coral_core + I(ningaloo_coral_core^2), 
          # data = dat_joint)
# summary(lm1)

# p-value for quadratic is 0.160
# use linear model instead

NOAA_TNT <- lm(ningaloo_NOAA ~ 1 + ningaloo_coral_core, 
          data = TNT_joint)
# summary(lm1)

# repeat for CCI 
ggplot(TNT_joint, aes(x = ningaloo_coral_core, y = ningaloo_CCI)) + 
  geom_point() + 
  geom_smooth(method = "gam") %>% 
  labs(title = "Sea Surface Temperature at TNT", x = "Coral Core", y = "CCI")
# linear decreasing trend with a slight curvature. 
# gam2 <- gam(ningaloo_CCI ~ s(ningaloo_coral_core, bs = "cs"), data = dat_joint, method = "REML")
# plot(gam2)
# summary(gam2)
# edf = 3.056 so linear + quadratic should give a good approx to the trend

# lm2 <- lm(ningaloo_CCI ~ 1 + ningaloo_coral_core + I(ningaloo_coral_core^2), 
#          data = dat_joint)
# summary(lm2)

# p-value for quadratic is 0.258
# use linear model instead

CCI_TNT <- lm(ningaloo_CCI ~ 1 + ningaloo_coral_core, 
          data = TNT_joint)
# summary(lm2)

modelsummary::modelsummary(list(NOAA_TNT, CCI_TNT))

##TNT07C
##Only annual coral core data

Ningaloo_TNT07C_CCI <- read_csv(here::here("data_raw", "CCI_TNT07C.csv"))
Ningaloo_TNT07C_CCI <- Ningaloo_TNT07C_CCI %>% 
  mutate(sst = as.numeric(str_sub(Ningaloo_TNT07C_CCI$`mean temperature deg C`, 3, 13))) %>%  #remove punctuation [[ and ]] from temperature data
  select(-`mean temperature deg C`) %>%  #remove column with [[ and ]]
  mutate(data_type = "CCI") %>%  #prepare data for binding with other data types
  rename(date = daily_date) %>%  #prepare data for binding with other data types
  select(data_type, date, sst) %>%  #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

Ningaloo_TNT07C_CCore <- read_csv(here::here("data_raw", "CCore_Ningaloo_TNT07C_year.csv"))

Ningaloo_TNT07C_CCore <- Ningaloo_TNT07C_CCore %>% 
  mutate(data_type = "Coral Core") %>% #prepare data for binding with other data types
  mutate(month = "01") %>% 
  mutate(date = str_c(year, month, sep = "-")) %>% 
  mutate(date = ym(date)) %>% 
  select(data_type, date, `Tantabiddi Sr/Ca`) %>% 
  as_tsibble(index = date) # convert them to tsibble

Ningaloo_TNT07C_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_TANTABIDDI_SL1.csv"))
Ningaloo_TNT07C_Logger <- Ningaloo_TNT07C_Logger %>% 
  rename(sst = mean_SST) %>% #prepare data for binding with other data types
  mutate(data_type = "Logger") %>% #prepare data for binding with other data types
  select(data_type, date, sst) %>%   #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

Ningaloo_TNT07C_NOAA <- read_csv(here::here("data_raw", "NOAA_TNT07C_SST.csv"))
Ningaloo_TNT07C_NOAA <- Ningaloo_TNT07C_NOAA %>% 
  mutate(data_type = "NOAA") %>%  #prepare data for binding with other data types
  select(-date) %>% #remove monthly date column
  rename(date = Date) %>% #rename daily date column to prepare for binding with other data types
  select(data_type, date, sst) %>%  #select only useful columns
  as_tsibble(index = date) # convert them to tsibble


dat <- as_tibble(Ningaloo_TNT07C_CCI) %>% 
  add_row(as_tibble(Ningaloo_TNT07C_NOAA)) %>% 
  # no data is available when logger data is added: add_row(as_tibble(Ningaloo_TNT07C_Logger)) %>% 
  add_row(as_tibble(Ningaloo_TNT07C_CCore) %>% 
            rename(sst = `Tantabiddi Sr/Ca`)) %>% 
  mutate(data_type = 
           case_when( data_type == "CCI" ~ "ningaloo_CCI",
                      data_type == "Logger" ~ "ningaloo_Logger", 
                      data_type == "NOAA" ~ "ningaloo_NOAA",
                      data_type == "Coral Core" ~ "ningaloo_coral_core",
                      TRUE ~ data_type))

TNT07C_joint <- dat %>% 
  pivot_wider(names_from = data_type, values_from = sst) %>% 
  drop_na() %>% 
  mutate(Site = "TNT07C")

#GGally::ggpairs(dat_joint)
## coral core is slightly more aligned with NOAA over CCI 
ggplot(TNT07C_joint, aes(x = ningaloo_coral_core, y = ningaloo_NOAA)) + 
  geom_point() + 
  geom_smooth(method = "gam") %>% 
  labs(title = "Sea Surface Temperature at TNT07C", x = "Coral Core", y = "NOAA")
# linear decreasing trend 
# gam1 <- gam(ningaloo_NOAA ~ s(ningaloo_coral_core, bs = "cs"), data = dat_joint, method = "REML")
# plot(gam1)
# summary(gam1)
# edf = 1.237 so linear + quadratic should give a good approx to the trend

# lm1 <- lm(ningaloo_NOAA ~ 1 + ningaloo_coral_core + I(ningaloo_coral_core^2), 
         # data = dat_joint)
# summary(lm1)

# p-value for quadratic is 0.312
# use linear model

NOAA_TNT07C <- lm(ningaloo_NOAA ~ 1 + ningaloo_coral_core, 
          data = TNT07C_joint)
# summary(lm1)

# repeat for CCI 
ggplot(TNT07C_joint, aes(x = ningaloo_coral_core, y = ningaloo_CCI)) + 
  geom_point() + 
  geom_smooth(method = "gam") %>% 
  labs(title = "Sea Surface Temperature at TNT07C", x = "Coral Core", y = "CCI")
# linear decreasing trend 
# gam2 <- gam(ningaloo_CCI ~ s(ningaloo_coral_core, bs = "cs"), data = dat_joint, method = "REML")
# plot(gam2)
# summary(gam2)
# edf = 1.139 so linear + quadratic should give a good approx to the trend

# lm2 <- lm(ningaloo_CCI ~ 1 + ningaloo_coral_core + I(ningaloo_coral_core^2), 
         # data = dat_joint)
# summary(lm2)

# p-value for quadratic is 0.726
# use linear model

CCI_TNT07C <- lm(ningaloo_CCI ~ 1 + ningaloo_coral_core, 
          data = TNT07C_joint)
# summary(lm2)

modelsummary::modelsummary(list(NOAA_TNT07C, CCI_TNT07C))

##BUN05A
##Only annual coral core data

Ningaloo_BUN05A_CCI <- read_csv(here::here("data_raw", "CCI_BUN05A.csv"))
Ningaloo_BUN05A_CCI <- Ningaloo_BUN05A_CCI %>% 
  mutate(sst = as.numeric(str_sub(Ningaloo_BUN05A_CCI$`mean temperature deg C`, 3, 13))) %>%  #remove punctuation [[ and ]] from temperature data
  select(-`mean temperature deg C`) %>%  #remove column with [[ and ]]
  mutate(data_type = "CCI") %>%  #prepare data for binding with other data types
  rename(date = daily_date) %>%  #prepare data for binding with other data types
  select(data_type, date, sst) %>%  #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

Ningaloo_BUN05A_CCore <- read_csv(here::here("data_raw", "CCore_Ningaloo_BUN05A_year.csv"))
Ningaloo_BUN05A_CCore <- Ningaloo_BUN05A_CCore %>% 
  mutate(data_type = "Coral Core") %>% #prepare data for binding with other data types
  mutate(month = "01") %>% 
  mutate(date = str_c(year, month, sep = "-")) %>% 
  mutate(date = ym(date)) %>% 
  select(data_type, date, `Bundegi Sr/Ca`) %>% 
  as_tsibble(index = date) # convert them to tsibble

Ningaloo_BUN05A_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_BUNDEGI_BR.csv"))
Ningaloo_BUN05A_Logger <- Ningaloo_BUN05A_Logger %>% 
  rename(sst = mean_SST) %>% #prepare data for binding with other data types
  mutate(data_type = "Logger") %>% #prepare data for binding with other data types
  select(data_type, date, sst) %>%   #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

Ningaloo_BUN05A_NOAA <- read_csv(here::here("data_raw", "NOAA_BUN05A_SST.csv"))
Ningaloo_BUN05A_NOAA <- Ningaloo_BUN05A_NOAA %>% 
  mutate(data_type = "NOAA") %>%  #prepare data for binding with other data types
  select(-date) %>% #remove monthly date column
  rename(date = Date) %>% #rename daily date column to prepare for binding with other data types
  select(data_type, date, sst) %>%  #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

dat <- as_tibble(Ningaloo_BUN05A_CCI) %>% 
  add_row(as_tibble(Ningaloo_BUN05A_NOAA)) %>% 
  # no data is available when logger data is added: add_row(as_tibble(Ningaloo_BUN05A_Logger)) %>% 
  add_row(as_tibble(Ningaloo_BUN05A_CCore) %>% 
            rename(sst = `Bundegi Sr/Ca`)) %>% 
  mutate(data_type = 
           case_when( data_type == "CCI" ~ "ningaloo_CCI",
                      data_type == "Logger" ~ "ningaloo_Logger", 
                      data_type == "NOAA" ~ "ningaloo_NOAA",
                      data_type == "Coral Core" ~ "ningaloo_coral_core",
                      TRUE ~ data_type))

BUN05A_joint <- dat %>% 
  pivot_wider(names_from = data_type, values_from = sst) %>% 
  drop_na() %>% 
  mutate(Site = "BUN05A")

#GGally::ggpairs(dat_joint)
## coral core is more aligned with CCI than NOAA 
ggplot(BUN05A_joint, aes(x = ningaloo_coral_core, y = ningaloo_NOAA)) + 
  geom_point() + 
  geom_smooth(method = "gam") %>% 
  labs(title = "Sea Surface Temperature at BUN05A", x = "Coral Core", y = "NOAA")
# linear decreasing trend 
# gam1 <- gam(ningaloo_NOAA ~ s(ningaloo_coral_core, bs = "cs"), data = dat_joint, method = "REML")
# plot(gam1)
# summary(gam1)
# edf = 1.032 so quadratic might not give a good approx to the trend

# lm1 <- lm(ningaloo_NOAA ~ 1 + ningaloo_coral_core + I(ningaloo_coral_core^2), 
        #  data = dat_joint)
# summary(lm1)

# p-value for quadratic is 0.610
# use linear model

NOAA_BUN05A <- lm(ningaloo_NOAA ~ 1 + ningaloo_coral_core, 
          data = BUN05A_joint)
# summary(lm1)

# repeat for CCI 
ggplot(BUN05A_joint, aes(x = ningaloo_coral_core, y = ningaloo_CCI)) + 
  geom_point() + 
  geom_smooth(method = "gam") %>% 
  labs(title = "Sea Surface Temperature at BUN05A", x = "Coral Core", y = "CCI")
# linear decreasing trend 
# gam2 <- gam(ningaloo_CCI ~ s(ningaloo_coral_core, bs = "cs"), data = dat_joint, method = "REML")
# plot(gam2)
# summary(gam2)
# edf = 1.221 so linear + quadratic should give a good approx to the trend

# lm2 <- lm(ningaloo_CCI ~ 1 + ningaloo_coral_core + I(ningaloo_coral_core^2), 
        #  data = dat_joint)
# summary(lm2)

# p-value for quadratic is 0.816
# use linear model

CCI_BUN05A <- lm(ningaloo_CCI ~ 1 + ningaloo_coral_core, 
          data = BUN05A_joint)
# summary(lm2)

modelsummary::modelsummary(list(NOAA_BUN05A, CCI_BUN05A))

```



```{r Houtman_Abrolhos_Islands, message = FALSE, include = FALSE}
##Wallabi Island
Wallabi_Island_CCI <- read_csv(here::here("data_raw", "CCI_Wallabi_Island.csv"))
Wallabi_Island_CCI <- Wallabi_Island_CCI %>% 
  mutate(sst = as.numeric(str_sub(Wallabi_Island_CCI$`mean temperature deg C`, 3, 13))) %>%  #remove punctuation [[ and ]] from temperature data
  select(-`mean temperature deg C`) %>%  #remove column with [[ and ]]
  mutate(data_type = "CCI") %>%  #prepare data for binding with other data types
  rename(date = daily_date) %>%  #prepare data for binding with other data types
  select(data_type, date, sst) %>%  #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

Wallabi_Island_CCore <- read_csv(here::here("data_raw", "CCore_H_Abrol_Wallabi_Year_Month.csv"))
Wallabi_Island_CCore <- Wallabi_Island_CCore %>% 
  mutate(data_type = "Coral Core") %>% #prepare data for binding with other data types
  mutate(date = str_c(year, month, sep = "-")) %>% 
  mutate(date = ym(date)) %>% 
  select(data_type, date, `d18O`) %>%     #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

Wallabi_Island_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_NTHFISHFL1.csv"))
Wallabi_Island_Logger <- Wallabi_Island_Logger %>% 
  rename(sst = mean_SST) %>% #prepare data for binding with other data types
  mutate(data_type = "Logger") %>% #prepare data for binding with other data types
  select(data_type, date, sst) %>%   #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

Wallabi_Island_NOAA <- read_csv(here::here("data_raw", "NOAA_Wallabi_Island_SST.csv"))
Wallabi_Island_NOAA <- Wallabi_Island_NOAA %>% 
  mutate(data_type = "NOAA") %>%  #prepare data for binding with other data types
  select(-date) %>% #remove monthly date column
  rename(date = Date) %>% #rename daily date column to prepare for binding with other data types
  select(data_type, date, sst) %>%  #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

dat <- as_tibble(Wallabi_Island_CCI) %>% 
  add_row(as_tibble(Wallabi_Island_NOAA)) %>% 
  # no available data if logger data is included : add_row(as_tibble(Wallabi_Island_Logger)) %>% 
  add_row(as_tibble(Wallabi_Island_CCore) %>% 
            rename(sst = `d18O`)) %>% 
  mutate(data_type = 
           case_when( data_type == "CCI" ~ "HAbrol_CCI",
                      data_type == "Logger" ~ "HAbrol_Logger", 
                      data_type == "NOAA" ~ "HAbrol_NOAA",
                      data_type == "Coral Core" ~ "HAbrol_coral_core",
                      TRUE ~ data_type))

Wallabi_Island_joint <- dat %>% 
  pivot_wider(names_from = data_type, values_from = sst) %>% 
  drop_na() %>% 
  mutate(Site = "Wallabi Island")

#GGally::ggpairs(dat_joint)
## coral core is slightly more aligned with CCI than NOAA 
ggplot(Wallabi_Island_joint, aes(x = HAbrol_coral_core, y = HAbrol_NOAA)) + 
  geom_point() + 
  geom_smooth(method = "gam") %>% 
  labs(title = "Sea Surface Temperature at Wallabi Island", x = "Coral Core", y = "NOAA")
# trend is explained by a curvature. 
# gam1 <- gam(HAbrol_NOAA ~ s(HAbrol_coral_core, bs = "cs"), data = dat_joint, method = "REML")
# plot(gam1)
# summary(gam1)
# edf = 3.398 so linear + quadratic should give a good approx to the trend

NOAA_Wallabi_Island <- lm(HAbrol_NOAA ~ 1 + HAbrol_coral_core + I(HAbrol_coral_core^2), 
          data = Wallabi_Island_joint)
# summary(lm1)

# p-value for quadratic is significant

# repeat for CCI 
ggplot(Wallabi_Island_joint, aes(x = HAbrol_coral_core, y = HAbrol_CCI)) + 
  geom_point() + 
  geom_smooth(method = "gam") %>% 
  labs(title = "Sea Surface Temperature at Wallabi Island", x = "Coral Core", y = "CCI")
# trend is explained by curvature. 
# gam2 <- gam(HAbrol_CCI ~ s(HAbrol_coral_core, bs = "cs"), data = dat_joint, method = "REML")
# plot(gam2)
# summary(gam2)
# edf = 2.975 so linear + quadratic should give a good approx to the trend

CCI_Wallabi_Island <- lm(HAbrol_CCI ~ 1 + HAbrol_coral_core + I(HAbrol_coral_core^2), 
          data = Wallabi_Island_joint)
# summary(lm2)

# p-value for quadratic is significant

modelsummary::modelsummary(list(NOAA_Wallabi_Island, CCI_Wallabi_Island))

##HAB10A d18O Proxy
##Only annual coral core data

HAB10A_d18O_CCI <- read_csv(here::here("data_raw", "CCI_HAB10A.csv"))
HAB10A_d18O_CCI <- HAB10A_d18O_CCI %>% 
  mutate(sst = as.numeric(str_sub(HAB10A_d18O_CCI$`mean temperature deg C`, 3, 13))) %>%  #remove punctuation [[ and ]] from temperature data
  select(-`mean temperature deg C`) %>%  #remove column with [[ and ]]
  mutate(data_type = "CCI") %>%  #prepare data for binding with other data types
  rename(date = daily_date) %>%  #prepare data for binding with other data types
  select(data_type, date, sst) %>%  #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

HAB10A_d18O_CCore <- read_csv(here::here("data_raw", "CCore_H_Abrol_HAB_year.csv"))

HAB10A_d18O_CCore <- HAB10A_d18O_CCore %>% 
  mutate(data_type = "Coral Core") %>% #prepare data for binding with other data types
  mutate(month = "01") %>% 
  mutate(date = str_c(year, month, sep = "-")) %>% 
  mutate(date = ym(date)) %>% 
  select(data_type, date, `HAB10A d18O`) %>% 
  as_tsibble(index = date) # convert them to tsibble

HAB10A_d18O_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_NTHFISHFL1.csv"))
HAB10A_d18O_Logger <- HAB10A_d18O_Logger %>% 
  rename(sst = mean_SST) %>% #prepare data for binding with other data types
  mutate(data_type = "Logger") %>% #prepare data for binding with other data types
  select(data_type, date, sst) %>%   #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

HAB10A_d18O_NOAA <- read_csv(here::here("data_raw", "NOAA_HAB10A_d18O_Proxy_SST.csv"))
HAB10A_d18O_NOAA <- HAB10A_d18O_NOAA %>% 
  mutate(data_type = "NOAA") %>%  #prepare data for binding with other data types
  select(-date) %>% #remove monthly date column
  rename(date = Date) %>% #rename daily date column to prepare for binding with other data types
  select(data_type, date, sst) %>%  #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

dat <- as_tibble(HAB10A_d18O_CCI) %>% 
  add_row(as_tibble(HAB10A_d18O_NOAA)) %>% 
  # no available data if logger data is included : add_row(as_tibble(HAB10A_d18O_Logger)) %>% 
  add_row(as_tibble(HAB10A_d18O_CCore) %>% 
            rename(sst = `HAB10A d18O`)) %>% 
  mutate(data_type = 
           case_when( data_type == "CCI" ~ "HAbrol_CCI",
                      data_type == "Logger" ~ "HAbrol_Logger", 
                      data_type == "NOAA" ~ "HAbrol_NOAA",
                      data_type == "Coral Core" ~ "HAbrol_coral_core",
                      TRUE ~ data_type))

HAB10A_d18O_joint <- dat %>% 
  pivot_wider(names_from = data_type, values_from = sst) %>% 
  drop_na() %>% 
  mutate(Site = "HAB10A d18O")

#GGally::ggpairs(dat_joint)
## coral core is slightly more aligned with NOAA than CCI 
ggplot(HAB10A_d18O_joint, aes(x = HAbrol_coral_core, y = HAbrol_NOAA)) + 
  geom_point() + 
  geom_smooth(method = "gam") %>% 
  labs(title = "Sea Surface Temperature at HAB10A d18O", x = "Coral Core", y = "NOAA")
# linear decreasing trend with a slight curvature. 
# gam1 <- gam(HAbrol_NOAA ~ s(HAbrol_coral_core, bs = "cs"), data = dat_joint, method = "REML")
# plot(gam1)
# summary(gam1)
# edf = 1.16 so linear + quadratic should give a good approx to the trend

# lm1 <- lm(HAbrol_NOAA ~ 1 + HAbrol_coral_core + I(HAbrol_coral_core^2), 
#          data = dat_joint)
# summary(lm1)

# p-value for quadratic is 0.0657
# use linear model

NOAA_HAB10A_d18O <- lm(HAbrol_NOAA ~ 1 + HAbrol_coral_core, 
          data = HAB10A_d18O_joint)
# summary(lm1)

# repeat for CCI 
ggplot(HAB10A_d18O_joint, aes(x = HAbrol_coral_core, y = HAbrol_CCI)) + 
  geom_point() + 
  geom_smooth(method = "gam") %>% 
  labs(title = "Sea Surface Temperature at HAB10A d18O", x = "Coral Core", y = "CCI")
# linear decreasing trend with a slight curvature. 
# gam2 <- gam(HAbrol_CCI ~ s(HAbrol_coral_core, bs = "cs"), data = dat_joint, method = "REML")
# plot(gam2)
# summary(gam2)
# edf = 0.9356 so quadratic model might not give a good approx to the trend

# lm2 <- lm(HAbrol_CCI ~ 1 + HAbrol_coral_core + I(HAbrol_coral_core^2), 
#          data = dat_joint)
# summary(lm2)

# p-value for quadratic is 0.272
# use linear model

CCI_HAB10A_d18O <- lm(HAbrol_CCI ~ 1 + HAbrol_coral_core, 
          data = HAB10A_d18O_joint)
# summary(lm2)

modelsummary::modelsummary(list(NOAA_HAB10A_d18O, CCI_HAB10A_d18O))

##HAB05B d18O Proxy
##Only annual coral core data

HAB05B_d18O_CCI <- read_csv(here::here("data_raw", "CCI_HAB05B.csv"))
HAB05B_d18O_CCI <- HAB05B_d18O_CCI %>% 
  mutate(sst = as.numeric(str_sub(HAB05B_d18O_CCI$`mean temperature deg C`, 3, 7))) %>%  #remove punctuation [[ and ]] from temperature data
  select(-`mean temperature deg C`) %>%  #remove column with [[ and ]]
  mutate(data_type = "CCI") %>%  #prepare data for binding with other data types
  rename(date = daily_date) %>%  #prepare data for binding with other data types
  select(data_type, date, sst) %>%  #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

HAB05B_d18O_CCore <- read_csv(here::here("data_raw", "CCore_H_Abrol_HAB_year.csv"))

HAB05B_d18O_CCore <- HAB05B_d18O_CCore %>% 
  mutate(data_type = "Coral Core") %>% #prepare data for binding with other data types
  mutate(month = "01") %>% 
  mutate(date = str_c(year, month, sep = "-")) %>% 
  mutate(date = ym(date)) %>% 
  select(data_type, date, `HAB05B d18O`) %>% 
  as_tsibble(index = date) # convert them to tsibble

HAB05B_d18O_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_NTHFISHFL1.csv"))
HAB05B_d18O_Logger <- HAB05B_d18O_Logger %>% 
  rename(sst = mean_SST) %>% #prepare data for binding with other data types
  mutate(data_type = "Logger") %>% #prepare data for binding with other data types
  select(data_type, date, sst) %>%   #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

HAB05B_d18O_NOAA <- read_csv(here::here("data_raw", "NOAA_HAB05B_d18O_Proxy_SST.csv"))
HAB05B_d18O_NOAA <- HAB05B_d18O_NOAA %>% 
  mutate(data_type = "NOAA") %>%  #prepare data for binding with other data types
  select(-date) %>% #remove monthly date column
  rename(date = Date) %>% #rename daily date column to prepare for binding with other data types
  select(data_type, date, sst) %>%  #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

##HAB10A Sr/Ca Proxy
##Only annual coral core data

HAB10A_SrCa_CCI <- read_csv(here::here("data_raw", "CCI_HAB10A.csv"))
HAB10A_SrCa_CCI <- HAB10A_SrCa_CCI %>% 
  mutate(sst = as.numeric(str_sub(HAB10A_SrCa_CCI$`mean temperature deg C`, 3, 13))) %>%  #remove punctuation [[ and ]] from temperature data
  select(-`mean temperature deg C`) %>%  #remove column with [[ and ]]
  mutate(data_type = "CCI") %>%  #prepare data for binding with other data types
  rename(date = daily_date) %>%  #prepare data for binding with other data types
  select(data_type, date, sst) %>%  #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

HAB10A_SrCa_CCore <- read_csv(here::here("data_raw", "CCore_H_Abrol_HAB_year.csv"))

HAB10A_SrCa_CCore <- HAB10A_SrCa_CCore %>% 
  mutate(data_type = "Coral Core") %>% #prepare data for binding with other data types
  mutate(month = "01") %>% 
  mutate(date = str_c(year, month, sep = "-")) %>% 
  mutate(date = ym(date)) %>% 
  select(data_type, date, `HAB10A Sr/Ca`) %>% 
  as_tsibble(index = date) # convert them to tsibble

HAB10A_SrCa_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_NTHFISHFL1.csv"))
HAB10A_SrCa_Logger <- HAB10A_SrCa_Logger %>% 
  rename(sst = mean_SST) %>% #prepare data for binding with other data types
  mutate(data_type = "Logger") %>% #prepare data for binding with other data types
  select(data_type, date, sst) %>%   #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

HAB10A_SrCa_NOAA <- read_csv(here::here("data_raw", "NOAA_HAB10A_SrCa_Proxy_SST.csv"))
HAB10A_SrCa_NOAA <- HAB10A_SrCa_NOAA %>% 
  mutate(data_type = "NOAA") %>%  #prepare data for binding with other data types
  select(-date) %>% #remove monthly date column
  rename(date = Date) %>% #rename daily date column to prepare for binding with other data types
  select(data_type, date, sst) %>%  #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

##HAB05B SrCa Proxy
##Only annual coral core data

HAB05B_SrCa_CCI <- read_csv(here::here("data_raw", "CCI_HAB05B.csv"))
HAB05B_SrCa_CCI <- HAB05B_SrCa_CCI %>% 
  mutate(sst = as.numeric(str_sub(HAB05B_SrCa_CCI$`mean temperature deg C`, 3, 7))) %>%  #remove punctuation [[ and ]] from temperature data
  select(-`mean temperature deg C`) %>%  #remove column with [[ and ]]
  mutate(data_type = "CCI") %>%  #prepare data for binding with other data types
  rename(date = daily_date) %>%  #prepare data for binding with other data types
  select(data_type, date, sst) %>%  #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

HAB05B_SrCa_CCore <- read_csv(here::here("data_raw", "CCore_H_Abrol_HAB_year.csv"))

HAB05B_SrCa_CCore <- HAB05B_SrCa_CCore %>% 
  mutate(data_type = "Coral Core") %>% #prepare data for binding with other data types
  mutate(month = "01") %>% 
  mutate(date = str_c(year, month, sep = "-")) %>% 
  mutate(date = ym(date)) %>% 
  select(data_type, date, `HAB05B Sr/Ca`) %>% 
  as_tsibble(index = date) # convert them to tsibble

HAB05B_SrCa_Logger <- read_csv(here::here("data_raw", "Logger_Avg_Daily_SST_NTHFISHFL1.csv"))
HAB05B_SrCa_Logger <- HAB05B_SrCa_Logger %>% 
  rename(sst = mean_SST) %>% #prepare data for binding with other data types
  mutate(data_type = "Logger") %>% #prepare data for binding with other data types
  select(data_type, date, sst) %>%   #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

HAB05B_SrCa_NOAA <- read_csv(here::here("data_raw", "NOAA_HAB05B_SrCa_Proxy_SST.csv"))
HAB05B_SrCa_NOAA <- HAB05B_SrCa_NOAA %>% 
  mutate(data_type = "NOAA") %>%  #prepare data for binding with other data types
  select(-date) %>% #remove monthly date column
  rename(date = Date) %>% #rename daily date column to prepare for binding with other data types
  select(data_type, date, sst) %>%  #select only useful columns
  as_tsibble(index = date) # convert them to tsibble

dat <- as_tibble(HAB05B_SrCa_CCI) %>% 
  add_row(as_tibble(HAB05B_SrCa_NOAA)) %>% 
  # no available data if logger data is included : add_row(as_tibble(HAB05B_SrCa_Logger)) %>% 
  add_row(as_tibble(HAB05B_SrCa_CCore) %>% 
            rename(sst = `HAB05B Sr/Ca`)) %>% 
  mutate(data_type = 
           case_when( data_type == "CCI" ~ "HAbrol_CCI",
                      data_type == "Logger" ~ "HAbrol_Logger", 
                      data_type == "NOAA" ~ "HAbrol_NOAA",
                      data_type == "Coral Core" ~ "HAbrol_coral_core",
                      TRUE ~ data_type))

HAB05B_SrCa_joint <- dat %>% 
  pivot_wider(names_from = data_type, values_from = sst) %>% 
  drop_na() %>% 
  mutate(Site = "HAB05B SrCa")

#GGally::ggpairs(dat_joint)
## coral core is slightly more aligned with CCI than NOAA
#ggplot(HAB05B_SrCa_joint, aes(x = HAbrol_coral_core, y = HAbrol_NOAA)) + 
#  geom_point() + 
#  geom_smooth(method = "gam")
# linear and slight decreasing trend
# gam1 <- gam(HAbrol_NOAA ~ s(HAbrol_coral_core, bs = "cs"), data = dat_joint, method = "REML")
# plot(gam1)
# summary(gam1)
# edf is 0.5599 LOW!

# lm1 <- lm(HAbrol_NOAA ~ 1 + HAbrol_coral_core + I(HAbrol_coral_core^2), 
#          data = dat_joint)
# summary(lm1)

# p-value for quadratic is 0.0828
# use linear model

# lm1 <- lm(HAbrol_NOAA ~ 1 + HAbrol_coral_core, 
#          data = dat_joint)
# summary(lm1)

# p-value for linear model is not significant as well

# repeat for CCI 
ggplot(HAB05B_SrCa_joint, aes(x = HAbrol_coral_core, y = HAbrol_CCI)) + 
  geom_point() + 
  geom_smooth(method = "gam") %>% 
  labs(title = "Sea Surface Temperature at HAB05B Sr/Ca", x = "Coral Core", y = "CCI")
# linear decreasing trend
# gam2 <- gam(HAbrol_CCI ~ s(HAbrol_coral_core, bs = "cs"), data = dat_joint, method = "REML")
# plot(gam2)
# summary(gam2)
# edf = 0.9579 so linear + quadratic should give a good approx to the trend

# lm2 <- lm(HAbrol_CCI ~ 1 + HAbrol_coral_core + I(HAbrol_coral_core^2), 
#          data = dat_joint)
# summary(lm2)

# p-value for quadratic is 0.217
# use linear model

CCI_HAB05B_SrCa <- lm(HAbrol_CCI ~ 1 + HAbrol_coral_core, 
          data = HAB05B_SrCa_joint)
# summary(lm2)

# p-value for linear model is significant

modelsummary::modelsummary(list(CCI_HAB05B_SrCa))
```




\newpage
```{r binding_data}

Browse <- rbind(BRS05_joint, BRS07_joint)
Cocos_Keeling <- rbind(DARL_joint, DAR3_joint)
Ningaloo <- rbind(Tantabiddi_13TNT_joint, Tantabiddi_08TNT_joint, TNT_joint, TNT07C_joint, Bundegi_13BND_joint, Bundegi_08BND_joint, BUN05A_joint)
Ningaloo_no_TNT <- rbind(Tantabiddi_13TNT_joint, Tantabiddi_08TNT_joint, TNT07C_joint, Bundegi_13BND_joint, Bundegi_08BND_joint, BUN05A_joint)
Ningaloo_B <- rbind(Bundegi_13BND_joint, Bundegi_08BND_joint, BUN05A_joint)
Ningaloo_T1 <- rbind(Tantabiddi_13TNT_joint, Tantabiddi_08TNT_joint, TNT07C_joint)
Ningaloo_T2 <- TNT_joint
HAbrol <- rbind(Wallabi_Island_joint, HAB10A_d18O_joint, HAB05B_SrCa_joint)


```


\newpage
```{r Browse_island_Plots_Table}
Browse_Plot_NOAA <- Browse %>% 
  ggplot(aes(x = browse_coral_core, y = browse_NOAA)) +
  geom_point() +
  geom_smooth() +
  labs(title = "Browse Island NOAA SST and Coral Core Proxy", x = "Coral Core", y = "NOAA") +
  facet_wrap("Site")

Browse_Plot_CCI <- Browse %>% 
  ggplot(aes(x = browse_coral_core, y = browse_CCI)) +
  geom_point() +
  geom_smooth() +
  labs(title = "Browse Island CCI SST and Coral Core Proxy", x = "Coral Core", y = "CCI") +
  facet_wrap("Site")

Browse_Plot_NOAA / Browse_Plot_CCI

C_Browse_Plot_NOAA <- Browse %>% 
  ggplot(aes(x = browse_coral_core, y = browse_NOAA, color = Site)) +
  geom_smooth() +
  labs(title = "Browse Island NOAA SST and Coral Core Proxy", x = "Coral Core", y = "NOAA", caption = "[Range of R Square values is from 0.497 to 0.570]")

C_Browse_Plot_CCI <- Browse %>% 
  ggplot(aes(x = browse_coral_core, y = browse_CCI, color = Site)) +
  geom_smooth() +
  labs(title = "Browse Island CCI SST and Coral Core Proxy", x = "Coral Core", y = "CCI", caption = "[Range of R Square values is from 0.568 to 0.622]")

C_Browse_Plot_NOAA / C_Browse_Plot_CCI 


```
\newpage

```{r Cocos_Keeling_Plots_Table}
Cocos_Keeling_Plot_NOAA <- Cocos_Keeling %>% 
  ggplot(aes(x = Cocos_coral_core, y = Cocos_NOAA)) +
  geom_point() +
  geom_smooth() +
  labs(title = "Cocos Keeling Island NOAA SST and Coral Core Proxy", x = "Coral Core", y = "NOAA") +
  facet_wrap("Site")

Cocos_Keeling_Plot_CCI <- Cocos_Keeling %>% 
  ggplot(aes(x = Cocos_coral_core, y = Cocos_CCI)) +
  geom_point() +
  geom_smooth() +
  labs(title = "Cocos Keeling Island CCI SST and Coral Core Proxy", x = "Coral Core", y = "CCI") +
  facet_wrap("Site")

Cocos_Keeling_Plot_NOAA / Cocos_Keeling_Plot_CCI

C_Cocos_Plot_NOAA <- Cocos_Keeling %>% 
  ggplot(aes(x = Cocos_coral_core, y = Cocos_NOAA, color = Site)) +
  geom_smooth() +
  labs(title = "Cocos Keeling Island NOAA SST and Coral Core Proxy", x = "Coral Core", y = "NOAA", caption = "[R Square values for both sites are 0.188]")

C_Cocos_Plot_CCI <- Cocos_Keeling %>% 
  ggplot(aes(x = Cocos_coral_core, y = Cocos_CCI, color = Site)) +
  geom_smooth() +
  labs(title = "Cocos Keeling Island CCI SST and Coral Core Proxy", x = "Coral Core", y = "CCI", caption = "[R Square values for both sites are 0.244]")

C_Cocos_Plot_NOAA / C_Cocos_Plot_CCI
```
\newpage
```{r Ningaloo_Plots_Table}
Ningaloo_Plot_NOAA <- Ningaloo %>% 
  ggplot(aes(x = ningaloo_coral_core, y = ningaloo_NOAA)) +
  geom_point() +
  geom_smooth() +
  labs(title = "Ningaloo Reef NOAA SST and Coral Core Proxy", x = "Coral Core", y = "NOAA") +
  facet_wrap("Site")

Ningaloo_Plot_CCI <- Ningaloo %>% 
  ggplot(aes(x = ningaloo_coral_core, y = ningaloo_CCI)) +
  geom_point() +
  geom_smooth() +
  labs(title = "Ningaloo Reef CCI SST and Coral Core Proxy", x = "Coral Core", y = "CCI") +
  facet_wrap("Site")

Ningaloo_Bundegi_Plot_NOAA <- Ningaloo_B %>% 
  ggplot(aes(x = ningaloo_coral_core, y = ningaloo_NOAA)) +
  geom_point() +
  geom_smooth() +
  labs(title = "Ningaloo Reef Bundegi and BUN05A NOAA SST and Coral Core Proxy", x = "Coral Core", y = "NOAA") +
  facet_wrap("Site")

Ningaloo_Bundegi_Plot_CCI <- Ningaloo_B %>% 
  ggplot(aes(x = ningaloo_coral_core, y = ningaloo_CCI)) +
  geom_point() +
  geom_smooth() +
  labs(title = "Ningaloo Reef Bundegi and BUN05A CCI SST and Coral Core Proxy", x = "Coral Core", y = "CCI") +
  facet_wrap("Site")

Ningaloo_Tantabiddi_Plot_NOAA <- Ningaloo_T1 %>% 
  ggplot(aes(x = ningaloo_coral_core, y = ningaloo_NOAA)) +
  geom_point() +
  geom_smooth() +
  labs(title = "Ningaloo Reef Tantabiddi NOAA SST and Coral Core Proxy", x = "Coral Core", y = "NOAA") +
  facet_wrap("Site")

Ningaloo_Tantabiddi_Plot_CCI <- Ningaloo_T1 %>% 
  ggplot(aes(x = ningaloo_coral_core, y = ningaloo_CCI)) +
  geom_point() +
  geom_smooth() +
  labs(title = "Ningaloo Reef Tantabiddi CCI SST and Coral Core Proxy", x = "Coral Core", y = "CCI") +
  facet_wrap("Site")

Ningaloo_TNT_Plot_NOAA <- Ningaloo_T2 %>% 
  ggplot(aes(x = ningaloo_coral_core, y = ningaloo_NOAA)) +
  geom_point() +
  geom_smooth() +
  labs(title = "Ningaloo Reef TNT NOAA SST and Coral Core Proxy", x = "Coral Core", y = "NOAA") +
  facet_wrap("Site")

Ningaloo_TNT_Plot_CCI <- Ningaloo_T2 %>% 
  ggplot(aes(x = ningaloo_coral_core, y = ningaloo_CCI)) +
  geom_point() +
  geom_smooth() +
  labs(title = "Ningaloo Reef TNT CCI SST and Coral Core Proxy", x = "Coral Core", y = "CCI") +
  facet_wrap("Site")

Ningaloo_Plot_NOAA 
Ningaloo_Plot_CCI
Ningaloo_Bundegi_Plot_NOAA/Ningaloo_Bundegi_Plot_CCI
Ningaloo_Tantabiddi_Plot_NOAA/Ningaloo_Tantabiddi_Plot_CCI
Ningaloo_TNT_Plot_NOAA/Ningaloo_TNT_Plot_CCI

C_Ningaloo_Plot_NOAA <- Ningaloo %>% 
  ggplot(aes(x = ningaloo_coral_core, y = ningaloo_NOAA, color = Site)) +
  geom_smooth() +
  labs(title = "Ningaloo Reef NOAA SST and Coral Core Proxy", x = "Coral Core", y = "NOAA", caption = "[Range of R Square values is from 0.195 to 0.839]")

C_Ningaloo_Plot_CCI <- Ningaloo %>% 
  ggplot(aes(x = ningaloo_coral_core, y = ningaloo_CCI, color = Site)) +
  geom_smooth() +
  labs(title = "Ningaloo Reef CCI SST and Coral Core Proxy", x = "Coral Core", y = "CCI", caption = "[Range of R Square values is from 0.301 to 0.758]")

C_Ningaloo_Plot_NOAA / C_Ningaloo_Plot_CCI

C_Ningaloo_no_TNT_Plot_NOAA <- Ningaloo_no_TNT %>% 
  ggplot(aes(x = ningaloo_coral_core, y = ningaloo_NOAA, color = Site)) +
  geom_smooth() +
  labs(title = "Ningaloo Reef NOAA SST and Coral Core Proxy", x = "Coral Core", y = "NOAA", caption = "[Range of R Square values is from 0.195 to 0.839]")

C_Ningaloo_no_TNT_Plot_CCI <- Ningaloo_no_TNT %>% 
  ggplot(aes(x = ningaloo_coral_core, y = ningaloo_CCI, color = Site)) +
  geom_smooth() +
  labs(title = "Ningaloo Reef CCI SST and Coral Core Proxy", x = "Coral Core", y = "CCI", caption = "[Range of R Square values is from 0.301 to 0.758]")

C_Ningaloo_no_TNT_Plot_NOAA / C_Ningaloo_no_TNT_Plot_CCI

```
\newpage
```{r Houtman_Abrolhos_Plots_Table}
HAbrol_Plot_NOAA <- HAbrol %>% 
  ggplot(aes(x = HAbrol_coral_core, y = HAbrol_NOAA)) +
  geom_point() +
  geom_smooth() +
  labs(title = "Houtman Abrolhos NOAA SST and Coral Core Proxy", x = "Coral Core", y = "NOAA") +
  facet_wrap("Site")

HAbrol_Plot_CCI <- HAbrol %>% 
  ggplot(aes(x = HAbrol_coral_core, y = HAbrol_CCI)) +
  geom_point() +
  geom_smooth() +
  labs(title = "Houtman Abrolhos CCI SST and Coral Core Proxy", x = "Coral Core", y = "CCI") +
  facet_wrap("Site")

HAbrol_Plot_NOAA / HAbrol_Plot_CCI

C_HAbrol_Plot_NOAA <- HAbrol %>% 
  ggplot(aes(x = HAbrol_coral_core, y = HAbrol_NOAA, color = Site)) +
  geom_smooth() +
  labs(title = "Houtman Abrolhos NOAA SST and Coral Core Proxy", x = "Coral Core", y = "NOAA", caption = "[Range of R Square values is from 0.155 to 0.282]")

C_HAbrol_Plot_CCI <- HAbrol %>% 
  ggplot(aes(x = HAbrol_coral_core, y = HAbrol_CCI, color = Site)) +
  geom_smooth() +
  labs(title = "Houtman Abrolhos CCI SST and Coral Core Proxy", x = "Coral Core", y = "CCI", caption = "[Range of R Square values is from 0.142 to 0.336]") 

C_HAbrol_Plot_NOAA / C_HAbrol_Plot_CCI

Wallabi_Plot_NOAA <- Wallabi_Island_joint %>% 
  ggplot(aes(x = HAbrol_coral_core, y = HAbrol_NOAA, color = Site)) +
  geom_smooth() +
  labs(title = "Wallabi Island NOAA SST and Coral Core Proxy", x = "Coral Core", y = "NOAA", caption = "R Square value is 0.282")

Wallabi_Plot_CCI <- Wallabi_Island_joint %>% 
  ggplot(aes(x = HAbrol_coral_core, y = HAbrol_CCI, color = Site)) +
  geom_smooth() +
  labs(title = "Wallabi Island CCI SST and Coral Core Proxy", x = "Coral Core", y = "CCI", caption = "R Square value is 0.336")

Wallabi_Plot_NOAA / Wallabi_Plot_NOAA
```
\newpage
\begin{landscape}
```{r Tables}

modelsummary::modelsummary(list("BRS05" = NOAA_BRS05, "BRS07" = NOAA_BRS07, "DARL" = NOAA_DARL, "DAR3" = NOAA_DAR3, "13TNT" = NOAA_Tantabiddi_13TNT, "08TNT" = NOAA_Tantabiddi_08TNT, "TNT" = NOAA_TNT, "TNT07C" = NOAA_TNT07C, "13BND" = NOAA_Bundegi_13BND, "08BND" = NOAA_Bundegi_08BND, "BUN05A" = NOAA_BUN05A, "Wallabi Island" = NOAA_Wallabi_Island, "HAB10A d18O" = NOAA_HAB10A_d18O), title = "NOAA", coef_omit = "(Intercept)", coef_rename = c("browse_coral_core" = "L_Browse", "Cocos_coral_core" = "L_Cocos", "ningaloo_coral_core" = "L_Ningaloo", "I(ningaloo_coral_core^2)" = "Q_Ningaloo", "HAbrol_coral_core" = "L_HAbrol", "I(HAbrol_coral_core^2)" = "Q_HAbrol"), gof_omit = "BIC|Log.Lik.|F", output = 'kableExtra') %>% 
  kable_styling(position = "center", full_width = T) %>% 
  column_spec(column = 1, color = "purple") %>% 
  add_header_above(c(" " = 1, "Browse" = 2, "Cocos Keeling" = 2, "Ningaloo" = 7, "Houtman Abrolhos" = 2))

modelsummary::modelsummary(list("BRS05" = CCI_BRS05, "BRS07" = CCI_BRS07, "DARL" = CCI_DARL, "DAR3" = CCI_DAR3, "13TNT" = CCI_Tantabiddi_13TNT, "08TNT" = CCI_Tantabiddi_08TNT, "TNT" = CCI_TNT, "TNT07C" = CCI_TNT07C, "13BND" = CCI_Bundegi_13BND, "08BND" = CCI_Bundegi_08BND, "BUN05A" = CCI_BUN05A, "Wallabi Island" = CCI_Wallabi_Island, "HAB10A d18O" = CCI_HAB10A_d18O, "HAB05B SrCa" = CCI_HAB05B_SrCa), title = "CCI", coef_omit = "(Intercept)", coef_rename = c("browse_coral_core" = "L_Browse", "I(browse_coral_core^2)" = "Q_Browse", "Cocos_coral_core" = "L_Cocos", "ningaloo_coral_core" = "L_Ningaloo", "I(ningaloo_coral_core^2)" = "Q_Ningaloo", "HAbrol_coral_core" = "L_HAbrol", "I(HAbrol_coral_core^2)" = "Q_HAbrol"), gof_omit = "BIC|Log.Lik.|F", output = 'kableExtra') %>% 
  kable_styling(position = "center", full_width = T) %>% 
  column_spec(column = 1, color = "purple") %>% 
  add_header_above(c(" " = 1, "Browse" = 2, "Cocos Keeling" = 2, "Ningaloo" = 7, "Houtman Abrolhos" = 3))

```
\end{landscape}

## Frequency Analysis - Spectral Analysis of Time Series for Sr/Ca Coral Proxy sites

\newpage
```{r Frequency_Analysis_Browse, echo = FALSE}
library(dplR)

#Browse Island
#use _joint file with combined SST/Proxy values from NOAA, CCI and CCore

#BRS05 CCI
wave.out <- morlet(y1 = BRS05_joint$browse_CCI, x1 = as.numeric(year(BRS05_joint$date)), dj = 0.1, siglvl = 0.95)
wave.out$period <- wave.out$period/12
levs <- quantile(wave.out$Power, c(0, 0.25, 0.5, 0.75, 0.95, 1))


wave.avg_BRS05_CCI <- data.frame(power = apply(wave.out$Power, 2, mean), period = (wave.out$period), Type = "CCI")
#plot(wave.avg_BRS05_CCI$period, wave.avg_BRS05_CCI$power, type = "l")

#BRS05 NOAA
wave.out <- morlet(y1 = BRS05_joint$browse_NOAA, x1 = as.numeric(year(BRS05_joint$date)), dj = 0.1, siglvl = 0.95)
wave.out$period <- wave.out$period/12
levs <- quantile(wave.out$Power, c(0, 0.25, 0.5, 0.75, 0.95, 1))


wave.avg_BRS05_NOAA <- data.frame(power = apply(wave.out$Power, 2, mean), period = (wave.out$period), Type = "NOAA")
#plot(wave.avg_BRS05_NOAA$period, wave.avg_BRS05_NOAA$power, type = "l")

#BRS05 Coral Core

wave.out <- morlet(y1 = BRS05_joint$browse_coral_core, x1 = as.numeric(year(BRS05_joint$date)), dj = 0.1, siglvl = 0.95)
wave.out$period <- wave.out$period/12
levs <- quantile(wave.out$Power, c(0, 0.25, 0.5, 0.75, 0.95, 1))

wave.avg_BRS05_CCore <- data.frame(power = apply(wave.out$Power, 2, mean), period = (wave.out$period), Type = "Coral Core")
#plot(wave.avg_BRS05_CCore$period, wave.avg_BRS05_CCore$power, type = "l")

#combined BRS05 plot
wave.avg_BRS05_Combined <- as_tibble(rbind(wave.avg_BRS05_CCI, wave.avg_BRS05_NOAA))

wave.avg_BRS05_CCore <- as_tibble(wave.avg_BRS05_CCore)
BRS05_CCore <- ggplot(wave.avg_BRS05_CCore) +
  geom_line(aes(x = period, y = power, color = Type)) +
  scale_color_manual(values = "brown")
  
BRS05_Sat <- ggplot(wave.avg_BRS05_Combined) +
  geom_line(aes(x = period, y = power, color = Type)) +
  ggtitle("BRS05")

BRS05_Sat / BRS05_CCore #plot using patchwork
  
#BRS07 CCI
wave.out <- morlet(y1 = BRS07_joint$browse_CCI, x1 = as.numeric(year(BRS07_joint$date)), dj = 0.1, siglvl = 0.95)
wave.out$period <- wave.out$period/12
levs <- quantile(wave.out$Power, c(0, 0.25, 0.5, 0.75, 0.95, 1))


wave.avg_BRS07_CCI <- data.frame(power = apply(wave.out$Power, 2, mean), period = (wave.out$period), Type = "CCI")
#plot(wave.avg_BRS07_CCI$period, wave.avg_BRS07_CCI$power, type = "l")

#BRS07 NOAA
wave.out <- morlet(y1 = BRS07_joint$browse_NOAA, x1 = as.numeric(year(BRS07_joint$date)), dj = 0.1, siglvl = 0.95)
wave.out$period <- wave.out$period/12
levs <- quantile(wave.out$Power, c(0, 0.25, 0.5, 0.75, 0.95, 1))


wave.avg_BRS07_NOAA <- data.frame(power = apply(wave.out$Power, 2, mean), period = (wave.out$period), Type = "NOAA")
#plot(wave.avg_BRS07_NOAA$period, wave.avg_BRS07_NOAA$power, type = "l")

#BRS07 Coral Core

wave.out <- morlet(y1 = BRS07_joint$browse_coral_core, x1 = as.numeric(year(BRS07_joint$date)), dj = 0.1, siglvl = 0.95)
wave.out$period <- wave.out$period/12
levs <- quantile(wave.out$Power, c(0, 0.25, 0.5, 0.75, 0.95, 1))

wave.avg_BRS07_CCore <- data.frame(power = apply(wave.out$Power, 2, mean), period = (wave.out$period), Type = "Coral Core")
#plot(wave.avg_BRS07_CCore$period, wave.avg_BRS07_CCore$power, type = "l")

#combined BRS07 plot
wave.avg_BRS07_Combined <- as_tibble(rbind(wave.avg_BRS07_CCI, wave.avg_BRS07_NOAA))

wave.avg_BRS07_CCore <- as_tibble(wave.avg_BRS07_CCore)
BRS07_CCore <- ggplot(wave.avg_BRS07_CCore) +
  geom_line(aes(x = period, y = power, color = Type)) +
  scale_color_manual(values = "brown")
  
BRS07_Sat <- ggplot(wave.avg_BRS07_Combined) +
  geom_line(aes(x = period, y = power, color = Type)) +
  ggtitle("BRS07")

BRS07_Sat / BRS07_CCore #plot using patchwork

```

```{r Frequency_Analysis_Cocos, echo = FALSE}

#Cocos (Keeling) Island
#use _joint file with combined SST/Proxy values from NOAA, CCI and CCore

#DAR3 CCI
wave.out <- morlet(y1 = DAR3_joint$Cocos_CCI, x1 = as.numeric(year(DAR3_joint$date)), dj = 0.1, siglvl = 0.95)
wave.out$period <- wave.out$period/12
levs <- quantile(wave.out$Power, c(0, 0.25, 0.5, 0.75, 0.95, 1))


wave.avg_DAR3_CCI <- data.frame(power = apply(wave.out$Power, 2, mean), period = (wave.out$period), Type = "CCI")
#plot(wave.avg_DAR3_CCI$period, wave.avg_DAR3_CCI$power, type = "l")

#DAR3 NOAA
wave.out <- morlet(y1 = DAR3_joint$Cocos_NOAA, x1 = as.numeric(year(DAR3_joint$date)), dj = 0.1, siglvl = 0.95)
wave.out$period <- wave.out$period/12
levs <- quantile(wave.out$Power, c(0, 0.25, 0.5, 0.75, 0.95, 1))


wave.avg_DAR3_NOAA <- data.frame(power = apply(wave.out$Power, 2, mean), period = (wave.out$period), Type = "NOAA")
#plot(wave.avg_DAR3_NOAA$period, wave.avg_DAR3_NOAA$power, type = "l")

#DAR3 Coral Core

wave.out <- morlet(y1 = DAR3_joint$Cocos_coral_core, x1 = as.numeric(year(DAR3_joint$date)), dj = 0.1, siglvl = 0.95)
wave.out$period <- wave.out$period/12
levs <- quantile(wave.out$Power, c(0, 0.25, 0.5, 0.75, 0.95, 1))

wave.avg_DAR3_CCore <- data.frame(power = apply(wave.out$Power, 2, mean), period = (wave.out$period), Type = "Coral Core")
#plot(wave.avg_DAR3_CCore$period, wave.avg_DAR3_CCore$power, type = "l")

#combined DAR3 plot
wave.avg_DAR3_Combined <- as_tibble(rbind(wave.avg_DAR3_CCI, wave.avg_DAR3_NOAA))

wave.avg_DAR3_CCore <- as_tibble(wave.avg_DAR3_CCore)
DAR3_CCore <- ggplot(wave.avg_DAR3_CCore) +
  geom_line(aes(x = period, y = power, color = Type)) +
  scale_color_manual(values = "brown")
  
DAR3_Sat <- ggplot(wave.avg_DAR3_Combined) +
  geom_line(aes(x = period, y = power, color = Type)) +
  ggtitle("DAR3")

DAR3_Sat / DAR3_CCore #plot using patchwork
  
#DARL CCI
wave.out <- morlet(y1 = DARL_joint$Cocos_CCI, x1 = as.numeric(year(DARL_joint$date)), dj = 0.1, siglvl = 0.95)
wave.out$period <- wave.out$period/12
levs <- quantile(wave.out$Power, c(0, 0.25, 0.5, 0.75, 0.95, 1))


wave.avg_DARL_CCI <- data.frame(power = apply(wave.out$Power, 2, mean), period = (wave.out$period), Type = "CCI")
#plot(wave.avg_DARL_CCI$period, wave.avg_DARL_CCI$power, type = "l")

#DARL NOAA
wave.out <- morlet(y1 = DARL_joint$Cocos_NOAA, x1 = as.numeric(year(DARL_joint$date)), dj = 0.1, siglvl = 0.95)
wave.out$period <- wave.out$period/12
levs <- quantile(wave.out$Power, c(0, 0.25, 0.5, 0.75, 0.95, 1))


wave.avg_DARL_NOAA <- data.frame(power = apply(wave.out$Power, 2, mean), period = (wave.out$period), Type = "NOAA")
#plot(wave.avg_DARL_NOAA$period, wave.avg_DARL_NOAA$power, type = "l")

#DARL Coral Core

wave.out <- morlet(y1 = DARL_joint$Cocos_coral_core, x1 = as.numeric(year(DARL_joint$date)), dj = 0.1, siglvl = 0.95)
wave.out$period <- wave.out$period/12
levs <- quantile(wave.out$Power, c(0, 0.25, 0.5, 0.75, 0.95, 1))

wave.avg_DARL_CCore <- data.frame(power = apply(wave.out$Power, 2, mean), period = (wave.out$period), Type = "Coral Core")
#plot(wave.avg_DARL_CCore$period, wave.avg_DARL_CCore$power, type = "l")

#combined DARL plot
wave.avg_DARL_Combined <- as_tibble(rbind(wave.avg_DARL_CCI, wave.avg_DARL_NOAA))

wave.avg_DARL_CCore <- as_tibble(wave.avg_DARL_CCore)
DARL_CCore <- ggplot(wave.avg_DARL_CCore) +
  geom_line(aes(x = period, y = power, color = Type)) +
  scale_color_manual(values = "brown")
  
DARL_Sat <- ggplot(wave.avg_DARL_Combined) +
  geom_line(aes(x = period, y = power, color = Type)) +
  ggtitle("DARL")

DARL_Sat / DARL_CCore #plot using patchwork

```


```{r Frequency_Analysis_Ningaloo, echo = FALSE}

#Ningaloo Reef
#use _joint file with combined SST/Proxy values from NOAA, CCI and CCore

#Tantabiddi 13TNT CCI
wave.out <- morlet(y1 = Tantabiddi_13TNT_joint$ningaloo_CCI, x1 = as.numeric(year(Tantabiddi_13TNT_joint$date)), dj = 0.1, siglvl = 0.95)
wave.out$period <- wave.out$period/12
levs <- quantile(wave.out$Power, c(0, 0.25, 0.5, 0.75, 0.95, 1))


wave.avg_Tantabiddi_13TNT_CCI <- data.frame(power = apply(wave.out$Power, 2, mean), period = (wave.out$period), Type = "CCI")
#plot(wave.avg_Tantabiddi_13TNT_CCI$period, wave.avg_Tantabiddi_13TNT_CCI$power, type = "l")

#Tantabiddi 13TNT NOAA
wave.out <- morlet(y1 = Tantabiddi_13TNT_joint$ningaloo_NOAA, x1 = as.numeric(year(Tantabiddi_13TNT_joint$date)), dj = 0.1, siglvl = 0.95)
wave.out$period <- wave.out$period/12
levs <- quantile(wave.out$Power, c(0, 0.25, 0.5, 0.75, 0.95, 1))


wave.avg_Tantabiddi_13TNT_NOAA <- data.frame(power = apply(wave.out$Power, 2, mean), period = (wave.out$period), Type = "NOAA")
#plot(wave.avg_Tantabiddi_13TNT_NOAA$period, wave.avg_Tantabiddi_13TNT_NOAA$power, type = "l")

#Tantabiddi 13TNT Coral Core

wave.out <- morlet(y1 = Tantabiddi_13TNT_joint$ningaloo_coral_core, x1 = as.numeric(year(Tantabiddi_13TNT_joint$date)), dj = 0.1, siglvl = 0.95)
wave.out$period <- wave.out$period/12
levs <- quantile(wave.out$Power, c(0, 0.25, 0.5, 0.75, 0.95, 1))

wave.avg_Tantabiddi_13TNT_CCore <- data.frame(power = apply(wave.out$Power, 2, mean), period = (wave.out$period), Type = "Coral Core")
#plot(wave.avg_Tantabiddi_13TNT_CCore$period, wave.avg_Tantabiddi_13TNT_CCore$power, type = "l")

#combined Tantabiddi 13TNT plot
wave.avg_Tantabiddi_13TNT_Combined <- as_tibble(rbind(wave.avg_Tantabiddi_13TNT_CCI, wave.avg_Tantabiddi_13TNT_NOAA))

wave.avg_Tantabiddi_13TNT_CCore <- as_tibble(wave.avg_Tantabiddi_13TNT_CCore)
Tantabiddi_13TNT_CCore <- ggplot(wave.avg_Tantabiddi_13TNT_CCore) +
  geom_line(aes(x = period, y = power, color = Type)) +
  scale_color_manual(values = "brown")
  
Tantabiddi_13TNT_Sat <- ggplot(wave.avg_Tantabiddi_13TNT_Combined) +
  geom_line(aes(x = period, y = power, color = Type)) +
  ggtitle("13TNT")

Tantabiddi_13TNT_Sat / Tantabiddi_13TNT_CCore #plot using patchwork
  

#Tantabiddi 08TNT CCI
wave.out <- morlet(y1 = Tantabiddi_08TNT_joint$ningaloo_CCI, x1 = as.numeric(year(Tantabiddi_08TNT_joint$date)), dj = 0.1, siglvl = 0.95)
wave.out$period <- wave.out$period/12
levs <- quantile(wave.out$Power, c(0, 0.25, 0.5, 0.75, 0.95, 1))


wave.avg_Tantabiddi_08TNT_CCI <- data.frame(power = apply(wave.out$Power, 2, mean), period = (wave.out$period), Type = "CCI")
#plot(wave.avg_Tantabiddi_08TNT_CCI$period, wave.avg_Tantabiddi_08TNT_CCI$power, type = "l")

#Tantabiddi 08TNT NOAA
wave.out <- morlet(y1 = Tantabiddi_08TNT_joint$ningaloo_NOAA, x1 = as.numeric(year(Tantabiddi_08TNT_joint$date)), dj = 0.1, siglvl = 0.95)
wave.out$period <- wave.out$period/12
levs <- quantile(wave.out$Power, c(0, 0.25, 0.5, 0.75, 0.95, 1))


wave.avg_Tantabiddi_08TNT_NOAA <- data.frame(power = apply(wave.out$Power, 2, mean), period = (wave.out$period), Type = "NOAA")
#plot(wave.avg_Tantabiddi_08TNT_NOAA$period, wave.avg_Tantabiddi_08TNT_NOAA$power, type = "l")

#Tantabiddi 08TNT Coral Core

wave.out <- morlet(y1 = Tantabiddi_08TNT_joint$ningaloo_coral_core, x1 = as.numeric(year(Tantabiddi_08TNT_joint$date)), dj = 0.1, siglvl = 0.95)
wave.out$period <- wave.out$period/12
levs <- quantile(wave.out$Power, c(0, 0.25, 0.5, 0.75, 0.95, 1))

wave.avg_Tantabiddi_08TNT_CCore <- data.frame(power = apply(wave.out$Power, 2, mean), period = (wave.out$period), Type = "Coral Core")
#plot(wave.avg_Tantabiddi_08TNT_CCore$period, wave.avg_Tantabiddi_08TNT_CCore$power, type = "l")

#combined Tantabiddi 08TNT plot
wave.avg_Tantabiddi_08TNT_Combined <- as_tibble(rbind(wave.avg_Tantabiddi_08TNT_CCI, wave.avg_Tantabiddi_08TNT_NOAA))

wave.avg_Tantabiddi_08TNT_CCore <- as_tibble(wave.avg_Tantabiddi_08TNT_CCore)
Tantabiddi_08TNT_CCore <- ggplot(wave.avg_Tantabiddi_08TNT_CCore) +
  geom_line(aes(x = period, y = power, color = Type)) +
  scale_color_manual(values = "brown")
  
Tantabiddi_08TNT_Sat <- ggplot(wave.avg_Tantabiddi_08TNT_Combined) +
  geom_line(aes(x = period, y = power, color = Type)) +
  ggtitle("08TNT")

Tantabiddi_08TNT_Sat / Tantabiddi_08TNT_CCore #plot using patchwork

#Bundegi 13BND CCI
wave.out <- morlet(y1 = Bundegi_13BND_joint$ningaloo_CCI, x1 = as.numeric(year(Bundegi_13BND_joint$date)), dj = 0.1, siglvl = 0.95)
wave.out$period <- wave.out$period/12
levs <- quantile(wave.out$Power, c(0, 0.25, 0.5, 0.75, 0.95, 1))


wave.avg_Bundegi_13BND_CCI <- data.frame(power = apply(wave.out$Power, 2, mean), period = (wave.out$period), Type = "CCI")
#plot(wave.avg_Bundegi_13BND_CCI$period, wave.avg_Bundegi_13BND_CCI$power, type = "l")

#Bundegi 13BND NOAA
wave.out <- morlet(y1 = Bundegi_13BND_joint$ningaloo_NOAA, x1 = as.numeric(year(Bundegi_13BND_joint$date)), dj = 0.1, siglvl = 0.95)
wave.out$period <- wave.out$period/12
levs <- quantile(wave.out$Power, c(0, 0.25, 0.5, 0.75, 0.95, 1))


wave.avg_Bundegi_13BND_NOAA <- data.frame(power = apply(wave.out$Power, 2, mean), period = (wave.out$period), Type = "NOAA")
#plot(wave.avg_Bundegi_13BND_NOAA$period, wave.avg_Bundegi_13BND_NOAA$power, type = "l")

#Bundegi 13BND Coral Core

wave.out <- morlet(y1 = Bundegi_13BND_joint$ningaloo_coral_core, x1 = as.numeric(year(Bundegi_13BND_joint$date)), dj = 0.1, siglvl = 0.95)
wave.out$period <- wave.out$period/12
levs <- quantile(wave.out$Power, c(0, 0.25, 0.5, 0.75, 0.95, 1))

wave.avg_Bundegi_13BND_CCore <- data.frame(power = apply(wave.out$Power, 2, mean), period = (wave.out$period), Type = "Coral Core")
#plot(wave.avg_Bundegi_13BND_CCore$period, wave.avg_Bundegi_13BND_CCore$power, type = "l")

#combined Bundegi 13BND plot
wave.avg_Bundegi_13BND_Combined <- as_tibble(rbind(wave.avg_Bundegi_13BND_CCI, wave.avg_Bundegi_13BND_NOAA))

wave.avg_Bundegi_13BND_CCore <- as_tibble(wave.avg_Bundegi_13BND_CCore)
Bundegi_13BND_CCore <- ggplot(wave.avg_Bundegi_13BND_CCore) +
  geom_line(aes(x = period, y = power, color = Type)) +
  scale_color_manual(values = "brown")
  
Bundegi_13BND_Sat <- ggplot(wave.avg_Bundegi_13BND_Combined) +
  geom_line(aes(x = period, y = power, color = Type)) +
  ggtitle("13BND")

Bundegi_13BND_Sat / Bundegi_13BND_CCore #plot using patchwork
  
#Bundegi 08BND CCI
wave.out <- morlet(y1 = Bundegi_08BND_joint$ningaloo_CCI, x1 = as.numeric(year(Bundegi_08BND_joint$date)), dj = 0.1, siglvl = 0.95)
wave.out$period <- wave.out$period/12
levs <- quantile(wave.out$Power, c(0, 0.25, 0.5, 0.75, 0.95, 1))


wave.avg_Bundegi_08BND_CCI <- data.frame(power = apply(wave.out$Power, 2, mean), period = (wave.out$period), Type = "CCI")
#plot(wave.avg_Bundegi_08BND_CCI$period, wave.avg_Bundegi_08BND_CCI$power, type = "l")

#Bundegi 08BND NOAA
wave.out <- morlet(y1 = Bundegi_08BND_joint$ningaloo_NOAA, x1 = as.numeric(year(Bundegi_08BND_joint$date)), dj = 0.1, siglvl = 0.95)
wave.out$period <- wave.out$period/12
levs <- quantile(wave.out$Power, c(0, 0.25, 0.5, 0.75, 0.95, 1))


wave.avg_Bundegi_08BND_NOAA <- data.frame(power = apply(wave.out$Power, 2, mean), period = (wave.out$period), Type = "NOAA")
#plot(wave.avg_Bundegi_08BND_NOAA$period, wave.avg_Bundegi_08BND_NOAA$power, type = "l")

#Bundegi 08BND Coral Core

wave.out <- morlet(y1 = Bundegi_08BND_joint$ningaloo_coral_core, x1 = as.numeric(year(Bundegi_08BND_joint$date)), dj = 0.1, siglvl = 0.95)
wave.out$period <- wave.out$period/12
levs <- quantile(wave.out$Power, c(0, 0.25, 0.5, 0.75, 0.95, 1))

wave.avg_Bundegi_08BND_CCore <- data.frame(power = apply(wave.out$Power, 2, mean), period = (wave.out$period), Type = "Coral Core")
#plot(wave.avg_Bundegi_08BND_CCore$period, wave.avg_Bundegi_08BND_CCore$power, type = "l")

#combined Bundegi 08BND plot
wave.avg_Bundegi_08BND_Combined <- as_tibble(rbind(wave.avg_Bundegi_08BND_CCI, wave.avg_Bundegi_08BND_NOAA))

wave.avg_Bundegi_08BND_CCore <- as_tibble(wave.avg_Bundegi_08BND_CCore)
Bundegi_08BND_CCore <- ggplot(wave.avg_Bundegi_08BND_CCore) +
  geom_line(aes(x = period, y = power, color = Type)) +
  scale_color_manual(values = "brown")
  
Bundegi_08BND_Sat <- ggplot(wave.avg_Bundegi_08BND_Combined) +
  geom_line(aes(x = period, y = power, color = Type)) +
  ggtitle("08BND")

Bundegi_08BND_Sat / Bundegi_08BND_CCore #plot using patchwork

#TNT07C CCI
wave.out <- morlet(y1 = TNT07C_joint$ningaloo_CCI, x1 = as.numeric(year(TNT07C_joint$date)), dj = 0.1, siglvl = 0.95)
#wave.out$period <- wave.out$period/12 
#not necessary because dataset is annual
levs <- quantile(wave.out$Power, c(0, 0.25, 0.5, 0.75, 0.95, 1))


wave.avg_TNT07C_CCI <- data.frame(power = apply(wave.out$Power, 2, mean), period = (wave.out$period), Type = "CCI")
#plot(wave.avg_TNT07C_CCI$period, wave.avg_TNT07C_CCI$power, type = "l")

#TNT07C NOAA
wave.out <- morlet(y1 = TNT07C_joint$ningaloo_NOAA, x1 = as.numeric(year(TNT07C_joint$date)), dj = 0.1, siglvl = 0.95)
#wave.out$period <- wave.out$period/12
#not necessary because dataset is annual
levs <- quantile(wave.out$Power, c(0, 0.25, 0.5, 0.75, 0.95, 1))


wave.avg_TNT07C_NOAA <- data.frame(power = apply(wave.out$Power, 2, mean), period = (wave.out$period), Type = "NOAA")
#plot(wave.avg_TNT07C_NOAA$period, wave.avg_TNT07C_NOAA$power, type = "l")

#TNT07C Coral Core

wave.out <- morlet(y1 = TNT07C_joint$ningaloo_coral_core, x1 = as.numeric(year(TNT07C_joint$date)), dj = 0.1, siglvl = 0.95)
#wave.out$period <- wave.out$period/12
#not necessary because dataset is annual
levs <- quantile(wave.out$Power, c(0, 0.25, 0.5, 0.75, 0.95, 1))

wave.avg_TNT07C_CCore <- data.frame(power = apply(wave.out$Power, 2, mean), period = (wave.out$period), Type = "Coral Core")
#plot(wave.avg_TNT07C_CCore$period, wave.avg_TNT07C_CCore$power, type = "l")

#combined TNT07C plot
wave.avg_TNT07C_Combined <- as_tibble(rbind(wave.avg_TNT07C_CCI, wave.avg_TNT07C_NOAA))

wave.avg_TNT07C_CCore <- as_tibble(wave.avg_TNT07C_CCore)
TNT07C_CCore <- ggplot(wave.avg_TNT07C_CCore) +
  geom_line(aes(x = period, y = power, color = Type)) +
  scale_color_manual(values = "brown")
  
TNT07C_Sat <- ggplot(wave.avg_TNT07C_Combined) +
  geom_line(aes(x = period, y = power, color = Type)) +
  ggtitle("TNT07C")

TNT07C_Sat / TNT07C_CCore #plot using patchwork


#BUN05A CCI
wave.out <- morlet(y1 = BUN05A_joint$ningaloo_CCI, x1 = as.numeric(year(BUN05A_joint$date)), dj = 0.1, siglvl = 0.95)
#wave.out$period <- wave.out$period/12 
#not necessary because dataset is annual
levs <- quantile(wave.out$Power, c(0, 0.25, 0.5, 0.75, 0.95, 1))


wave.avg_BUN05A_CCI <- data.frame(power = apply(wave.out$Power, 2, mean), period = (wave.out$period), Type = "CCI")
#plot(wave.avg_BUN05A_CCI$period, wave.avg_BUN05A_CCI$power, type = "l")

#BUN05A NOAA
wave.out <- morlet(y1 = BUN05A_joint$ningaloo_NOAA, x1 = as.numeric(year(BUN05A_joint$date)), dj = 0.1, siglvl = 0.95)
#wave.out$period <- wave.out$period/12
#not necessary because dataset is annual
levs <- quantile(wave.out$Power, c(0, 0.25, 0.5, 0.75, 0.95, 1))


wave.avg_BUN05A_NOAA <- data.frame(power = apply(wave.out$Power, 2, mean), period = (wave.out$period), Type = "NOAA")
#plot(wave.avg_BUN05A_NOAA$period, wave.avg_BUN05A_NOAA$power, type = "l")

#BUN05A Coral Core

wave.out <- morlet(y1 = BUN05A_joint$ningaloo_coral_core, x1 = as.numeric(year(BUN05A_joint$date)), dj = 0.1, siglvl = 0.95)
#wave.out$period <- wave.out$period/12
#not necessary because dataset is annual
levs <- quantile(wave.out$Power, c(0, 0.25, 0.5, 0.75, 0.95, 1))

wave.avg_BUN05A_CCore <- data.frame(power = apply(wave.out$Power, 2, mean), period = (wave.out$period), Type = "Coral Core")
#plot(wave.avg_BUN05A_CCore$period, wave.avg_BUN05A_CCore$power, type = "l")

#combined BUN05A plot
wave.avg_BUN05A_Combined <- as_tibble(rbind(wave.avg_BUN05A_CCI, wave.avg_BUN05A_NOAA))

wave.avg_BUN05A_CCore <- as_tibble(wave.avg_BUN05A_CCore)
BUN05A_CCore <- ggplot(wave.avg_BUN05A_CCore) +
  geom_line(aes(x = period, y = power, color = Type)) +
  scale_color_manual(values = "brown")
  
BUN05A_Sat <- ggplot(wave.avg_BUN05A_Combined) +
  geom_line(aes(x = period, y = power, color = Type)) +
  ggtitle("BUN05A")

BUN05A_Sat / BUN05A_CCore #plot using patchwork

```

```{r Frequency_Analysis_Houtman_Abrol, echo = FALSE}

#Houtman Abrolhos Island
#use _joint file with combined SST/Proxy values from NOAA, CCI and CCore

#HAB05B SrCa CCI
wave.out <- morlet(y1 = HAB05B_SrCa_joint$HAbrol_CCI, x1 = as.numeric(year(HAB05B_SrCa_joint$date)), dj = 0.1, siglvl = 0.95)
#wave.out$period <- wave.out$period/12
#not necessary as dataset is annual
levs <- quantile(wave.out$Power, c(0, 0.25, 0.5, 0.75, 0.95, 1))


wave.avg_HAB05B_SrCa_CCI <- data.frame(power = apply(wave.out$Power, 2, mean), period = (wave.out$period), Type = "CCI")
#plot(wave.avg_HAB05B_SrCa_CCI$period, wave.avg_HAB05B_SrCa_CCI$power, type = "l")

#HAB05B SrCa NOAA
wave.out <- morlet(y1 = HAB05B_SrCa_joint$HAbrol_NOAA, x1 = as.numeric(year(HAB05B_SrCa_joint$date)), dj = 0.1, siglvl = 0.95)
#wave.out$period <- wave.out$period/12
#not necessary as dataset is annual
levs <- quantile(wave.out$Power, c(0, 0.25, 0.5, 0.75, 0.95, 1))


wave.avg_HAB05B_SrCa_NOAA <- data.frame(power = apply(wave.out$Power, 2, mean), period = (wave.out$period), Type = "NOAA")
#plot(wave.avg_HAB05B_SrCa_NOAA$period, wave.avg_HAB05B_SrCa_NOAA$power, type = "l")

#HAB05B SrCa Coral Core

wave.out <- morlet(y1 = HAB05B_SrCa_joint$HAbrol_coral_core, x1 = as.numeric(year(HAB05B_SrCa_joint$date)), dj = 0.1, siglvl = 0.95)
#wave.out$period <- wave.out$period/12
#not necessary as dataset is annual
levs <- quantile(wave.out$Power, c(0, 0.25, 0.5, 0.75, 0.95, 1))

wave.avg_HAB05B_SrCa_CCore <- data.frame(power = apply(wave.out$Power, 2, mean), period = (wave.out$period), Type = "Coral Core")
#plot(wave.avg_HAB05B_SrCa_CCore$period, wave.avg_HAB05B_SrCa_CCore$power, type = "l")

#combined HAB05B SrCa plot
wave.avg_HAB05B_SrCa_Combined <- as_tibble(rbind(wave.avg_HAB05B_SrCa_CCI, wave.avg_HAB05B_SrCa_NOAA))

wave.avg_HAB05B_SrCa_CCore <- as_tibble(wave.avg_HAB05B_SrCa_CCore)
HAB05B_SrCa_CCore <- ggplot(wave.avg_HAB05B_SrCa_CCore) +
  geom_line(aes(x = period, y = power, color = Type)) +
  scale_color_manual(values = "brown")
  
HAB05B_SrCa_Sat <- ggplot(wave.avg_HAB05B_SrCa_Combined) +
  geom_line(aes(x = period, y = power, color = Type)) +
  ggtitle("HAB05B")

HAB05B_SrCa_Sat / HAB05B_SrCa_CCore #plot using patchwork

```