---
title: "Raw SrCa TS"
author: "Vanessa Neo"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_packages_and_file, include = FALSE}
library(tidyverse)
library(lubridate)
library(patchwork)
library(ggpmisc)

Browse <- read_csv(here::here("data_raw/CCore_BRS05_BRS07_Year_Month.csv")) %>% 
  select(c(2,3,9,10)) %>% 
  mutate(date = ym(str_c(year, month)))

Browse05_SST_CCI <- read_csv(here::here("data_raw/CCore_SST_BRS05_CCI.csv"))

Browse05_SST_NOAA <- read_csv(here::here("data_raw/CCore_SST_BRS05_NOAA.csv"))

Browse07_SST_CCI <- read_csv(here::here("data_raw/CCore_SST_BRS07_CCI.csv"))

Browse07_SST_NOAA <- read_csv(here::here("data_raw/CCore_SST_BRS07_NOAA.csv"))
```

```{r plot_TS}

Browse05 <- Browse %>% 
  drop_na(`BRS05 Sr/Ca [mmol/mol]`) %>% 
  select(-c(`BRS07 Sr/Ca [mmol/mol]`, year, month))

Browse07 <- Browse %>% 
  drop_na(`BRS07 Sr/Ca [mmol/mol]`) %>% 
  select(-c(`BRS05 Sr/Ca [mmol/mol]`, year, month))

#To find out the range of Sr/Ca in BRS05 and BRS07
#BRS05
min_BRS05 <- min(Browse05$`BRS05 Sr/Ca [mmol/mol]`)
max_BRS05 <- max(Browse05$`BRS05 Sr/Ca [mmol/mol]`)
min_BRS05
max_BRS05
max_BRS05 - min_BRS05 #range
mean(Browse05$`BRS05 Sr/Ca [mmol/mol]`)
#BRS07
min_BRS07 <- min(Browse07$`BRS07 Sr/Ca [mmol/mol]`)
max_BRS07 <- max(Browse07$`BRS07 Sr/Ca [mmol/mol]`)
min_BRS07
max_BRS07
max_BRS07 - min_BRS07 #range
mean(Browse07$`BRS07 Sr/Ca [mmol/mol]`)

#Time Series of Raw Sr/Ca
BRS05_raw <- ggplot(Browse05) +
  geom_line(aes(x = date, y = `BRS05 Sr/Ca [mmol/mol]`), color = "coral") +
  labs(x = "Time", y = "BRS05 Sr/Ca \n [mmol/mol]") +
  theme(panel.grid.major.y = element_line(color = "grey", linetype = "dashed"),
        legend.key = element_rect(fill = "transparent"),
        plot.title = element_text( face = "bold", size = 12),
        legend.position = "right",
        panel.background = element_blank(),
        axis.line = element_line(color = "grey"),
        axis.title = element_text(size = 12)
  ) +
  scale_x_date(limits = as.Date(c("1980-01-01", Inf)))

BRS05_raw

ggsave("SrCa raw time series Browse BRS05.jpg", path = here::here("graphics/Supplementary"), dpi = 300, scale = 2)

BRS07_raw <- ggplot(Browse07) +
  geom_line(aes(x = date, y = `BRS07 Sr/Ca [mmol/mol]`), color = "skyblue") +
  labs(x = "Time", y = "BRS07 Sr/Ca \n [mmol/mol]") +
  theme(panel.grid.major.y = element_line(color = "grey", linetype = "dashed"),
        legend.key = element_rect(fill = "transparent"),
        plot.title = element_text( face = "bold", size = 12),
        legend.position = "right",
        panel.background = element_blank(),
        axis.line = element_line(color = "grey"),
        axis.title = element_text(size = 12)
  ) +
  scale_x_date(limits = as.Date(c("1980-01-01", Inf)))

BRS07_raw

ggsave("SrCa raw time series Browse BRS07.jpg", path = here::here("graphics/Supplementary"), dpi = 300, scale = 2)

Browse05 <- Browse05 %>% 
  mutate(Site = "BRS05") %>% 
  rename("SrCa" = 1)
Browse07 <- Browse07 %>% 
  mutate(Site = "BRS07") %>% 
  rename("SrCa" = 1)

Browse_combined <- rbind(Browse05, Browse07)

color <- c(BRS05 = "coral", BRS07 = "skyblue")

BRS_raw <- ggplot(Browse_combined) +
  geom_line(aes(x = date, y = SrCa, color = Site)) +
  scale_color_manual(values = color) +
  labs(x = "Time", y = "Sr/Ca \n [mmol/mol]") +
  theme(panel.grid.major.y = element_line(color = "grey", linetype = "dashed"),
        legend.key = element_rect(fill = "transparent"),
        plot.title = element_text( face = "bold", size = 12),
        legend.position = "right",
        panel.background = element_blank(),
        axis.line = element_line(color = "grey"),
        axis.title = element_text(size = 12)
  ) +
  scale_x_date(limits = as.Date(c("1980-01-01", Inf)))
  
BRS05_raw / BRS07_raw / BRS_raw

ggsave("SrCa raw time series Combined.jpg", path = here::here("graphics/Supplementary"), dpi = 300, scale = 1)

TableS1 <- read_csv(here::here("graphics/Supplementary/Table for Figure S1.csv"))

ggplot_Table <- ggplot() +
  theme_void() +
  annotate(geom = "table",
           x = 3,
           y = 4,
           label = list(TableS1), size = 5)

BRS05_raw /BRS07_raw / BRS_raw / ggplot_Table
 
ggsave("SrCa raw time series Combined with Table.jpg", path = here::here("graphics/Supplementary"), dpi = 300, scale = 1)

#Sr/Ca vs SST
CCI_05 <- ggplot(Browse05_SST_CCI) +
  geom_smooth(aes(x = sst, y = SrCa), color = "brown") +
  labs(x = "Sea Surface Temperature (CCI)", y = "SrCa [mmol/mol]", title = "BRS05 SrCa calibrated by CCI") +
  theme(panel.grid.major.y = element_line(color = "grey", linetype = "dashed"),
        legend.key = element_rect(fill = "transparent"),
        plot.title = element_text( face = "bold", size = 12),
        legend.position = "right",
        panel.background = element_blank(),
        axis.line = element_line(color = "grey"),
        axis.title = element_text(size = 12)
  ) 

CCI_05

ggsave("SrCa Browse BRS05 calibrated by CCI.jpg", path = here::here("graphics/Supplementary"), dpi = 300, scale = 2)

CCI_07 <- ggplot(Browse07_SST_CCI) +
  geom_smooth(aes(x = sst, y = SrCa), color = "brown") +
  labs(x = "Sea Surface Temperature (CCI)", y = "SrCa [mmol/mol]", title = "BRS07 SrCa calibrated by CCI") +
  theme(panel.grid.major.y = element_line(color = "grey", linetype = "dashed"),
        legend.key = element_rect(fill = "transparent"),
        plot.title = element_text( face = "bold", size = 12),
        legend.position = "right",
        panel.background = element_blank(),
        axis.line = element_line(color = "grey"),
        axis.title = element_text(size = 12)
  ) 

CCI_07

ggsave("SrCa Browse BRS07 calibrated by CCI.jpg", path = here::here("graphics/Supplementary"), dpi = 300, scale = 2)

NOAA_05 <- ggplot(Browse05_SST_NOAA) +
  geom_smooth(aes(x = sst, y = SrCa), color = "brown") +
  labs(x = "Sea Surface Temperature (NOAA)", y = "SrCa [mmol/mol]", title = "BRS05 SrCa calibrated by NOAA") +
  theme(panel.grid.major.y = element_line(color = "grey", linetype = "dashed"),
        legend.key = element_rect(fill = "transparent"),
        plot.title = element_text( face = "bold", size = 12),
        legend.position = "right",
        panel.background = element_blank(),
        axis.line = element_line(color = "grey"),
        axis.title = element_text(size = 12)
  ) 

NOAA_05

ggsave("SrCa Browse BRS05 calibrated by NOAA.jpg", path = here::here("graphics/Supplementary"), dpi = 300, scale = 2)

NOAA_07 <- ggplot(Browse07_SST_NOAA) +
  geom_smooth(aes(x = sst, y = SrCa), color = "brown") +
  labs(x = "Sea Surface Temperature (NOAA)", y = "SrCa [mmol/mol]", title = "BRS07 SrCa calibrated by NOAA") +
  theme(panel.grid.major.y = element_line(color = "grey", linetype = "dashed"),
        legend.key = element_rect(fill = "transparent"),
        plot.title = element_text( face = "bold", size = 12),
        legend.position = "right",
        panel.background = element_blank(),
        axis.line = element_line(color = "grey"),
        axis.title = element_text(size = 12)
  ) 

NOAA_07

ggsave("SrCa Browse BRS07 calibrated by NOAA.jpg", path = here::here("graphics/Supplementary"), dpi = 300, scale = 2)

(CCI_05 + CCI_07) / (NOAA_05 + NOAA_07)

ggsave("SrCa Browse calibrated by CCI and NOAA.jpg", path = here::here("graphics/Supplementary"), dpi = 300, scale = 3)

```

