---
title: "Study Sites"
author: "Vanessa Neo"
date: "`r lubridate::today()`"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Map, echo = FALSE, warning = FALSE, message = FALSE}
library(tidyverse)
library(maps)
library(ggrepel)
library(ggmap)
library(grid)

#register_google(key = "[your API key]", write = TRUE)
#code requires google API key to load maps

Study_Sites <- read_csv(here::here("data_raw", "Combined_Site_Coordinates_Full.csv")) 

watercolor <- get_map(location = c(lon = 110, lat = -20), zoom = 5, source = 'stamen', maptype="watercolor")

SS_Map <- ggmap(watercolor, fullpage = TRUE) +
  geom_point(data = Study_Sites, aes(x = Longitude, y = Latitude, shape = Reef), size = 5) +
  labs(title = "Study Sites", caption = "Number of Sites = 19", x = "Longitude", y = "Latitude") +
  theme(plot.caption = element_text(hjust = 0.5, size = 9), legend.title = element_blank(), legend.key = element_rect(fill = "transparent"), panel.background = element_rect(fill = "transparent"), legend.position = "right", legend.text = element_text(size = 7), plot.title = element_text(size = 22, hjust = 0.5), panel.border = element_rect(color = "black", fill = "transparent", size = 1), axis.text = element_text(size = 12), axis.title = element_text(size = 12)) 
  #xlim(85, 175) + #for full map
  #ylim(-50, 10) + #for full map
  #guides(shape = guide_legend(nrow = 2))
 
SS_Map

ggsave("study sites.png", path = here::here("graphics/Figures"), dpi = 300, width = 210, height = 100, units = "mm", limitsize = TRUE, bg = "transparent")

Cocos_getmap <- get_map(location = c(lon = 96.9, lat = -12.1), zoom = 13, source = 'stamen', maptype="watercolor")

Cocos <- ggmap(Cocos_getmap, fullpage = TRUE) +
  geom_point(data = Study_Sites, aes(x = Longitude, y = Latitude, shape = Reef), size = 5) +
  geom_label_repel(data = Study_Sites, aes(x = Longitude, y = Latitude, label = Site, size = 5)) +
  theme(plot.caption = element_text(hjust = 0.5, size = 9), legend.title = element_blank(), legend.key = element_rect(fill = "transparent"), panel.background = element_rect(fill = "transparent"), legend.position = "none", legend.text = element_blank(), plot.title = element_text(size = 22, hjust = 0.5), panel.border = element_rect(color = "black", fill = "transparent", linetype = "dashed")) +
  labs(title = "Cocos Keeling Island") 

Cocos

ggsave("Cocos.png", path = here::here("graphics/Figures"), dpi = 300, width = 210, height = 100, units = "mm", limitsize = TRUE, bg = "transparent")

Browse_getmap <- get_map(location = c(lon = 123.5, lat = -14.1), zoom = 11, source = 'stamen', maptype="watercolor")

Browse <- ggmap(Browse_getmap, fullpage = TRUE) +
  geom_point(data = Study_Sites, aes(x = Longitude, y = Latitude, shape = Reef), size = 5) +
  geom_label_repel(data = Study_Sites, aes(x = Longitude, y = Latitude, label = Site, size = 5)) +
  theme(plot.caption = element_text(hjust = 0.5, size = 9), legend.title = element_blank(), legend.key = element_rect(fill = "transparent"), panel.background = element_rect(fill = "transparent"), legend.position = "none", legend.text = element_blank(), plot.title = element_text(size = 22, hjust = 0.5), panel.border = element_rect(color = "black", fill = "transparent", linetype = "dashed")) +
  labs(title = "Browse Island") 

Browse

ggsave("Browse.png", path = here::here("graphics/Figures"), dpi = 300, width = 210, height = 100, units = "mm", limitsize = TRUE, bg = "transparent")

Scott_getmap <- get_map(location = c(lon = 121.9, lat = -13.9), zoom = 10, source = 'stamen', maptype="watercolor")

Scott <- ggmap(Scott_getmap, fullpage = TRUE) +
  geom_point(data = Study_Sites, aes(x = Longitude, y = Latitude, shape = Reef), size = 5) +
  geom_label_repel(data = Study_Sites, aes(x = Longitude, y = Latitude, label = Site, size = 5)) +
  theme(plot.caption = element_text(hjust = 0.5, size = 9), legend.title = element_blank(), legend.key = element_rect(fill = "transparent"), panel.background = element_rect(fill = "transparent"), legend.position = "none", legend.text = element_blank(), plot.title = element_text(size = 22, hjust = 0.5), panel.border = element_rect(color = "black", fill = "transparent", linetype = "dashed")) +
  labs(title = "Scott Reef") 

Scott

ggsave("Scott.png", path = here::here("graphics/Figures"), dpi = 300, width = 210, height = 100, units = "mm", limitsize = TRUE, bg = "transparent")

Ningaloo_getmap <- get_map(location = c(lon = 114.1, lat = -21.9), zoom = 11, source = 'stamen', maptype="watercolor")

Ningaloo <- ggmap(Ningaloo_getmap, fullpage = TRUE) +
  geom_point(data = Study_Sites, aes(x = Longitude, y = Latitude, shape = Reef), size = 5) +
  geom_label_repel(data = Study_Sites, aes(x = Longitude, y = Latitude, label = Site, size = 5)) +
  theme(plot.caption = element_text(hjust = 0.5, size = 9), legend.title = element_blank(), legend.key = element_rect(fill = "transparent"), panel.background = element_rect(fill = "transparent"), legend.position = "none", legend.text = element_blank(), plot.title = element_text(size = 22, hjust = 0.5), panel.border = element_rect(color = "black", fill = "transparent", linetype = "dashed")) +
  labs(title = "Ningaloo Reef") 

Ningaloo

ggsave("Ningaloo.png", path = here::here("graphics/Figures"), dpi = 300, width = 210, height = 100, units = "mm", limitsize = TRUE, bg = "transparent")

HAbrol_getmap <- get_map(location = c(lon = 113.75, lat = -28.46), zoom = 14, source = 'stamen', maptype="watercolor")

HAbrol <- ggmap(HAbrol_getmap, fullpage = TRUE) +
  geom_point(data = Study_Sites, aes(x = Longitude, y = Latitude, shape = Reef), size = 5) +
  geom_label_repel(data = Study_Sites, aes(x = Longitude, y = Latitude, label = Site, size = 5)) +
  theme(plot.caption = element_text(hjust = 0.5, size = 9), legend.title = element_blank(), legend.key = element_rect(fill = "transparent"), panel.background = element_rect(fill = "transparent"), legend.position = "none", legend.text = element_blank(), plot.title = element_text(size = 22, hjust = 0.5), panel.border = element_rect(color = "black", fill = "transparent", linetype = "dashed")) +
  labs(title = "Houtman Abrolhos Island")

HAbrol

ggsave("HAbrol.png", path = here::here("graphics/Figures"), dpi = 300, width = 210, height = 100, units = "mm", limitsize = TRUE, bg = "transparent")

#Creating publication map with main map + insets
mainmap <- viewport(width = 0.7, height = 0.55, x = 0.5, y = 0.17)
insetmap_Cocos <- viewport (width = 0.7, height = 0.55, x = 0.5, y = 0.72)
insetmap_Ningaloo <- viewport(width = 0.7, height = 0.55, x = 0.16, y = 0.72)
insetmap_HAbrol <- viewport(width = 0.7, height = 0.55, x = 0.16, y = 0.18)
insetmap_Scott <- viewport(width = 0.7, height = 0.55, x = 0.84, y = 0.72)
insetmap_Browse <- viewport(width = 0.7, height = 0.55, x = 0.84, y = 0.18)


jpeg(filename = "Study Sites with Insets.jpeg", res = 300, width = 680, height = 420, units = "mm" ) 

grid.newpage()
print(SS_Map, vp = mainmap)
print(Cocos, vp = insetmap_Cocos)
print(Ningaloo, vp = insetmap_Ningaloo)
print(HAbrol, vp = insetmap_HAbrol)
print(Scott, vp = insetmap_Scott)
print(Browse, vp = insetmap_Browse)
dev.off()
# ggsave("Study Sites with Insets.jpg", dpi = 300)


###Old Code###
#Aus <- map_data("world") %>% 
 # filter(region == "Australia")

#cols <- c("Browse Island" = "#CC6666", "Scott Reef" = "#9999CC", "Cocos (Keeling) Islands" = "#66CC99", "Ningaloo Reef" = "#FFCC99", "Houtman Abrolhos" = "dark blue")

# geom_polygon(data = Aus, aes(x = long, y = lat, group = group), fill = "grey") +
 # geom_point(data = Study_Sites, aes(x = Longitude, y = Latitude, color = Reef), size = 3 ) +
  #geom_label_repel(data = Study_Sites, aes(x = Longitude, y = Latitude, label = Site, fill = Reef), size = 4, max.overlaps = 40, segment.color = "grey80") +
  #scale_color_manual(values = cols) +
  #xlab("Longitude") +
  #ylab("Latitude") +
  #ylim(-40, -10) +
  #xlim(95, 125) +
  #labs(caption = "Number of Sites = 19")+
  #coord_fixed(ratio = 1) +
  #theme(legend.key = element_rect(fill = "transparent"), panel.grid = element_line(color = "transparent"), legend.position = "bottom", axis.title = element_text(size = 12), panel.background = element_rect(fill = "transparent"), axis.line = element_line(color = "black"), plot.caption = element_text(hjust = 0.5, size = 12), legend.title = element_blank() )

#ggsave("study sites.png", path = here::here("graphics/Figures"), dpi = 300, width = 210, height = 100, units = "mm", limitsize = FALSE)

```
